# 1 "hxhxmacrohost_NativeMacroModuleHostAbi.ml"
(* Generated by reflaxe.ocaml (WIP) *)
(* Haxe type: hxhxmacrohost.NativeMacroModuleHostAbi *)

let __reflaxe_ocaml__ = ()

type t = { __hx_type : Obj.t }

let create = fun () -> let self = ({ __hx_type = HxType.class_ "hxhxmacrohost.NativeMacroModuleHostAbi" } : t) in (
  ignore ();
  self
)

let __empty = fun () -> ({ __hx_type = HxType.class_ "hxhxmacrohost.NativeMacroModuleHostAbi" } : t)

let trim = fun value -> let tempResult = ref ("" : string) in (
  ignore (if value == Obj.magic (HxRuntime.hx_null) then let __assign_1 = ("" : string) in (
    tempResult := __assign_1;
    __assign_1
  ) else let __assign_2 = (StringTools.trim (value : string) : string) in (
    tempResult := __assign_2;
    __assign_2
  ));
  !tempResult
)

let normalizeSourceLabel = fun sourceLabel -> let tempString = ref ("" : string) in (
  ignore (if sourceLabel == Obj.magic (HxRuntime.hx_null) then let __assign_3 = ("" : string) in (
    tempString := __assign_3;
    __assign_3
  ) else let __assign_4 = (StringTools.trim (sourceLabel : string) : string) in (
    tempString := __assign_4;
    __assign_4
  ));
  let tempResult = ref ("" : string) in (
    ignore (if HxString.length (!tempString) = 0 then let __assign_5 = ("<unknown-native-macro-source>" : string) in (
      tempResult := __assign_5;
      __assign_5
    ) else let __assign_6 = (!tempString : string) in (
      tempResult := __assign_6;
      __assign_6
    ));
    !tempResult
  )
)

let fail = fun sourceLabel message -> ignore (let tempRight = ref ("" : string) in let tempString = ref ("" : string) in (
  ignore (if sourceLabel == Obj.magic (HxRuntime.hx_null) then let __assign_7 = ("" : string) in (
    tempString := __assign_7;
    __assign_7
  ) else let __assign_8 = (StringTools.trim (sourceLabel : string) : string) in (
    tempString := __assign_8;
    __assign_8
  ));
  ignore (if HxString.length (!tempString) = 0 then let __assign_9 = ("<unknown-native-macro-source>" : string) in (
    tempRight := __assign_9;
    __assign_9
  ) else let __assign_10 = (!tempString : string) in (
    tempRight := __assign_10;
    __assign_10
  ));
  HxType.hx_throw_typed_rtti (Obj.repr ((("native macro module registration (" ^ HxString.toStdString (!tempRight)) ^ "): ") ^ HxString.toStdString message)) ["Dynamic"; "String"]
))

let trimTrailingCr = fun line -> try let __fallback_result_15 = (
  ignore (if line == Obj.magic (HxRuntime.hx_null) then raise (HxRuntime.Hx_return (Obj.repr ("" : string))) else ());
  let len = HxString.length line in (
    ignore (if len = 0 then raise (HxRuntime.Hx_return (Obj.repr ("" : string))) else ());
    let tempResult = ref ("" : string) in (
      ignore (if let __nullable_11 = HxString.charCodeAt line (HxInt.sub len 1) in if __nullable_11 == HxRuntime.hx_null then false else Obj.obj __nullable_11 = 13 then let __assign_12 = (HxString.substr line 0 (HxInt.sub len 1) : string) in (
        tempResult := __assign_12;
        __assign_12
      ) else let __assign_13 = (line : string) in (
        tempResult := __assign_13;
        __assign_13
      ));
      !tempResult
    )
  )
) in Obj.magic __fallback_result_15 with
  | HxRuntime.Hx_return __ret_14 -> Obj.obj __ret_14

let requireToken = fun value field sourceLabel -> let tempString = ref ("" : string) in (
  ignore (if value == Obj.magic (HxRuntime.hx_null) then let __assign_16 = ("" : string) in (
    tempString := __assign_16;
    __assign_16
  ) else let __assign_17 = (StringTools.trim (value : string) : string) in (
    tempString := __assign_17;
    __assign_17
  ));
  ignore (if HxString.length (!tempString) = 0 then ignore (fail (sourceLabel : string) (HxString.toStdString field ^ " is required" : string)) else ());
  ignore (if HxString.indexOf (!tempString) "\n" 0 >= 0 || HxString.indexOf (!tempString) "\r" 0 >= 0 || HxString.indexOf (!tempString) "\t" 0 >= 0 then ignore (fail (sourceLabel : string) (HxString.toStdString field ^ " must not contain tab/newline characters" : string)) else ());
  !tempString
)

let decodeRow = fun line lineNumber sourceLabel -> let idx = HxString.indexOf line "\t" 0 in (
  ignore (if idx <= 0 || HxInt.add idx (HxString.length "\t") >= HxString.length line then ignore (fail (sourceLabel : string) (("invalid registration row at line " ^ string_of_int lineNumber) ^ " (expected pluginId<TAB>expr)" : string)) else ());
  ignore (if HxString.indexOf line "\t" (HxInt.add idx (HxString.length "\t")) >= 0 then ignore (fail (sourceLabel : string) (("invalid registration row at line " ^ string_of_int lineNumber) ^ " (too many separators)" : string)) else ());
  let pluginId = (requireToken (HxString.substr line 0 idx : string) ("pluginId" : string) (sourceLabel : string) : string) in let expr = (requireToken (HxString.substr line (HxInt.add idx (HxString.length "\t")) (-1) : string) ("expr" : string) (sourceLabel : string) : string) in let __anon_18 = HxAnon.create () in (
    ignore (HxAnon.set __anon_18 "pluginId" (Obj.repr pluginId));
    ignore (HxAnon.set __anon_18 "expr" (Obj.repr expr));
    __anon_18
  )
)

let requireHeaderInt = fun line prefix field expected lineNumber sourceLabel -> ignore ((
  ignore (if not (StringTools.startsWith (line : string) (prefix : string)) then ignore (fail (sourceLabel : string) ((((((("missing " ^ HxString.toStdString field) ^ " header at line ") ^ string_of_int lineNumber) ^ " (expected `") ^ HxString.toStdString prefix) ^ string_of_int expected) ^ "`)" : string)) else ());
  let tempString = ref ("" : string) in let value = (HxString.substr line (HxString.length prefix) (-1) : string) in (
    ignore (if value == Obj.magic (HxRuntime.hx_null) then let __assign_19 = ("" : string) in (
      tempString := __assign_19;
      __assign_19
    ) else let __assign_20 = (StringTools.trim (value : string) : string) in (
      tempString := __assign_20;
      __assign_20
    ));
    let parsed = Std.parseInt (!tempString : string) in (
      ignore (if parsed == HxRuntime.hx_null then ignore (fail (sourceLabel : string) ((((("invalid " ^ HxString.toStdString field) ^ " value `") ^ HxString.toStdString (!tempString)) ^ "` at line ") ^ string_of_int lineNumber : string)) else ());
      if not (let __nullable_21 = parsed in if __nullable_21 == HxRuntime.hx_null then false else Obj.obj __nullable_21 = expected) then ignore (fail (sourceLabel : string) ((((((HxString.toStdString field ^ " mismatch: expected ") ^ HxString.toStdString field) ^ "=") ^ string_of_int expected) ^ ", got ") ^ HxRuntime.nullable_int_toStdString parsed : string)) else ()
    )
  )
))

let decodeSnapshot = fun snapshot sourceLabel -> let tempString = ref ("" : string) in (
  ignore (if snapshot == Obj.magic (HxRuntime.hx_null) then let __assign_22 = ("" : string) in (
    tempString := __assign_22;
    __assign_22
  ) else let __assign_23 = (snapshot : string) in (
    tempString := __assign_23;
    __assign_23
  ));
  let lines = Obj.magic (HxString.split (!tempString) "\n") in let rows = Obj.magic (HxArray.create ()) in let headerState = ref 0 in let lineNumber = ref 0 in let _g = ref 0 in (
    ignore (try while !_g < HxArray.length lines do try ignore (let line = (HxArray.get (Obj.magic lines) (!_g) : string) in (
      ignore (let __old_24 = !_g in let __new_25 = HxInt.add __old_24 1 in (
        ignore (_g := __new_25);
        __new_25
      ));
      ignore (let __old_26 = !lineNumber in let __new_27 = HxInt.add __old_26 1 in (
        ignore (lineNumber := __new_27);
        __old_26
      ));
      let tempString1 = ref ("" : string) in let tempString2 = ref ("" : string) in (
        ignore (if line == Obj.magic (HxRuntime.hx_null) then let __assign_28 = ("" : string) in (
          tempString2 := __assign_28;
          __assign_28
        ) else let len = HxString.length line in if len = 0 then let __assign_29 = ("" : string) in (
          tempString2 := __assign_29;
          __assign_29
        ) else if let __nullable_30 = HxString.charCodeAt line (HxInt.sub len 1) in if __nullable_30 == HxRuntime.hx_null then false else Obj.obj __nullable_30 = 13 then let __assign_31 = (HxString.substr line 0 (HxInt.sub len 1) : string) in (
          tempString2 := __assign_31;
          __assign_31
        ) else let __assign_32 = (line : string) in (
          tempString2 := __assign_32;
          __assign_32
        ));
        let value = (!tempString2 : string) in (
          ignore (if value == Obj.magic (HxRuntime.hx_null) then let __assign_33 = ("" : string) in (
            tempString1 := __assign_33;
            __assign_33
          ) else let __assign_34 = (StringTools.trim (value : string) : string) in (
            tempString1 := __assign_34;
            __assign_34
          ));
          let normalized = (!tempString1 : string) in (
            ignore (if HxString.length normalized = 0 then raise (HxRuntime.Hx_continue) else ());
            ignore (if !headerState = 0 then ignore ((
              ignore (if not (HxString.equals normalized "v2") then ignore (fail (sourceLabel : string) (((("invalid snapshot version `" ^ HxString.toStdString normalized) ^ "` (expected `") ^ "v2") ^ "`)" : string)) else ());
              ignore (let __assign_35 = 1 in (
                headerState := __assign_35;
                __assign_35
              ));
              raise (HxRuntime.Hx_continue)
            )) else ());
            ignore (if !headerState = 1 then ignore ((
              ignore (requireHeaderInt (normalized : string) ("abiVersion=" : string) ("abiVersion" : string) 1 (!lineNumber) (sourceLabel : string));
              ignore (let __assign_36 = 2 in (
                headerState := __assign_36;
                __assign_36
              ));
              raise (HxRuntime.Hx_continue)
            )) else ());
            ignore (if !headerState = 2 then ignore ((
              ignore (requireHeaderInt (normalized : string) ("macroApiVersion=" : string) ("macroApiVersion" : string) 1 (!lineNumber) (sourceLabel : string));
              ignore (let __assign_37 = 3 in (
                headerState := __assign_37;
                __assign_37
              ));
              raise (HxRuntime.Hx_continue)
            )) else ());
            HxArray.push rows (decodeRow (normalized : string) (!lineNumber) (sourceLabel : string))
          )
        )
      )
    )) with
      | HxRuntime.Hx_continue -> () done with
      | HxRuntime.Hx_break -> ());
    ignore (if !headerState = 0 then ignore (fail (sourceLabel : string) (("snapshot is missing version header `" ^ "v2") ^ "`" : string)) else ());
    ignore (if !headerState = 1 then ignore (fail (sourceLabel : string) (("snapshot is missing abiVersion header `abiVersion=" ^ string_of_int 1) ^ "`" : string)) else ());
    ignore (if !headerState = 2 then ignore (fail (sourceLabel : string) (("snapshot is missing macroApiVersion header `macroApiVersion=" ^ string_of_int 1) ^ "`" : string)) else ());
    rows
  )
)

let exprsForPluginInternal = fun snapshot pluginId sourceLabel allowEmpty -> let expectedPluginId = (requireToken (pluginId : string) ("pluginId" : string) (sourceLabel : string) : string) in let rows = Obj.magic (decodeSnapshot (snapshot : string) (sourceLabel : string)) in let out = Obj.magic (HxArray.create ()) in let seenExprs = Obj.magic (HxMap.create_string ()) in let _g = ref 0 in (
  ignore (while !_g < HxArray.length rows do ignore (let row = HxArray.get (Obj.magic rows) (!_g) in (
    ignore (let __old_38 = !_g in let __new_39 = HxInt.add __old_38 1 in (
      ignore (_g := __new_39);
      __new_39
    ));
    ignore (if not (HxString.equals (Obj.obj (HxAnon.get row "pluginId")) expectedPluginId) then ignore (fail (sourceLabel : string) (((((("registration pluginId mismatch: expected `" ^ HxString.toStdString expectedPluginId) ^ "`, got `") ^ HxString.toStdString (Obj.obj (HxAnon.get row "pluginId"))) ^ "` (expr `") ^ HxString.toStdString (Obj.obj (HxAnon.get row "expr"))) ^ "`)" : string)) else ());
    ignore (if HxMap.exists_string seenExprs (Obj.obj (HxAnon.get row "expr")) then ignore (fail (sourceLabel : string) (((("duplicate expr registration `" ^ HxString.toStdString (Obj.obj (HxAnon.get row "expr"))) ^ "` for plugin `") ^ HxString.toStdString expectedPluginId) ^ "`" : string)) else ());
    ignore (HxMap.set_string seenExprs (Obj.obj (HxAnon.get row "expr")) true);
    HxArray.push out (Obj.obj (HxAnon.get row "expr"))
  )) done);
  ignore (if not (allowEmpty) && HxArray.length out = 0 then ignore (fail (sourceLabel : string) (("plugin `" ^ HxString.toStdString expectedPluginId) ^ "` did not register any macro expressions" : string)) else ());
  out
)

let exprsForPlugin = fun snapshot pluginId sourceLabel -> exprsForPluginInternal (snapshot : string) (pluginId : string) (sourceLabel : string) false

let exprsForPluginAllowEmpty = fun snapshot pluginId sourceLabel -> exprsForPluginInternal (snapshot : string) (pluginId : string) (sourceLabel : string) true