# 1 "backend_js_JsNameMangler.ml"
(* Generated by reflaxe.ocaml (WIP) *)
(* Haxe type: backend.js.JsNameMangler *)

let __reflaxe_ocaml__ = ()

type t = { __hx_type : Obj.t }

let create = fun () -> let self = ({ __hx_type = HxType.class_ "backend.js.JsNameMangler" } : t) in (
  ignore ();
  self
)

let __empty = fun () -> ({ __hx_type = HxType.class_ "backend.js.JsNameMangler" } : t)

let isReserved = fun (name : string) -> (let tempResult = ref (false : bool) in (
  ignore (match name with
    | "arguments" | "break" | "case" | "catch" | "class" | "const" | "continue" | "debugger" | "default" | "delete" | "do" | "else" | "enum" | "eval" | "export" | "extends" | "false" | "finally" | "for" | "function" | "if" | "implements" | "import" | "in" | "instanceof" | "interface" | "let" | "new" | "null" | "package" | "private" | "protected" | "public" | "return" | "static" | "super" | "switch" | "this" | "throw" | "true" | "try" | "typeof" | "var" | "void" | "while" | "with" | "yield" -> let __assign_2 = true in (
      tempResult := __assign_2;
      __assign_2
    )
    | _ -> let __assign_1 = false in (
      tempResult := __assign_1;
      __assign_1
    ));
  !tempResult
) : bool)

let identifier = fun (raw : string) -> (let tempString = ref (HxString.hx_null_string : string) in (
  ignore (if raw == HxString.hx_null_string then let __assign_3 = ("" : string) in (
    tempString := __assign_3;
    __assign_3
  ) else let __assign_4 = (raw : string) in (
    tempString := __assign_4;
    __assign_4
  ));
  let s = (!tempString : string) in let out = Obj.magic (StringBuf.create ()) in let _g = ref 0 in let _g1 = HxString.length s in (
    ignore (while !_g < _g1 do ignore (let i = let __old_5 = !_g in let __new_6 = HxInt.add __old_5 1 in (
      ignore (_g := __new_6);
      __old_5
    ) in let c = HxString.charCodeAt s i in let isAlpha = (let __nullable_7 = c in let __nullable_8 = 97 in if __nullable_7 == HxRuntime.hx_null then false else Obj.obj __nullable_7 >= __nullable_8) && (let __nullable_9 = c in let __nullable_10 = 122 in if __nullable_9 == HxRuntime.hx_null then false else Obj.obj __nullable_9 <= __nullable_10) || (let __nullable_11 = c in let __nullable_12 = 65 in if __nullable_11 == HxRuntime.hx_null then false else Obj.obj __nullable_11 >= __nullable_12) && (let __nullable_13 = c in let __nullable_14 = 90 in if __nullable_13 == HxRuntime.hx_null then false else Obj.obj __nullable_13 <= __nullable_14) in let isNum = (let __nullable_15 = c in let __nullable_16 = 48 in if __nullable_15 == HxRuntime.hx_null then false else Obj.obj __nullable_15 >= __nullable_16) && (let __nullable_17 = c in let __nullable_18 = 57 in if __nullable_17 == HxRuntime.hx_null then false else Obj.obj __nullable_17 <= __nullable_18) in let tempString1 = ref (HxString.hx_null_string : string) in (
      ignore (if isAlpha || isNum || (let __nullable_19 = c in if __nullable_19 == HxRuntime.hx_null then false else Obj.obj __nullable_19 = 95) then let __assign_20 = (HxString.fromCharCode (let __nullable_int_21 = c in if __nullable_int_21 == HxRuntime.hx_null then 0 else Obj.obj __nullable_int_21) : string) in (
        tempString1 := __assign_20;
        __assign_20
      ) else let __assign_22 = ("_" : string) in (
        tempString1 := __assign_22;
        __assign_22
      ));
      let ch = (!tempString1 : string) in (
        ignore (if i = 0 && isNum then ignore (StringBuf.add (Obj.magic out) (Obj.repr "_")) else ());
        StringBuf.add (Obj.magic out) (Obj.repr ch)
      )
    )) done);
    let r = ref (StringBuf.toString (Obj.magic out) () : string) in (
      ignore (if HxString.length (!r) = 0 then ignore (let __assign_23 = ("_" : string) in (
        r := __assign_23;
        __assign_23
      )) else ());
      ignore (if let __call_arg_0_24 = !r in isReserved __call_arg_0_24 then ignore (r := HxString.toStdString (!r) ^ "_") else ());
      !r
    )
  )
) : string)

let classVarName = fun (fullName : string) -> ("__hx_cls_" ^ HxString.toStdString (let __call_arg_0_25 = fullName in identifier __call_arg_0_25) : string)

let quoteString = fun (raw : string) -> (let tempString = ref (HxString.hx_null_string : string) in (
  ignore (if raw == HxString.hx_null_string then let __assign_26 = ("" : string) in (
    tempString := __assign_26;
    __assign_26
  ) else let __assign_27 = (raw : string) in (
    tempString := __assign_27;
    __assign_27
  ));
  let text = (!tempString : string) in let out = Obj.magic (StringBuf.create ()) in (
    ignore (StringBuf.add (Obj.magic out) (Obj.repr "\""));
    let _g = ref 0 in let _g1 = HxString.length text in (
      ignore (while !_g < _g1 do ignore (let i = let __old_28 = !_g in let __new_29 = HxInt.add __old_28 1 in (
        ignore (_g := __new_29);
        __old_28
      ) in let code = HxString.charCodeAt text i in if code == HxRuntime.hx_null then ignore (if (let __nullable_30 = code in let __nullable_31 = 32 in if __nullable_30 == HxRuntime.hx_null then false else Obj.obj __nullable_30 < __nullable_31) || (let __nullable_32 = code in let __nullable_33 = 126 in if __nullable_32 == HxRuntime.hx_null then false else Obj.obj __nullable_32 > __nullable_33) then ignore (StringBuf.add (Obj.magic out) (Obj.repr ("\\u" ^ HxString.toStdString (let __call_arg_0_34 = HxRuntime.nullable_int_unwrap code in let __call_arg_1_35 = Obj.repr 4 in StringTools.hex __call_arg_0_34 __call_arg_1_35)))) else ignore (StringBuf.addChar (Obj.magic out) (let __nullable_int_36 = code in if __nullable_int_36 == HxRuntime.hx_null then 0 else Obj.obj __nullable_int_36))) else ignore (let __switch_44 = code in if __switch_44 == HxRuntime.hx_null then ignore (if (let __nullable_37 = code in let __nullable_38 = 32 in if __nullable_37 == HxRuntime.hx_null then false else Obj.obj __nullable_37 < __nullable_38) || (let __nullable_39 = code in let __nullable_40 = 126 in if __nullable_39 == HxRuntime.hx_null then false else Obj.obj __nullable_39 > __nullable_40) then ignore (StringBuf.add (Obj.magic out) (Obj.repr ("\\u" ^ HxString.toStdString (let __call_arg_0_41 = HxRuntime.nullable_int_unwrap code in let __call_arg_1_42 = Obj.repr 4 in StringTools.hex __call_arg_0_41 __call_arg_1_42)))) else ignore (StringBuf.addChar (Obj.magic out) (let __nullable_int_43 = code in if __nullable_int_43 == HxRuntime.hx_null then 0 else Obj.obj __nullable_int_43))) else match Obj.obj __switch_44 with
        | 8 -> ignore (StringBuf.add (Obj.magic out) (Obj.repr "\\b"))
        | 9 -> ignore (StringBuf.add (Obj.magic out) (Obj.repr "\\t"))
        | 10 -> ignore (StringBuf.add (Obj.magic out) (Obj.repr "\\n"))
        | 12 -> ignore (StringBuf.add (Obj.magic out) (Obj.repr "\\f"))
        | 13 -> ignore (StringBuf.add (Obj.magic out) (Obj.repr "\\r"))
        | 34 -> ignore (StringBuf.add (Obj.magic out) (Obj.repr "\\\""))
        | 92 -> ignore (StringBuf.add (Obj.magic out) (Obj.repr "\\\\"))
        | _ -> ignore (if (let __nullable_37 = code in let __nullable_38 = 32 in if __nullable_37 == HxRuntime.hx_null then false else Obj.obj __nullable_37 < __nullable_38) || (let __nullable_39 = code in let __nullable_40 = 126 in if __nullable_39 == HxRuntime.hx_null then false else Obj.obj __nullable_39 > __nullable_40) then ignore (StringBuf.add (Obj.magic out) (Obj.repr ("\\u" ^ HxString.toStdString (let __call_arg_0_41 = HxRuntime.nullable_int_unwrap code in let __call_arg_1_42 = Obj.repr 4 in StringTools.hex __call_arg_0_41 __call_arg_1_42)))) else ignore (StringBuf.addChar (Obj.magic out) (let __nullable_int_43 = code in if __nullable_int_43 == HxRuntime.hx_null then 0 else Obj.obj __nullable_int_43))))) done);
      ignore (StringBuf.add (Obj.magic out) (Obj.repr "\""));
      StringBuf.toString (Obj.magic out) ()
    )
  )
) : string)

let propertySuffix = fun (name : string) -> (let id = let __call_arg_0_45 = name in identifier __call_arg_0_45 in let tempResult = ref (HxString.hx_null_string : string) in (
  ignore (if HxString.equals id name then let __assign_46 = "." ^ HxString.toStdString id in (
    tempResult := __assign_46;
    __assign_46
  ) else let __assign_47 = ("[" ^ HxString.toStdString (let __call_arg_0_48 = name in quoteString __call_arg_0_48)) ^ "]" in (
    tempResult := __assign_47;
    __assign_47
  ));
  !tempResult
) : string)