# 1 "backend_cpp_CppTargetCore.ml"
(* Generated by reflaxe.ocaml (WIP) *)
(* Haxe type: backend.cpp.CppTargetCore *)

let __reflaxe_ocaml__ = ()

type t = { __hx_type : Obj.t }

let create = fun () -> let self = ({ __hx_type = HxType.class_ "backend.cpp.CppTargetCore" } : t) in (
  ignore ();
  self
)

let __empty = fun () -> ({ __hx_type = HxType.class_ "backend.cpp.CppTargetCore" } : t)

let findMainModule = fun program context -> try let __fallback_result_23 = let tempString = ref ("" : string) in (
  ignore (if (Obj.magic context : Backend_BackendContext.t).mainModule == Obj.magic (HxRuntime.hx_null) then let __assign_10 = ("" : string) in (
    tempString := __assign_10;
    __assign_10
  ) else let __assign_11 = ((Obj.magic context : Backend_BackendContext.t).mainModule : string) in (
    tempString := __assign_11;
    __assign_11
  ));
  let fallback = ref (HxRuntime.hx_null : Obj.t) in let _g = ref 0 in let _g1 = Obj.magic (MacroExpandedProgram.getTypedModules (Obj.magic program) ()) in (
    ignore (while !_g < HxArray.length _g1 do ignore (let typed = Obj.magic (HxArray.get (Obj.magic _g1) (!_g)) in (
      ignore (let __old_12 = !_g in let __new_13 = HxInt.add __old_12 1 in (
        ignore (_g := __new_13);
        __new_13
      ));
      let decl = Obj.magic (ParsedModule.getDecl (Obj.magic (TypedModule.getParsed (Obj.magic typed) ())) ()) in let pkg = (HxModuleDecl.getPackagePath (Obj.magic decl) : string) in let _g2 = ref 0 in let _g3 = Obj.magic (HxModuleDecl.getClasses (Obj.magic decl)) in while !_g2 < HxArray.length _g3 do ignore (let cls = Obj.magic (HxArray.get (Obj.magic _g3) (!_g2)) in (
        ignore (let __old_14 = !_g2 in let __new_15 = HxInt.add __old_14 1 in (
          ignore (_g2 := __new_15);
          __new_15
        ));
        let clsName = (HxClassDecl.getName (Obj.magic cls) : string) in let tempString1 = ref ("" : string) in (
          ignore (if pkg == Obj.magic (HxRuntime.hx_null) || HxString.length pkg = 0 then let __assign_16 = (clsName : string) in (
            tempString1 := __assign_16;
            __assign_16
          ) else let __assign_17 = ((HxString.toStdString pkg ^ ".") ^ HxString.toStdString clsName : string) in (
            tempString1 := __assign_17;
            __assign_17
          ));
          let fullName = (!tempString1 : string) in let _g4 = ref 0 in let _g5 = Obj.magic (HxClassDecl.getFunctions (Obj.magic cls)) in while !_g4 < HxArray.length _g5 do ignore (let fn = Obj.magic (HxArray.get (Obj.magic _g5) (!_g4)) in (
            ignore (let __old_18 = !_g4 in let __new_19 = HxInt.add __old_18 1 in (
              ignore (_g4 := __new_19);
              __new_19
            ));
            if HxFunctionDecl.getIsStatic (Obj.magic fn) && HxString.equals (HxFunctionDecl.getName (Obj.magic fn)) "main" then ignore (let found = let __anon_20 = HxAnon.create () in (
              ignore (HxAnon.set __anon_20 "decl" (Obj.repr decl));
              ignore (HxAnon.set __anon_20 "cls" (Obj.repr cls));
              ignore (HxAnon.set __anon_20 "fn" (Obj.repr fn));
              __anon_20
            ) in (
              ignore (if Obj.magic (!fallback) == Obj.magic (HxRuntime.hx_null) then ignore (let __assign_21 = Obj.magic found in (
                fallback := __assign_21;
                __assign_21
              )) else ());
              if HxString.length (!tempString) = 0 || HxString.equals (!tempString) clsName || HxString.equals (!tempString) fullName then raise (HxRuntime.Hx_return (Obj.repr found)) else ()
            )) else ()
          )) done
        )
      )) done
    )) done);
    Obj.magic (!fallback)
  )
) in Obj.magic __fallback_result_23 with
  | HxRuntime.Hx_return __ret_22 -> Obj.magic __ret_22

let mainModule = fun program context -> let found = findMainModule (Obj.magic program) (Obj.magic context) in (
  ignore (if found == Obj.magic (HxRuntime.hx_null) then ignore (HxType.hx_throw_typed_rtti (Obj.repr "C++ source backend MVP requires a static main entrypoint") ["Dynamic"; "String"]) else ());
  found
)

let rec isStringLike = fun expr -> let tempResult = ref (false : bool) in (
  ignore (match expr with
    | HxExpr.EString _p0 -> (
      ignore _p0;
      let __assign_94 = true in (
        tempResult := __assign_94;
        __assign_94
      )
    )
    | HxExpr.ECall (_p0, _p1) -> let _g = Obj.magic _p0 in let _g1 = Obj.magic _p1 in if (match _g with
      | HxExpr.ENull -> 0
      | HxExpr.EBool _ -> 1
      | HxExpr.EString _ -> 2
      | HxExpr.EInt _ -> 3
      | HxExpr.EFloat _ -> 4
      | HxExpr.EEnumValue _ -> 5
      | HxExpr.EThis -> 6
      | HxExpr.ESuper -> 7
      | HxExpr.EIdent _ -> 8
      | HxExpr.EField (_, _) -> 9
      | HxExpr.ECall (_, _) -> 10
      | HxExpr.EMacroExpr (_, _) -> 11
      | HxExpr.EMacroType _ -> 12
      | HxExpr.ELambda (_, _) -> 13
      | HxExpr.ETryCatchRaw _ -> 14
      | HxExpr.ESwitchRaw _ -> 15
      | HxExpr.ESwitch (_, _, _) -> 16
      | HxExpr.ENew (_, _) -> 17
      | HxExpr.EUnop (_, _) -> 18
      | HxExpr.EBinop (_, _, _) -> 19
      | HxExpr.ETernary (_, _, _) -> 20
      | HxExpr.EAnon (_, _) -> 21
      | HxExpr.EArrayComprehension (_, _, _, _) -> 22
      | HxExpr.EArrayDecl _ -> 23
      | HxExpr.EArrayAccess (_, _) -> 24
      | HxExpr.ERange (_, _) -> 25
      | HxExpr.ECast (_, _) -> 26
      | HxExpr.EUntyped _ -> 27
      | HxExpr.EUnsupported _ -> 28) = 9 then let _g2 = Obj.magic (match _g with
      | HxExpr.EField (__enum_param_95, _) -> __enum_param_95
      | _ -> failwith "Unexpected enum parameter") in let _g3 = (match _g with
      | HxExpr.EField (_, __enum_param_96) -> __enum_param_96
      | _ -> failwith "Unexpected enum parameter" : string) in if (match _g2 with
      | HxExpr.ENull -> 0
      | HxExpr.EBool _ -> 1
      | HxExpr.EString _ -> 2
      | HxExpr.EInt _ -> 3
      | HxExpr.EFloat _ -> 4
      | HxExpr.EEnumValue _ -> 5
      | HxExpr.EThis -> 6
      | HxExpr.ESuper -> 7
      | HxExpr.EIdent _ -> 8
      | HxExpr.EField (_, _) -> 9
      | HxExpr.ECall (_, _) -> 10
      | HxExpr.EMacroExpr (_, _) -> 11
      | HxExpr.EMacroType _ -> 12
      | HxExpr.ELambda (_, _) -> 13
      | HxExpr.ETryCatchRaw _ -> 14
      | HxExpr.ESwitchRaw _ -> 15
      | HxExpr.ESwitch (_, _, _) -> 16
      | HxExpr.ENew (_, _) -> 17
      | HxExpr.EUnop (_, _) -> 18
      | HxExpr.EBinop (_, _, _) -> 19
      | HxExpr.ETernary (_, _, _) -> 20
      | HxExpr.EAnon (_, _) -> 21
      | HxExpr.EArrayComprehension (_, _, _, _) -> 22
      | HxExpr.EArrayDecl _ -> 23
      | HxExpr.EArrayAccess (_, _) -> 24
      | HxExpr.ERange (_, _) -> 25
      | HxExpr.ECast (_, _) -> 26
      | HxExpr.EUntyped _ -> 27
      | HxExpr.EUnsupported _ -> 28) = 8 then let _g4 = (match _g2 with
      | HxExpr.EIdent __enum_param_97 -> __enum_param_97
      | _ -> failwith "Unexpected enum parameter" : string) in if HxString.equals _g4 "Std" then if HxString.equals _g3 "string" then let args = Obj.magic _g1 in if HxArray.length args = 1 then let __assign_98 = true in (
      tempResult := __assign_98;
      __assign_98
    ) else let __assign_99 = false in (
      tempResult := __assign_99;
      __assign_99
    ) else let __assign_100 = false in (
      tempResult := __assign_100;
      __assign_100
    ) else let __assign_101 = false in (
      tempResult := __assign_101;
      __assign_101
    ) else let __assign_102 = false in (
      tempResult := __assign_102;
      __assign_102
    ) else let __assign_103 = false in (
      tempResult := __assign_103;
      __assign_103
    )
    | HxExpr.EBinop (_p0, _p1, _p2) -> let _g = (_p0 : string) in let _g1 = Obj.magic _p1 in let _g2 = Obj.magic _p2 in if HxString.equals _g "+" then let left = Obj.magic _g1 in let right = Obj.magic _g2 in let __assign_104 = isStringLike (Obj.magic left) || isStringLike (Obj.magic right) in (
      tempResult := __assign_104;
      __assign_104
    ) else let __assign_105 = false in (
      tempResult := __assign_105;
      __assign_105
    )
    | _ -> let __assign_93 = false in (
      tempResult := __assign_93;
      __assign_93
    ));
  !tempResult
)

let isSimpleBinaryOp = fun op -> HxString.equals op "+" || HxString.equals op "-" || HxString.equals op "*" || HxString.equals op "/" || HxString.equals op "==" || HxString.equals op "!=" || HxString.equals op "<" || HxString.equals op "<=" || HxString.equals op ">" || HxString.equals op ">="

let rec exprKind = fun expr -> let tempResult = ref ("" : string) in (
  ignore (match expr with
    | HxExpr.ENull -> let __assign_121 = ("ENull" : string) in (
      tempResult := __assign_121;
      __assign_121
    )
    | HxExpr.EBool _p0 -> (
      ignore _p0;
      let __assign_122 = ("EBool" : string) in (
        tempResult := __assign_122;
        __assign_122
      )
    )
    | HxExpr.EString _p0 -> (
      ignore _p0;
      let __assign_123 = ("EString" : string) in (
        tempResult := __assign_123;
        __assign_123
      )
    )
    | HxExpr.EInt _p0 -> (
      ignore _p0;
      let __assign_124 = ("EInt" : string) in (
        tempResult := __assign_124;
        __assign_124
      )
    )
    | HxExpr.EFloat _p0 -> (
      ignore _p0;
      let __assign_125 = ("EFloat" : string) in (
        tempResult := __assign_125;
        __assign_125
      )
    )
    | HxExpr.EEnumValue _p0 -> (
      ignore _p0;
      let __assign_126 = ("EEnumValue" : string) in (
        tempResult := __assign_126;
        __assign_126
      )
    )
    | HxExpr.EThis -> let __assign_127 = ("EThis" : string) in (
      tempResult := __assign_127;
      __assign_127
    )
    | HxExpr.ESuper -> let __assign_128 = ("ESuper" : string) in (
      tempResult := __assign_128;
      __assign_128
    )
    | HxExpr.EIdent _p0 -> let _g = (_p0 : string) in let name = (_g : string) in let __assign_129 = (("EIdent(" ^ HxString.toStdString name) ^ ")" : string) in (
      tempResult := __assign_129;
      __assign_129
    )
    | HxExpr.EField (_p0, _p1) -> (
      ignore _p0;
      let _g2 = (_p1 : string) in let field = (_g2 : string) in let __assign_130 = (("EField(" ^ HxString.toStdString field) ^ ")" : string) in (
        tempResult := __assign_130;
        __assign_130
      )
    )
    | HxExpr.ECall (_p0, _p1) -> let _g = Obj.magic _p0 in (
      ignore _p1;
      let callee = Obj.magic _g in let __assign_131 = (("ECall(" ^ HxString.toStdString (exprKind (Obj.magic callee))) ^ ")" : string) in (
        tempResult := __assign_131;
        __assign_131
      )
    )
    | HxExpr.EMacroExpr (_p0, _p1) -> (
      ignore _p0;
      ignore _p1;
      let __assign_132 = ("EMacroExpr" : string) in (
        tempResult := __assign_132;
        __assign_132
      )
    )
    | HxExpr.EMacroType _p0 -> (
      ignore _p0;
      let __assign_133 = ("EMacroType" : string) in (
        tempResult := __assign_133;
        __assign_133
      )
    )
    | HxExpr.ELambda (_p0, _p1) -> (
      ignore _p0;
      ignore _p1;
      let __assign_134 = ("ELambda" : string) in (
        tempResult := __assign_134;
        __assign_134
      )
    )
    | HxExpr.ETryCatchRaw _p0 -> (
      ignore _p0;
      let __assign_135 = ("ETryCatchRaw" : string) in (
        tempResult := __assign_135;
        __assign_135
      )
    )
    | HxExpr.ESwitchRaw _p0 -> (
      ignore _p0;
      let __assign_136 = ("ESwitchRaw" : string) in (
        tempResult := __assign_136;
        __assign_136
      )
    )
    | HxExpr.ESwitch (_p0, _p1, _p2) -> (
      ignore _p0;
      ignore _p1;
      ignore _p2;
      let __assign_137 = ("ESwitch" : string) in (
        tempResult := __assign_137;
        __assign_137
      )
    )
    | HxExpr.ENew (_p0, _p1) -> let _g = (_p0 : string) in (
      ignore _p1;
      let typePath = (_g : string) in let __assign_138 = (("ENew(" ^ HxString.toStdString typePath) ^ ")" : string) in (
        tempResult := __assign_138;
        __assign_138
      )
    )
    | HxExpr.EUnop (_p0, _p1) -> let _g = (_p0 : string) in (
      ignore _p1;
      let op = (_g : string) in let __assign_139 = (("EUnop(" ^ HxString.toStdString op) ^ ")" : string) in (
        tempResult := __assign_139;
        __assign_139
      )
    )
    | HxExpr.EBinop (_p0, _p1, _p2) -> let _g = (_p0 : string) in (
      ignore _p1;
      ignore _p2;
      let op = (_g : string) in let __assign_140 = (("EBinop(" ^ HxString.toStdString op) ^ ")" : string) in (
        tempResult := __assign_140;
        __assign_140
      )
    )
    | HxExpr.ETernary (_p0, _p1, _p2) -> (
      ignore _p0;
      ignore _p1;
      ignore _p2;
      let __assign_141 = ("ETernary" : string) in (
        tempResult := __assign_141;
        __assign_141
      )
    )
    | HxExpr.EAnon (_p0, _p1) -> (
      ignore _p0;
      ignore _p1;
      let __assign_142 = ("EAnon" : string) in (
        tempResult := __assign_142;
        __assign_142
      )
    )
    | HxExpr.EArrayComprehension (_p0, _p1, _p2, _p3) -> (
      ignore _p0;
      ignore _p1;
      ignore _p2;
      ignore _p3;
      let __assign_143 = ("EArrayComprehension" : string) in (
        tempResult := __assign_143;
        __assign_143
      )
    )
    | HxExpr.EArrayDecl _p0 -> (
      ignore _p0;
      let __assign_144 = ("EArrayDecl" : string) in (
        tempResult := __assign_144;
        __assign_144
      )
    )
    | HxExpr.EArrayAccess (_p0, _p1) -> (
      ignore _p0;
      ignore _p1;
      let __assign_145 = ("EArrayAccess" : string) in (
        tempResult := __assign_145;
        __assign_145
      )
    )
    | HxExpr.ERange (_p0, _p1) -> (
      ignore _p0;
      ignore _p1;
      let __assign_146 = ("ERange" : string) in (
        tempResult := __assign_146;
        __assign_146
      )
    )
    | HxExpr.ECast (_p0, _p1) -> (
      ignore _p0;
      ignore _p1;
      let __assign_147 = ("ECast" : string) in (
        tempResult := __assign_147;
        __assign_147
      )
    )
    | HxExpr.EUntyped _p0 -> (
      ignore _p0;
      let __assign_148 = ("EUntyped" : string) in (
        tempResult := __assign_148;
        __assign_148
      )
    )
    | HxExpr.EUnsupported _p0 -> let _g = (_p0 : string) in let reason = (_g : string) in let __assign_149 = (("EUnsupported(" ^ HxString.toStdString reason) ^ ")" : string) in (
      tempResult := __assign_149;
      __assign_149
    ));
  !tempResult
)

let stmtKind = fun stmt -> let tempResult = ref ("" : string) in (
  ignore (match stmt with
    | HxStmt.SBlock (_p0, _p1) -> (
      ignore _p0;
      ignore _p1;
      let __assign_106 = ("SBlock" : string) in (
        tempResult := __assign_106;
        __assign_106
      )
    )
    | HxStmt.SVar (_p0, _p1, _p2, _p3) -> (
      ignore _p0;
      ignore _p1;
      ignore _p2;
      ignore _p3;
      let __assign_107 = ("SVar" : string) in (
        tempResult := __assign_107;
        __assign_107
      )
    )
    | HxStmt.SIf (_p0, _p1, _p2, _p3) -> (
      ignore _p0;
      ignore _p1;
      ignore _p2;
      ignore _p3;
      let __assign_108 = ("SIf" : string) in (
        tempResult := __assign_108;
        __assign_108
      )
    )
    | HxStmt.SForIn (_p0, _p1, _p2, _p3) -> (
      ignore _p0;
      ignore _p1;
      ignore _p2;
      ignore _p3;
      let __assign_109 = ("SForIn" : string) in (
        tempResult := __assign_109;
        __assign_109
      )
    )
    | HxStmt.SForKeyValue (_p0, _p1, _p2, _p3, _p4) -> (
      ignore _p0;
      ignore _p1;
      ignore _p2;
      ignore _p3;
      ignore _p4;
      let __assign_110 = ("SForKeyValue" : string) in (
        tempResult := __assign_110;
        __assign_110
      )
    )
    | HxStmt.SWhile (_p0, _p1, _p2) -> (
      ignore _p0;
      ignore _p1;
      ignore _p2;
      let __assign_111 = ("SWhile" : string) in (
        tempResult := __assign_111;
        __assign_111
      )
    )
    | HxStmt.SDoWhile (_p0, _p1, _p2) -> (
      ignore _p0;
      ignore _p1;
      ignore _p2;
      let __assign_112 = ("SDoWhile" : string) in (
        tempResult := __assign_112;
        __assign_112
      )
    )
    | HxStmt.SSwitch (_p0, _p1, _p2, _p3) -> (
      ignore _p0;
      ignore _p1;
      ignore _p2;
      ignore _p3;
      let __assign_113 = ("SSwitch" : string) in (
        tempResult := __assign_113;
        __assign_113
      )
    )
    | HxStmt.STry (_p0, _p1, _p2) -> (
      ignore _p0;
      ignore _p1;
      ignore _p2;
      let __assign_114 = ("STry" : string) in (
        tempResult := __assign_114;
        __assign_114
      )
    )
    | HxStmt.SBreak _p0 -> (
      ignore _p0;
      let __assign_115 = ("SBreak" : string) in (
        tempResult := __assign_115;
        __assign_115
      )
    )
    | HxStmt.SContinue _p0 -> (
      ignore _p0;
      let __assign_116 = ("SContinue" : string) in (
        tempResult := __assign_116;
        __assign_116
      )
    )
    | HxStmt.SThrow (_p0, _p1) -> (
      ignore _p0;
      ignore _p1;
      let __assign_117 = ("SThrow" : string) in (
        tempResult := __assign_117;
        __assign_117
      )
    )
    | HxStmt.SReturnVoid _p0 -> (
      ignore _p0;
      let __assign_118 = ("SReturnVoid" : string) in (
        tempResult := __assign_118;
        __assign_118
      )
    )
    | HxStmt.SReturn (_p0, _p1) -> (
      ignore _p0;
      ignore _p1;
      let __assign_119 = ("SReturn" : string) in (
        tempResult := __assign_119;
        __assign_119
      )
    )
    | HxStmt.SExpr (_p0, _p1) -> let _g = Obj.magic _p0 in (
      ignore _p1;
      let expr = Obj.magic _g in let __assign_120 = (("SExpr(" ^ HxString.toStdString (exprKind (Obj.magic expr))) ^ ")" : string) in (
        tempResult := __assign_120;
        __assign_120
      )
    ));
  !tempResult
)

let quoteString = fun value -> let out = ref ("\"" : string) in let _g = ref 0 in let _g1 = HxString.length value in (
  ignore (while !_g < _g1 do ignore (let i = let __old_150 = !_g in let __new_151 = HxInt.add __old_150 1 in (
    ignore (_g := __new_151);
    __old_150
  ) in let code = HxString.charCodeAt value i in let tempRight = ref ("" : string) in (
    ignore (if code == HxRuntime.hx_null then let __assign_152 = (HxString.fromCharCode (let __nullable_int_153 = code in if __nullable_int_153 == HxRuntime.hx_null then 0 else Obj.obj __nullable_int_153) : string) in (
      tempRight := __assign_152;
      __assign_152
    ) else let __switch_161 = code in if __switch_161 == HxRuntime.hx_null then let __assign_154 = (HxString.fromCharCode (let __nullable_int_155 = code in if __nullable_int_155 == HxRuntime.hx_null then 0 else Obj.obj __nullable_int_155) : string) in (
      tempRight := __assign_154;
      __assign_154
    ) else match Obj.obj __switch_161 with
      | 9 -> let __assign_162 = ("\\t" : string) in (
        tempRight := __assign_162;
        __assign_162
      )
      | 10 -> let __assign_163 = ("\\n" : string) in (
        tempRight := __assign_163;
        __assign_163
      )
      | 13 -> let __assign_164 = ("\\r" : string) in (
        tempRight := __assign_164;
        __assign_164
      )
      | 34 -> let __assign_165 = ("\\\"" : string) in (
        tempRight := __assign_165;
        __assign_165
      )
      | 92 -> let __assign_166 = ("\\\\" : string) in (
        tempRight := __assign_166;
        __assign_166
      )
      | _ -> let __assign_154 = (HxString.fromCharCode (let __nullable_int_155 = code in if __nullable_int_155 == HxRuntime.hx_null then 0 else Obj.obj __nullable_int_155) : string) in (
        tempRight := __assign_154;
        __assign_154
      ));
    out := HxString.toStdString (!out) ^ HxString.toStdString (!tempRight)
  )) done);
  HxString.toStdString (!out) ^ "\""
)

let sanitizeIdentifier = fun name -> try let __fallback_result_174 = (
  ignore (if name == Obj.magic (HxRuntime.hx_null) || HxString.length name = 0 then raise (HxRuntime.Hx_return (Obj.repr ("_" : string))) else ());
  let out = Obj.magic (StringBuf.create ()) in let _g = ref 0 in let _g1 = HxString.length name in (
    ignore (while !_g < _g1 do ignore (let i = let __old_167 = !_g in let __new_168 = HxInt.add __old_167 1 in (
      ignore (_g := __new_168);
      __old_167
    ) in let c = (HxString.charAt name i : string) in let ok = c >= "a" && c <= "z" || c >= "A" && c <= "Z" || HxString.equals c "_" || i > 0 && c >= "0" && c <= "9" in let tempString = ref ("" : string) in (
      ignore (if ok then let __assign_169 = (c : string) in (
        tempString := __assign_169;
        __assign_169
      ) else let __assign_170 = ("_" : string) in (
        tempString := __assign_170;
        __assign_170
      ));
      StringBuf.add (Obj.magic out) (Obj.repr (!tempString))
    )) done);
    let s = (StringBuf.toString (Obj.magic out) () : string) in let first = (HxString.charAt s 0 : string) in (
      ignore (if first >= "0" && first <= "9" then raise (HxRuntime.Hx_return (Obj.repr ("_" ^ HxString.toStdString s : string))) else ());
      let tempResult = ref ("" : string) in (
        ignore (match s with
          | "auto" | "bool" | "break" | "case" | "catch" | "class" | "const" | "continue" | "delete" | "do" | "double" | "else" | "false" | "float" | "for" | "if" | "int" | "long" | "namespace" | "new" | "nullptr" | "private" | "public" | "return" | "short" | "static" | "std" | "struct" | "switch" | "this" | "throw" | "true" | "try" | "void" | "while" -> let __assign_172 = (HxString.toStdString s ^ "_" : string) in (
            tempResult := __assign_172;
            __assign_172
          )
          | _ -> let __assign_171 = (s : string) in (
            tempResult := __assign_171;
            __assign_171
          ));
        !tempResult
      )
    )
  )
) in Obj.magic __fallback_result_174 with
  | HxRuntime.Hx_return __ret_173 -> Obj.obj __ret_173

let rec renderExpr = fun expr -> let tempResult = ref ("" : string) in (
  ignore (match expr with
    | HxExpr.ENull -> let __assign_61 = ("nullptr" : string) in (
      tempResult := __assign_61;
      __assign_61
    )
    | HxExpr.EBool _p0 -> let _g = _p0 in let value = _g in if value then let __assign_62 = ("true" : string) in (
      tempResult := __assign_62;
      __assign_62
    ) else let __assign_63 = ("false" : string) in (
      tempResult := __assign_63;
      __assign_63
    )
    | HxExpr.EString _p0 -> let _g = (_p0 : string) in let value = (_g : string) in let __assign_64 = (quoteString (value : string) : string) in (
      tempResult := __assign_64;
      __assign_64
    )
    | HxExpr.EInt _p0 -> let _g = _p0 in let value = _g in let __assign_65 = (string_of_int value : string) in (
      tempResult := __assign_65;
      __assign_65
    )
    | HxExpr.EFloat _p0 -> let _g = _p0 in let value = _g in let __assign_66 = (string_of_float value : string) in (
      tempResult := __assign_66;
      __assign_66
    )
    | HxExpr.EIdent _p0 -> let _g = (_p0 : string) in let name = (_g : string) in let __assign_67 = (sanitizeIdentifier (name : string) : string) in (
      tempResult := __assign_67;
      __assign_67
    )
    | HxExpr.ECall (_p0, _p1) -> let _g = Obj.magic _p0 in let _g1 = Obj.magic _p1 in if (match _g with
      | HxExpr.ENull -> 0
      | HxExpr.EBool _ -> 1
      | HxExpr.EString _ -> 2
      | HxExpr.EInt _ -> 3
      | HxExpr.EFloat _ -> 4
      | HxExpr.EEnumValue _ -> 5
      | HxExpr.EThis -> 6
      | HxExpr.ESuper -> 7
      | HxExpr.EIdent _ -> 8
      | HxExpr.EField (_, _) -> 9
      | HxExpr.ECall (_, _) -> 10
      | HxExpr.EMacroExpr (_, _) -> 11
      | HxExpr.EMacroType _ -> 12
      | HxExpr.ELambda (_, _) -> 13
      | HxExpr.ETryCatchRaw _ -> 14
      | HxExpr.ESwitchRaw _ -> 15
      | HxExpr.ESwitch (_, _, _) -> 16
      | HxExpr.ENew (_, _) -> 17
      | HxExpr.EUnop (_, _) -> 18
      | HxExpr.EBinop (_, _, _) -> 19
      | HxExpr.ETernary (_, _, _) -> 20
      | HxExpr.EAnon (_, _) -> 21
      | HxExpr.EArrayComprehension (_, _, _, _) -> 22
      | HxExpr.EArrayDecl _ -> 23
      | HxExpr.EArrayAccess (_, _) -> 24
      | HxExpr.ERange (_, _) -> 25
      | HxExpr.ECast (_, _) -> 26
      | HxExpr.EUntyped _ -> 27
      | HxExpr.EUnsupported _ -> 28) = 9 then let _g2 = Obj.magic (match _g with
      | HxExpr.EField (__enum_param_68, _) -> __enum_param_68
      | _ -> failwith "Unexpected enum parameter") in let _g3 = (match _g with
      | HxExpr.EField (_, __enum_param_69) -> __enum_param_69
      | _ -> failwith "Unexpected enum parameter" : string) in if (match _g2 with
      | HxExpr.ENull -> 0
      | HxExpr.EBool _ -> 1
      | HxExpr.EString _ -> 2
      | HxExpr.EInt _ -> 3
      | HxExpr.EFloat _ -> 4
      | HxExpr.EEnumValue _ -> 5
      | HxExpr.EThis -> 6
      | HxExpr.ESuper -> 7
      | HxExpr.EIdent _ -> 8
      | HxExpr.EField (_, _) -> 9
      | HxExpr.ECall (_, _) -> 10
      | HxExpr.EMacroExpr (_, _) -> 11
      | HxExpr.EMacroType _ -> 12
      | HxExpr.ELambda (_, _) -> 13
      | HxExpr.ETryCatchRaw _ -> 14
      | HxExpr.ESwitchRaw _ -> 15
      | HxExpr.ESwitch (_, _, _) -> 16
      | HxExpr.ENew (_, _) -> 17
      | HxExpr.EUnop (_, _) -> 18
      | HxExpr.EBinop (_, _, _) -> 19
      | HxExpr.ETernary (_, _, _) -> 20
      | HxExpr.EAnon (_, _) -> 21
      | HxExpr.EArrayComprehension (_, _, _, _) -> 22
      | HxExpr.EArrayDecl _ -> 23
      | HxExpr.EArrayAccess (_, _) -> 24
      | HxExpr.ERange (_, _) -> 25
      | HxExpr.ECast (_, _) -> 26
      | HxExpr.EUntyped _ -> 27
      | HxExpr.EUnsupported _ -> 28) = 8 then let _g4 = (match _g2 with
      | HxExpr.EIdent __enum_param_70 -> __enum_param_70
      | _ -> failwith "Unexpected enum parameter" : string) in if HxString.equals _g4 "Std" then if HxString.equals _g3 "string" then let args = Obj.magic _g1 in if HxArray.length args = 1 then let __assign_71 = (stringExpr (Obj.magic (HxArray.get (Obj.magic args) 0)) : string) in (
      tempResult := __assign_71;
      __assign_71
    ) else HxType.hx_throw_typed_rtti (Obj.repr ("C++ source backend MVP unsupported expression: " ^ HxString.toStdString (exprKind (Obj.magic expr)))) ["Dynamic"; "String"] else HxType.hx_throw_typed_rtti (Obj.repr ("C++ source backend MVP unsupported expression: " ^ HxString.toStdString (exprKind (Obj.magic expr)))) ["Dynamic"; "String"] else HxType.hx_throw_typed_rtti (Obj.repr ("C++ source backend MVP unsupported expression: " ^ HxString.toStdString (exprKind (Obj.magic expr)))) ["Dynamic"; "String"] else HxType.hx_throw_typed_rtti (Obj.repr ("C++ source backend MVP unsupported expression: " ^ HxString.toStdString (exprKind (Obj.magic expr)))) ["Dynamic"; "String"] else HxType.hx_throw_typed_rtti (Obj.repr ("C++ source backend MVP unsupported expression: " ^ HxString.toStdString (exprKind (Obj.magic expr)))) ["Dynamic"; "String"]
    | HxExpr.EBinop (_p0, _p1, _p2) -> let _g = (_p0 : string) in let _g1 = Obj.magic _p1 in let _g2 = Obj.magic _p2 in if HxString.equals _g "+" then let left = Obj.magic _g1 in let right = Obj.magic _g2 in if isStringLike (Obj.magic left) || isStringLike (Obj.magic right) then let __assign_72 = (((("(" ^ HxString.toStdString (stringExpr (Obj.magic left))) ^ " + ") ^ HxString.toStdString (stringExpr (Obj.magic right))) ^ ")" : string) in (
      tempResult := __assign_72;
      __assign_72
    ) else let op = (_g : string) in let left2 = Obj.magic _g1 in let right2 = Obj.magic _g2 in if isSimpleBinaryOp (op : string) then let __assign_73 = (((((("(" ^ HxString.toStdString (renderExpr (Obj.magic left2))) ^ " ") ^ HxString.toStdString op) ^ " ") ^ HxString.toStdString (renderExpr (Obj.magic right2))) ^ ")" : string) in (
      tempResult := __assign_73;
      __assign_73
    ) else HxType.hx_throw_typed_rtti (Obj.repr ("C++ source backend MVP unsupported expression: " ^ HxString.toStdString (exprKind (Obj.magic expr)))) ["Dynamic"; "String"] else let op = (_g : string) in let left = Obj.magic _g1 in let right = Obj.magic _g2 in if isSimpleBinaryOp (op : string) then let __assign_74 = (((((("(" ^ HxString.toStdString (renderExpr (Obj.magic left))) ^ " ") ^ HxString.toStdString op) ^ " ") ^ HxString.toStdString (renderExpr (Obj.magic right))) ^ ")" : string) in (
      tempResult := __assign_74;
      __assign_74
    ) else HxType.hx_throw_typed_rtti (Obj.repr ("C++ source backend MVP unsupported expression: " ^ HxString.toStdString (exprKind (Obj.magic expr)))) ["Dynamic"; "String"]
    | HxExpr.EUntyped _p0 -> let _g = Obj.magic _p0 in let inner = Obj.magic _g in let __assign_75 = (renderExpr (Obj.magic inner) : string) in (
      tempResult := __assign_75;
      __assign_75
    )
    | _ -> HxType.hx_throw_typed_rtti (Obj.repr ("C++ source backend MVP unsupported expression: " ^ HxString.toStdString (exprKind (Obj.magic expr)))) ["Dynamic"; "String"]);
  !tempResult
)
and stringExpr = fun expr -> let tempResult = ref ("" : string) in (
  ignore (match expr with
    | HxExpr.EBool _p0 -> (
      ignore _p0;
      let __assign_77 = (("std::string(" ^ HxString.toStdString (renderExpr (Obj.magic expr))) ^ " ? \"true\" : \"false\")" : string) in (
        tempResult := __assign_77;
        __assign_77
      )
    )
    | HxExpr.EString _p0 -> let _g = (_p0 : string) in let value = (_g : string) in let __assign_78 = (("std::string(" ^ HxString.toStdString (quoteString (value : string))) ^ ")" : string) in (
      tempResult := __assign_78;
      __assign_78
    )
    | HxExpr.EInt _p0 -> (
      ignore _p0;
      let __assign_79 = (("std::to_string(" ^ HxString.toStdString (renderExpr (Obj.magic expr))) ^ ")" : string) in (
        tempResult := __assign_79;
        __assign_79
      )
    )
    | HxExpr.EFloat _p0 -> (
      ignore _p0;
      let __assign_80 = (("std::to_string(" ^ HxString.toStdString (renderExpr (Obj.magic expr))) ^ ")" : string) in (
        tempResult := __assign_80;
        __assign_80
      )
    )
    | HxExpr.EIdent _p0 -> let _g = (_p0 : string) in let name = (_g : string) in let __assign_81 = (("std::string(" ^ HxString.toStdString (sanitizeIdentifier (name : string))) ^ ")" : string) in (
      tempResult := __assign_81;
      __assign_81
    )
    | HxExpr.ECall (_p0, _p1) -> let _g = Obj.magic _p0 in let _g1 = Obj.magic _p1 in if (match _g with
      | HxExpr.ENull -> 0
      | HxExpr.EBool _ -> 1
      | HxExpr.EString _ -> 2
      | HxExpr.EInt _ -> 3
      | HxExpr.EFloat _ -> 4
      | HxExpr.EEnumValue _ -> 5
      | HxExpr.EThis -> 6
      | HxExpr.ESuper -> 7
      | HxExpr.EIdent _ -> 8
      | HxExpr.EField (_, _) -> 9
      | HxExpr.ECall (_, _) -> 10
      | HxExpr.EMacroExpr (_, _) -> 11
      | HxExpr.EMacroType _ -> 12
      | HxExpr.ELambda (_, _) -> 13
      | HxExpr.ETryCatchRaw _ -> 14
      | HxExpr.ESwitchRaw _ -> 15
      | HxExpr.ESwitch (_, _, _) -> 16
      | HxExpr.ENew (_, _) -> 17
      | HxExpr.EUnop (_, _) -> 18
      | HxExpr.EBinop (_, _, _) -> 19
      | HxExpr.ETernary (_, _, _) -> 20
      | HxExpr.EAnon (_, _) -> 21
      | HxExpr.EArrayComprehension (_, _, _, _) -> 22
      | HxExpr.EArrayDecl _ -> 23
      | HxExpr.EArrayAccess (_, _) -> 24
      | HxExpr.ERange (_, _) -> 25
      | HxExpr.ECast (_, _) -> 26
      | HxExpr.EUntyped _ -> 27
      | HxExpr.EUnsupported _ -> 28) = 9 then let _g2 = Obj.magic (match _g with
      | HxExpr.EField (__enum_param_82, _) -> __enum_param_82
      | _ -> failwith "Unexpected enum parameter") in let _g3 = (match _g with
      | HxExpr.EField (_, __enum_param_83) -> __enum_param_83
      | _ -> failwith "Unexpected enum parameter" : string) in if (match _g2 with
      | HxExpr.ENull -> 0
      | HxExpr.EBool _ -> 1
      | HxExpr.EString _ -> 2
      | HxExpr.EInt _ -> 3
      | HxExpr.EFloat _ -> 4
      | HxExpr.EEnumValue _ -> 5
      | HxExpr.EThis -> 6
      | HxExpr.ESuper -> 7
      | HxExpr.EIdent _ -> 8
      | HxExpr.EField (_, _) -> 9
      | HxExpr.ECall (_, _) -> 10
      | HxExpr.EMacroExpr (_, _) -> 11
      | HxExpr.EMacroType _ -> 12
      | HxExpr.ELambda (_, _) -> 13
      | HxExpr.ETryCatchRaw _ -> 14
      | HxExpr.ESwitchRaw _ -> 15
      | HxExpr.ESwitch (_, _, _) -> 16
      | HxExpr.ENew (_, _) -> 17
      | HxExpr.EUnop (_, _) -> 18
      | HxExpr.EBinop (_, _, _) -> 19
      | HxExpr.ETernary (_, _, _) -> 20
      | HxExpr.EAnon (_, _) -> 21
      | HxExpr.EArrayComprehension (_, _, _, _) -> 22
      | HxExpr.EArrayDecl _ -> 23
      | HxExpr.EArrayAccess (_, _) -> 24
      | HxExpr.ERange (_, _) -> 25
      | HxExpr.ECast (_, _) -> 26
      | HxExpr.EUntyped _ -> 27
      | HxExpr.EUnsupported _ -> 28) = 8 then let _g4 = (match _g2 with
      | HxExpr.EIdent __enum_param_84 -> __enum_param_84
      | _ -> failwith "Unexpected enum parameter" : string) in if HxString.equals _g4 "Std" then if HxString.equals _g3 "string" then let args = Obj.magic _g1 in if HxArray.length args = 1 then let __assign_85 = (stringExpr (Obj.magic (HxArray.get (Obj.magic args) 0)) : string) in (
      tempResult := __assign_85;
      __assign_85
    ) else let __assign_86 = (("std::to_string(" ^ HxString.toStdString (renderExpr (Obj.magic expr))) ^ ")" : string) in (
      tempResult := __assign_86;
      __assign_86
    ) else let __assign_87 = (("std::to_string(" ^ HxString.toStdString (renderExpr (Obj.magic expr))) ^ ")" : string) in (
      tempResult := __assign_87;
      __assign_87
    ) else let __assign_88 = (("std::to_string(" ^ HxString.toStdString (renderExpr (Obj.magic expr))) ^ ")" : string) in (
      tempResult := __assign_88;
      __assign_88
    ) else let __assign_89 = (("std::to_string(" ^ HxString.toStdString (renderExpr (Obj.magic expr))) ^ ")" : string) in (
      tempResult := __assign_89;
      __assign_89
    ) else let __assign_90 = (("std::to_string(" ^ HxString.toStdString (renderExpr (Obj.magic expr))) ^ ")" : string) in (
      tempResult := __assign_90;
      __assign_90
    )
    | HxExpr.EBinop (_p0, _p1, _p2) -> let _g = (_p0 : string) in let _g1 = Obj.magic _p1 in let _g2 = Obj.magic _p2 in if HxString.equals _g "+" then let left = Obj.magic _g1 in let right = Obj.magic _g2 in let __assign_91 = (((("(" ^ HxString.toStdString (stringExpr (Obj.magic left))) ^ " + ") ^ HxString.toStdString (stringExpr (Obj.magic right))) ^ ")" : string) in (
      tempResult := __assign_91;
      __assign_91
    ) else let __assign_92 = (("std::to_string(" ^ HxString.toStdString (renderExpr (Obj.magic expr))) ^ ")" : string) in (
      tempResult := __assign_92;
      __assign_92
    )
    | _ -> let __assign_76 = (("std::to_string(" ^ HxString.toStdString (renderExpr (Obj.magic expr))) ^ ")" : string) in (
      tempResult := __assign_76;
      __assign_76
    ));
  !tempResult
)

let rec renderStmts = fun stmts indent -> let out = Obj.magic (HxArray.create ()) in let _g = ref 0 in (
  ignore (while !_g < HxArray.length stmts do ignore (let stmt = Obj.magic (HxArray.get (Obj.magic stmts) (!_g)) in (
    ignore (let __old_26 = !_g in let __new_27 = HxInt.add __old_26 1 in (
      ignore (_g := __new_27);
      __new_27
    ));
    let _g2 = ref 0 in let _g1 = Obj.magic (renderStmt (Obj.magic stmt) (indent : string)) in while !_g2 < HxArray.length _g1 do ignore (let line = (HxArray.get (Obj.magic _g1) (!_g2) : string) in (
      ignore (let __old_28 = !_g2 in let __new_29 = HxInt.add __old_28 1 in (
        ignore (_g2 := __new_29);
        __new_29
      ));
      HxArray.push out line
    )) done
  )) done);
  out
)
and renderStmt = fun stmt indent -> let tempResult = ref (Obj.magic (HxRuntime.hx_null) : string HxArray.t) in (
  ignore (match stmt with
    | HxStmt.SBlock (_p0, _p1) -> let _g = Obj.magic _p0 in (
      ignore _p1;
      let stmts = Obj.magic _g in let out = Obj.magic (let __arr_30 = HxArray.create () in (
        ignore (HxArray.push __arr_30 (HxString.toStdString indent ^ "{"));
        __arr_30
      )) in (
        ignore (let _g2 = ref 0 in let _g3 = Obj.magic (renderStmts (Obj.magic stmts) (HxString.toStdString indent ^ "  " : string)) in while !_g2 < HxArray.length _g3 do ignore (let line = (HxArray.get (Obj.magic _g3) (!_g2) : string) in (
          ignore (let __old_31 = !_g2 in let __new_32 = HxInt.add __old_31 1 in (
            ignore (_g2 := __new_32);
            __new_32
          ));
          HxArray.push out line
        )) done);
        ignore (HxArray.push out (HxString.toStdString indent ^ "}"));
        let __assign_33 = Obj.magic out in (
          tempResult := __assign_33;
          __assign_33
        )
      )
    )
    | HxStmt.SVar (_p0, _p1, _p2, _p3) -> let _g = (_p0 : string) in let _g1 = (_p1 : string) in let _g2 = Obj.obj (HxEnum.unbox_or_obj "HxExpr" _p2) in (
      ignore _p3;
      let name = (_g : string) in (
        ignore _g1;
        let init = Obj.obj (HxEnum.unbox_or_obj "HxExpr" _g2) in let tempString = ref ("" : string) in (
          ignore (if init == Obj.magic (HxRuntime.hx_null) then let __assign_34 = ("0" : string) in (
            tempString := __assign_34;
            __assign_34
          ) else let __assign_35 = (renderExpr (Obj.obj (HxEnum.unbox_or_obj "HxExpr" init)) : string) in (
            tempString := __assign_35;
            __assign_35
          ));
          let rhs = (!tempString : string) in let __assign_36 = Obj.magic (let __arr_37 = HxArray.create () in (
            ignore (HxArray.push __arr_37 (((((HxString.toStdString indent ^ "auto ") ^ HxString.toStdString (sanitizeIdentifier (name : string))) ^ " = ") ^ HxString.toStdString rhs) ^ ";"));
            __arr_37
          )) in (
            tempResult := __assign_36;
            __assign_36
          )
        )
      )
    )
    | HxStmt.SReturnVoid _p0 -> (
      ignore _p0;
      let __assign_38 = Obj.magic (let __arr_39 = HxArray.create () in (
        ignore (HxArray.push __arr_39 (HxString.toStdString indent ^ "return 0;"));
        __arr_39
      )) in (
        tempResult := __assign_38;
        __assign_38
      )
    )
    | HxStmt.SReturn (_p0, _p1) -> let _g = Obj.magic _p0 in (
      ignore _p1;
      let expr = Obj.magic _g in let __assign_40 = Obj.magic (let __arr_41 = HxArray.create () in (
        ignore (HxArray.push __arr_41 (((HxString.toStdString indent ^ "return static_cast<int>(") ^ HxString.toStdString (renderExpr (Obj.magic expr))) ^ ");"));
        __arr_41
      )) in (
        tempResult := __assign_40;
        __assign_40
      )
    )
    | HxStmt.SExpr (_p0, _p1) -> let _g = Obj.magic _p0 in (
      ignore _p1;
      if (match _g with
        | HxExpr.ENull -> 0
        | HxExpr.EBool _ -> 1
        | HxExpr.EString _ -> 2
        | HxExpr.EInt _ -> 3
        | HxExpr.EFloat _ -> 4
        | HxExpr.EEnumValue _ -> 5
        | HxExpr.EThis -> 6
        | HxExpr.ESuper -> 7
        | HxExpr.EIdent _ -> 8
        | HxExpr.EField (_, _) -> 9
        | HxExpr.ECall (_, _) -> 10
        | HxExpr.EMacroExpr (_, _) -> 11
        | HxExpr.EMacroType _ -> 12
        | HxExpr.ELambda (_, _) -> 13
        | HxExpr.ETryCatchRaw _ -> 14
        | HxExpr.ESwitchRaw _ -> 15
        | HxExpr.ESwitch (_, _, _) -> 16
        | HxExpr.ENew (_, _) -> 17
        | HxExpr.EUnop (_, _) -> 18
        | HxExpr.EBinop (_, _, _) -> 19
        | HxExpr.ETernary (_, _, _) -> 20
        | HxExpr.EAnon (_, _) -> 21
        | HxExpr.EArrayComprehension (_, _, _, _) -> 22
        | HxExpr.EArrayDecl _ -> 23
        | HxExpr.EArrayAccess (_, _) -> 24
        | HxExpr.ERange (_, _) -> 25
        | HxExpr.ECast (_, _) -> 26
        | HxExpr.EUntyped _ -> 27
        | HxExpr.EUnsupported _ -> 28) = 10 then let _g2 = Obj.magic (match _g with
        | HxExpr.ECall (__enum_param_42, _) -> __enum_param_42
        | _ -> failwith "Unexpected enum parameter") in let _g3 = Obj.magic (match _g with
        | HxExpr.ECall (_, __enum_param_43) -> __enum_param_43
        | _ -> failwith "Unexpected enum parameter") in if (match _g2 with
        | HxExpr.ENull -> 0
        | HxExpr.EBool _ -> 1
        | HxExpr.EString _ -> 2
        | HxExpr.EInt _ -> 3
        | HxExpr.EFloat _ -> 4
        | HxExpr.EEnumValue _ -> 5
        | HxExpr.EThis -> 6
        | HxExpr.ESuper -> 7
        | HxExpr.EIdent _ -> 8
        | HxExpr.EField (_, _) -> 9
        | HxExpr.ECall (_, _) -> 10
        | HxExpr.EMacroExpr (_, _) -> 11
        | HxExpr.EMacroType _ -> 12
        | HxExpr.ELambda (_, _) -> 13
        | HxExpr.ETryCatchRaw _ -> 14
        | HxExpr.ESwitchRaw _ -> 15
        | HxExpr.ESwitch (_, _, _) -> 16
        | HxExpr.ENew (_, _) -> 17
        | HxExpr.EUnop (_, _) -> 18
        | HxExpr.EBinop (_, _, _) -> 19
        | HxExpr.ETernary (_, _, _) -> 20
        | HxExpr.EAnon (_, _) -> 21
        | HxExpr.EArrayComprehension (_, _, _, _) -> 22
        | HxExpr.EArrayDecl _ -> 23
        | HxExpr.EArrayAccess (_, _) -> 24
        | HxExpr.ERange (_, _) -> 25
        | HxExpr.ECast (_, _) -> 26
        | HxExpr.EUntyped _ -> 27
        | HxExpr.EUnsupported _ -> 28) = 9 then let _g4 = Obj.magic (match _g2 with
        | HxExpr.EField (__enum_param_44, _) -> __enum_param_44
        | _ -> failwith "Unexpected enum parameter") in let _g5 = (match _g2 with
        | HxExpr.EField (_, __enum_param_45) -> __enum_param_45
        | _ -> failwith "Unexpected enum parameter" : string) in if (match _g4 with
        | HxExpr.ENull -> 0
        | HxExpr.EBool _ -> 1
        | HxExpr.EString _ -> 2
        | HxExpr.EInt _ -> 3
        | HxExpr.EFloat _ -> 4
        | HxExpr.EEnumValue _ -> 5
        | HxExpr.EThis -> 6
        | HxExpr.ESuper -> 7
        | HxExpr.EIdent _ -> 8
        | HxExpr.EField (_, _) -> 9
        | HxExpr.ECall (_, _) -> 10
        | HxExpr.EMacroExpr (_, _) -> 11
        | HxExpr.EMacroType _ -> 12
        | HxExpr.ELambda (_, _) -> 13
        | HxExpr.ETryCatchRaw _ -> 14
        | HxExpr.ESwitchRaw _ -> 15
        | HxExpr.ESwitch (_, _, _) -> 16
        | HxExpr.ENew (_, _) -> 17
        | HxExpr.EUnop (_, _) -> 18
        | HxExpr.EBinop (_, _, _) -> 19
        | HxExpr.ETernary (_, _, _) -> 20
        | HxExpr.EAnon (_, _) -> 21
        | HxExpr.EArrayComprehension (_, _, _, _) -> 22
        | HxExpr.EArrayDecl _ -> 23
        | HxExpr.EArrayAccess (_, _) -> 24
        | HxExpr.ERange (_, _) -> 25
        | HxExpr.ECast (_, _) -> 26
        | HxExpr.EUntyped _ -> 27
        | HxExpr.EUnsupported _ -> 28) = 8 then let _g6 = (match _g4 with
        | HxExpr.EIdent __enum_param_46 -> __enum_param_46
        | _ -> failwith "Unexpected enum parameter" : string) in if HxString.equals _g6 "Sys" then if HxString.equals _g5 "println" then let args = Obj.magic _g3 in if HxArray.length args = 1 then let __assign_47 = Obj.magic (let __arr_48 = HxArray.create () in (
        ignore (HxArray.push __arr_48 (((HxString.toStdString indent ^ "std::cout << ") ^ HxString.toStdString (stringExpr (Obj.magic (HxArray.get (Obj.magic args) 0)))) ^ " << std::endl;"));
        __arr_48
      )) in (
        tempResult := __assign_47;
        __assign_47
      ) else let expr = Obj.magic _g in let __assign_49 = Obj.magic (let __arr_50 = HxArray.create () in (
        ignore (HxArray.push __arr_50 ((HxString.toStdString indent ^ HxString.toStdString (renderExpr (Obj.magic expr))) ^ ";"));
        __arr_50
      )) in (
        tempResult := __assign_49;
        __assign_49
      ) else let expr = Obj.magic _g in let __assign_51 = Obj.magic (let __arr_52 = HxArray.create () in (
        ignore (HxArray.push __arr_52 ((HxString.toStdString indent ^ HxString.toStdString (renderExpr (Obj.magic expr))) ^ ";"));
        __arr_52
      )) in (
        tempResult := __assign_51;
        __assign_51
      ) else let expr = Obj.magic _g in let __assign_53 = Obj.magic (let __arr_54 = HxArray.create () in (
        ignore (HxArray.push __arr_54 ((HxString.toStdString indent ^ HxString.toStdString (renderExpr (Obj.magic expr))) ^ ";"));
        __arr_54
      )) in (
        tempResult := __assign_53;
        __assign_53
      ) else let expr = Obj.magic _g in let __assign_55 = Obj.magic (let __arr_56 = HxArray.create () in (
        ignore (HxArray.push __arr_56 ((HxString.toStdString indent ^ HxString.toStdString (renderExpr (Obj.magic expr))) ^ ";"));
        __arr_56
      )) in (
        tempResult := __assign_55;
        __assign_55
      ) else let expr = Obj.magic _g in let __assign_57 = Obj.magic (let __arr_58 = HxArray.create () in (
        ignore (HxArray.push __arr_58 ((HxString.toStdString indent ^ HxString.toStdString (renderExpr (Obj.magic expr))) ^ ";"));
        __arr_58
      )) in (
        tempResult := __assign_57;
        __assign_57
      ) else let expr = Obj.magic _g in let __assign_59 = Obj.magic (let __arr_60 = HxArray.create () in (
        ignore (HxArray.push __arr_60 ((HxString.toStdString indent ^ HxString.toStdString (renderExpr (Obj.magic expr))) ^ ";"));
        __arr_60
      )) in (
        tempResult := __assign_59;
        __assign_59
      )
    )
    | _ -> HxType.hx_throw_typed_rtti (Obj.repr ("C++ source backend MVP unsupported statement: " ^ HxString.toStdString (stmtKind (Obj.magic stmt)))) ["Dynamic"; "String"]);
  !tempResult
)

let renderProgram = fun className body -> (
  ignore className;
  let out = Obj.magic (HxArray.create ()) in (
    ignore (HxArray.push out "// Generated by hxhx Stage3 C++ source backend MVP");
    ignore (HxArray.push out "#include <iostream>");
    ignore (HxArray.push out "#include <string>");
    ignore (HxArray.push out "");
    ignore (HxArray.push out "int main(int argc, char** argv) {");
    ignore (HxArray.push out "  (void)argc;");
    ignore (HxArray.push out "  (void)argv;");
    let _g = ref 0 in let _g1 = Obj.magic (renderStmts (Obj.magic body) ("  " : string)) in (
      ignore (while !_g < HxArray.length _g1 do ignore (let line = (HxArray.get (Obj.magic _g1) (!_g) : string) in (
        ignore (let __old_24 = !_g in let __new_25 = HxInt.add __old_24 1 in (
          ignore (_g := __new_25);
          __new_25
        ));
        HxArray.push out line
      )) done);
      ignore (HxArray.push out "  return 0;");
      ignore (HxArray.push out "}");
      HxString.toStdString (HxArray.join out "\n" (fun x -> x)) ^ "\n"
    )
  )
)

let executablePath = fun outputDir className -> Haxe_io_Path.join (Obj.magic (let __arr_175 = HxArray.create () in (
  ignore (HxArray.push __arr_175 outputDir);
  ignore (HxArray.push __arr_175 className);
  __arr_175
)))

let rec ensureDirectory = fun path -> ignore (try (
  ignore (if path == Obj.magic (HxRuntime.hx_null) || HxString.length path = 0 || HxFileSystem.exists path then raise (HxRuntime.Hx_return (Obj.repr ())) else ());
  let parent = (Haxe_io_Path.directory (path : string) : string) in (
    ignore (if parent != Obj.magic (HxRuntime.hx_null) && HxString.length parent > 0 && not (HxString.equals parent path) then ignore (ensureDirectory (parent : string)) else ());
    HxFileSystem.createDirectory path
  )
) with
  | HxRuntime.Hx_return __ret_176 -> Obj.obj __ret_176)

let ensureParentDirectory = fun filePath -> ignore (let parent = (Haxe_io_Path.directory (filePath : string) : string) in if parent != Obj.magic (HxRuntime.hx_null) && HxString.length parent > 0 then ignore (ensureDirectory (parent : string)) else ())

let commandExists = fun name -> HxSys.command "sh" (Some (let __arr_177 = HxArray.create () in (
  ignore (HxArray.push __arr_177 "-c");
  ignore (HxArray.push __arr_177 (("command -v " ^ HxString.toStdString name) ^ " >/dev/null 2>&1"));
  __arr_177
))) = 0

let cppCompilerCommand = fun () -> try let __fallback_result_179 = (
  ignore (let candidate = ("c++" : string) in if commandExists (candidate : string) then raise (HxRuntime.Hx_return (Obj.repr (candidate : string))) else ());
  ignore (let candidate = ("g++" : string) in if commandExists (candidate : string) then raise (HxRuntime.Hx_return (Obj.repr (candidate : string))) else ());
  ignore (let candidate = ("clang++" : string) in if commandExists (candidate : string) then raise (HxRuntime.Hx_return (Obj.repr (candidate : string))) else ());
  Obj.magic (HxRuntime.hx_null)
) in Obj.magic __fallback_result_179 with
  | HxRuntime.Hx_return __ret_178 -> Obj.obj __ret_178

let emit = fun program context -> try let __fallback_result_9 = let main = mainModule (Obj.magic program) (Obj.magic context) in let className = (sanitizeIdentifier (HxClassDecl.getName (Obj.magic (Obj.obj (HxAnon.get main "cls"))) : string) : string) in let sourceDir = (Haxe_io_Path.join (Obj.magic (let __arr_1 = HxArray.create () in (
  ignore (HxArray.push __arr_1 ((Obj.magic context : Backend_BackendContext.t).outputDir));
  ignore (HxArray.push __arr_1 "src");
  __arr_1
))) : string) in let tempMaybeString = ref (Obj.magic (HxRuntime.hx_null) : string) in (
  ignore (if (Obj.magic context : Backend_BackendContext.t).outputFileHint != Obj.magic (HxRuntime.hx_null) && HxString.length ((Obj.magic context : Backend_BackendContext.t).outputFileHint) > 0 then let __assign_2 = Obj.magic ((Obj.magic context : Backend_BackendContext.t).outputFileHint : string) in (
    tempMaybeString := __assign_2;
    __assign_2
  ) else let __assign_3 = Obj.magic (Haxe_io_Path.join (Obj.magic (let __arr_4 = HxArray.create () in (
    ignore (HxArray.push __arr_4 sourceDir);
    ignore (HxArray.push __arr_4 (HxString.toStdString className ^ ".cpp"));
    __arr_4
  ))) : string) in (
    tempMaybeString := __assign_3;
    __assign_3
  ));
  ignore (ensureParentDirectory (!tempMaybeString : string));
  let content = (renderProgram (className : string) (Obj.magic (HxFunctionDecl.getBody (Obj.magic (Obj.obj (HxAnon.get main "fn"))))) : string) in (
    ignore (HxFile.saveContent (!tempMaybeString : string) (content : string));
    ignore (if (Obj.magic context : Backend_BackendContext.t).buildExecutable && not (Backend_BackendContext.hasDefine (Obj.magic context) ("no-compilation" : string)) then ignore (let exePath = (executablePath ((Obj.magic context : Backend_BackendContext.t).outputDir : string) (className : string) : string) in (
      ignore (ensureParentDirectory (exePath : string));
      let compiler = (cppCompilerCommand () : string) in (
        ignore (if compiler == Obj.magic (HxRuntime.hx_null) then ignore (HxType.hx_throw_typed_rtti (Obj.repr "C++ source backend MVP executable packaging requires `c++`, `g++`, or `clang++` on PATH") ["Dynamic"; "String"]) else ());
        let code = HxSys.command compiler (Some (let __arr_5 = HxArray.create () in (
          ignore (HxArray.push __arr_5 "-std=c++17");
          ignore (HxArray.push __arr_5 (!tempMaybeString));
          ignore (HxArray.push __arr_5 "-o");
          ignore (HxArray.push __arr_5 exePath);
          __arr_5
        ))) in (
          ignore (if code <> 0 then ignore (HxType.hx_throw_typed_rtti (Obj.repr ("C++ source backend MVP executable packaging failed with exit code " ^ string_of_int code)) ["Dynamic"; "String"]) else ());
          raise (HxRuntime.Hx_return (Obj.repr (Backend_EmitResult.create (exePath : string) (Obj.magic (let __arr_6 = HxArray.create () in (
            ignore (HxArray.push __arr_6 (Backend_EmitArtifact.create ("entry_cpp_source" : string) (!tempMaybeString : string)));
            ignore (HxArray.push __arr_6 (Backend_EmitArtifact.create ("entry_cpp_exe" : string) (exePath : string)));
            __arr_6
          ))) true)))
        )
      )
    )) else ());
    Backend_EmitResult.create (!tempMaybeString : string) (Obj.magic (let __arr_7 = HxArray.create () in (
      ignore (HxArray.push __arr_7 (Backend_EmitArtifact.create ("entry_cpp_source" : string) (!tempMaybeString : string)));
      __arr_7
    ))) false
  )
) in Obj.magic __fallback_result_9 with
  | HxRuntime.Hx_return __ret_8 -> Obj.obj __ret_8