# 1 "CompilerConditionalDefineInput.ml"
(* Generated by reflaxe.ocaml (WIP) *)
(* Haxe type: CompilerConditionalDefineInput *)

let __reflaxe_ocaml__ = ()

type t = { __hx_type : Obj.t; mutable name : string; mutable access : CompilerConditionalDefineAccess.compilerconditionaldefineaccess; mutable observedInputRevision : string }

let create = fun name2 access2 observedInputRevision2 -> let self = ({ __hx_type = HxType.class_ "CompilerConditionalDefineInput"; name = ""; access = Obj.magic (HxRuntime.hx_null); observedInputRevision = "" } : t) in (
  ignore (ignore (let tempRight = ref ("" : string) in (
    ignore (if name2 == Obj.magic (HxRuntime.hx_null) then let __assign_1 = ("" : string) in (
      tempRight := __assign_1;
      __assign_1
    ) else let __assign_2 = (StringTools.trim (name2 : string) : string) in (
      tempRight := __assign_2;
      __assign_2
    ));
    ignore (let __assign_3 = (!tempRight : string) in (
      (Obj.magic self : t).name <- __assign_3;
      __assign_3
    ));
    ignore (let __assign_4 = Obj.magic access2 in (
      (Obj.magic self : t).access <- __assign_4;
      __assign_4
    ));
    let tempRight1 = ref ("" : string) in (
      ignore (if observedInputRevision2 == Obj.magic (HxRuntime.hx_null) then let __assign_5 = ("" : string) in (
        tempRight1 := __assign_5;
        __assign_5
      ) else let __assign_6 = (observedInputRevision2 : string) in (
        tempRight1 := __assign_6;
        __assign_6
      ));
      ignore (let __assign_7 = (!tempRight1 : string) in (
        (Obj.magic self : t).observedInputRevision <- __assign_7;
        __assign_7
      ));
      ignore (if HxString.length ((Obj.magic self : t).name) = 0 then ignore (HxType.hx_throw_typed_rtti (Obj.repr "conditional-compilation definition name is required") ["Dynamic"; "String"]) else ());
      ignore (if (Obj.magic self : t).access == Obj.magic (HxRuntime.hx_null) then ignore (HxType.hx_throw_typed_rtti (Obj.repr "conditional-compilation definition access is required") ["Dynamic"; "String"]) else ());
      if HxString.length ((Obj.magic self : t).observedInputRevision) = 0 then ignore (HxType.hx_throw_typed_rtti (Obj.repr "conditional-compilation observed input revision is required") ["Dynamic"; "String"]) else ()
    )
  )));
  self
)

let __empty = fun () -> ({ __hx_type = HxType.class_ "CompilerConditionalDefineInput"; name = ""; access = Obj.magic (HxRuntime.hx_null); observedInputRevision = "" } : t)

let getObservedInputRevision = fun self () -> (Obj.magic self : t).observedInputRevision

let accessKey = fun self () -> let tempMaybeString = ref (Obj.magic (HxRuntime.hx_null) : string) in (
  ignore (if (Obj.magic self : t).access = CompilerConditionalDefineAccess.Value then let __assign_8 = Obj.magic ("value" : string) in (
    tempMaybeString := __assign_8;
    __assign_8
  ) else let __assign_9 = Obj.magic ("presence" : string) in (
    tempMaybeString := __assign_9;
    __assign_9
  ));
  CompilerCacheIdentity.encode (Obj.magic (let __arr_10 = HxArray.create () in (
    ignore (HxArray.push __arr_10 "conditional-define-access-key-v1");
    ignore (HxArray.push __arr_10 ((Obj.magic self : t).name));
    ignore (HxArray.push __arr_10 (!tempMaybeString));
    __arr_10
  )))
)

let canonicalKey = fun self () -> let tempMaybeString = ref (Obj.magic (HxRuntime.hx_null) : string) in (
  ignore (if (Obj.magic self : t).access = CompilerConditionalDefineAccess.Value then let __assign_11 = Obj.magic ("value" : string) in (
    tempMaybeString := __assign_11;
    __assign_11
  ) else let __assign_12 = Obj.magic ("presence" : string) in (
    tempMaybeString := __assign_12;
    __assign_12
  ));
  CompilerCacheIdentity.encode (Obj.magic (let __arr_13 = HxArray.create () in (
    ignore (HxArray.push __arr_13 "conditional-define-fact-v2");
    ignore (HxArray.push __arr_13 ((Obj.magic self : t).name));
    ignore (HxArray.push __arr_13 (!tempMaybeString));
    ignore (HxArray.push __arr_13 ((Obj.magic self : t).observedInputRevision));
    __arr_13
  )))
)

let fromDefines = fun name2 access2 defines -> let tempString = ref ("" : string) in (
  ignore (if name2 == Obj.magic (HxRuntime.hx_null) then let __assign_14 = ("" : string) in (
    tempString := __assign_14;
    __assign_14
  ) else let __assign_15 = (StringTools.trim (name2 : string) : string) in (
    tempString := __assign_15;
    __assign_15
  ));
  let present = HxString.length (!tempString) > 0 && defines != Obj.magic (HxRuntime.hx_null) && HxMap.exists_string defines (!tempString) in let tempMaybeString = ref (Obj.magic (HxRuntime.hx_null) : string) in (
    ignore (if present then let __assign_16 = Obj.magic (HxMap.get_string defines (!tempString) : string) in (
      tempMaybeString := __assign_16;
      __assign_16
    ) else let __assign_17 = Obj.magic (Obj.magic (HxRuntime.hx_null)) in (
      tempMaybeString := __assign_17;
      __assign_17
    ));
    let tempString1 = ref ("" : string) in (
      ignore (if access2 = CompilerConditionalDefineAccess.Value then let __assign_18 = ("value" : string) in (
        tempString1 := __assign_18;
        __assign_18
      ) else let __assign_19 = ("presence" : string) in (
        tempString1 := __assign_19;
        __assign_19
      ));
      let tempString2 = ref ("" : string) in (
        ignore (if present then let __assign_20 = ("present" : string) in (
          tempString2 := __assign_20;
          __assign_20
        ) else let __assign_21 = ("absent" : string) in (
          tempString2 := __assign_21;
          __assign_21
        ));
        let tempMaybeString1 = ref (Obj.magic (HxRuntime.hx_null) : string) in (
          ignore (if access2 = CompilerConditionalDefineAccess.Value then let __assign_22 = Obj.magic (!tempMaybeString : string) in (
            tempMaybeString1 := __assign_22;
            __assign_22
          ) else let __assign_23 = Obj.magic (Obj.magic (HxRuntime.hx_null)) in (
            tempMaybeString1 := __assign_23;
            __assign_23
          ));
          let identityInputs = Obj.magic (let __arr_24 = HxArray.create () in (
            ignore (HxArray.push __arr_24 "conditional-define-input-v2");
            ignore (HxArray.push __arr_24 (!tempString));
            ignore (HxArray.push __arr_24 (!tempString1));
            ignore (HxArray.push __arr_24 (!tempString2));
            ignore (HxArray.push __arr_24 (!tempMaybeString1));
            __arr_24
          )) in let tempString3 = ref ("" : string) in (
            ignore (if access2 = CompilerConditionalDefineAccess.Value then let __assign_25 = (Haxe_crypto_Sha256.encode (CompilerCacheIdentity.encode (Obj.magic identityInputs) : string) : string) in (
              tempString3 := __assign_25;
              __assign_25
            ) else let __assign_26 = (CompilerCacheIdentity.encode (Obj.magic identityInputs) : string) in (
              tempString3 := __assign_26;
              __assign_26
            ));
            create (!tempString : string) (Obj.magic access2) (!tempString3 : string)
          )
        )
      )
    )
  )
)