# 1 "hxhx_Stage1Compiler.ml"
(* Generated by reflaxe.ocaml (WIP) *)
(* Haxe type: hxhx.Stage1Args *)

let __reflaxe_ocaml__ = ()

type stage1args_t = { __hx_type : Obj.t; mutable classPaths : string HxArray.t; mutable main : string; mutable noOutput : bool; mutable roots : string HxArray.t; mutable defines : string HxArray.t; mutable libs : string HxArray.t; mutable macros : string HxArray.t; mutable resourceSpecs : string HxArray.t; mutable displayRequest : string; mutable cwd : string; mutable hadCmd : bool; mutable cmdCommands : string HxArray.t }

let stage1args_create = fun classPaths2 main2 noOutput2 roots2 defines2 libs2 macros2 resourceSpecs2 displayRequest2 cwd2 hadCmd2 cmdCommands2 -> let self = ({ __hx_type = HxType.class_ "hxhx.Stage1Args"; classPaths = Obj.magic (HxRuntime.hx_null); main = ""; noOutput = false; roots = Obj.magic (HxRuntime.hx_null); defines = Obj.magic (HxRuntime.hx_null); libs = Obj.magic (HxRuntime.hx_null); macros = Obj.magic (HxRuntime.hx_null); resourceSpecs = Obj.magic (HxRuntime.hx_null); displayRequest = Obj.magic (HxRuntime.hx_null); cwd = ""; hadCmd = false; cmdCommands = Obj.magic (HxRuntime.hx_null) } : stage1args_t) in (
  ignore (ignore ((
    ignore (let __assign_1 = Obj.magic classPaths2 in (
      (Obj.magic self : stage1args_t).classPaths <- __assign_1;
      __assign_1
    ));
    ignore (let __assign_2 = (main2 : string) in (
      (Obj.magic self : stage1args_t).main <- __assign_2;
      __assign_2
    ));
    ignore (let __assign_3 = noOutput2 in (
      (Obj.magic self : stage1args_t).noOutput <- __assign_3;
      __assign_3
    ));
    ignore (let __assign_4 = Obj.magic roots2 in (
      (Obj.magic self : stage1args_t).roots <- __assign_4;
      __assign_4
    ));
    ignore (let __assign_5 = Obj.magic defines2 in (
      (Obj.magic self : stage1args_t).defines <- __assign_5;
      __assign_5
    ));
    ignore (let __assign_6 = Obj.magic libs2 in (
      (Obj.magic self : stage1args_t).libs <- __assign_6;
      __assign_6
    ));
    ignore (let __assign_7 = Obj.magic macros2 in (
      (Obj.magic self : stage1args_t).macros <- __assign_7;
      __assign_7
    ));
    let tempRight = ref (Obj.magic (HxRuntime.hx_null) : string HxArray.t) in (
      ignore (if resourceSpecs2 == Obj.magic (HxRuntime.hx_null) then let __assign_8 = Obj.magic (let __arr_9 = HxArray.create () in __arr_9) in (
        tempRight := __assign_8;
        __assign_8
      ) else let __assign_10 = Obj.magic resourceSpecs2 in (
        tempRight := __assign_10;
        __assign_10
      ));
      ignore (let __assign_11 = Obj.magic (!tempRight) in (
        (Obj.magic self : stage1args_t).resourceSpecs <- __assign_11;
        __assign_11
      ));
      ignore (let __assign_12 = (displayRequest2 : string) in (
        (Obj.magic self : stage1args_t).displayRequest <- __assign_12;
        __assign_12
      ));
      ignore (let __assign_13 = (cwd2 : string) in (
        (Obj.magic self : stage1args_t).cwd <- __assign_13;
        __assign_13
      ));
      ignore (let __assign_14 = hadCmd2 in (
        (Obj.magic self : stage1args_t).hadCmd <- __assign_14;
        __assign_14
      ));
      let tempRight1 = ref (Obj.magic (HxRuntime.hx_null) : string HxArray.t) in (
        ignore (if cmdCommands2 == Obj.magic (HxRuntime.hx_null) then let __assign_15 = Obj.magic (let __arr_16 = HxArray.create () in __arr_16) in (
          tempRight1 := __assign_15;
          __assign_15
        ) else let __assign_17 = Obj.magic cmdCommands2 in (
          tempRight1 := __assign_17;
          __assign_17
        ));
        let __assign_18 = Obj.magic (!tempRight1) in (
          (Obj.magic self : stage1args_t).cmdCommands <- __assign_18;
          __assign_18
        )
      )
    )
  )));
  self
)

let stage1args___empty = fun () -> ({ __hx_type = HxType.class_ "hxhx.Stage1Args"; classPaths = Obj.magic (HxRuntime.hx_null); main = ""; noOutput = false; roots = Obj.magic (HxRuntime.hx_null); defines = Obj.magic (HxRuntime.hx_null); libs = Obj.magic (HxRuntime.hx_null); macros = Obj.magic (HxRuntime.hx_null); resourceSpecs = Obj.magic (HxRuntime.hx_null); displayRequest = Obj.magic (HxRuntime.hx_null); cwd = ""; hadCmd = false; cmdCommands = Obj.magic (HxRuntime.hx_null) } : stage1args_t)

let stage1args_readHaxercVersion = fun path -> try let __fallback_result_55 = (
  ignore (try let content = (HxFile.getContent (path : string) : string) in let versionPattern = Obj.magic (EReg.create ("\"version\"\\s*:\\s*\"([^\"]+)\"" : string) ("" : string)) in if EReg.hx_match (Obj.magic versionPattern) (content : string) then raise (HxRuntime.Hx_return (Obj.repr (StringTools.trim (EReg.matched (Obj.magic versionPattern) 1 : string) : string))) else () with
    | HxRuntime.Hx_break -> raise (HxRuntime.Hx_break)
    | HxRuntime.Hx_continue -> raise (HxRuntime.Hx_continue)
    | HxRuntime.Hx_return __ret_50 -> raise (HxRuntime.Hx_return __ret_50)
    | HxRuntime.Hx_exception (__exn_v_51, __exn_tags_52) -> if HxRuntime.tags_has __exn_tags_52 "haxe.io.Error" then let _hx = (Obj.obj (HxEnum.unbox_or_obj "haxe.io.Error" __exn_v_51) : Haxe_io_Error.error) in (
      ignore _hx;
      ()
    ) else if HxRuntime.tags_has __exn_tags_52 "String" then let _hx = (Obj.obj __exn_v_51 : string) in (
      ignore _hx;
      ()
    ) else HxRuntime.hx_throw_typed __exn_v_51 __exn_tags_52
    | __exn_53 -> if HxRuntime.tags_has ["OcamlExn"] "haxe.io.Error" then let _hx = (Obj.obj (HxEnum.unbox_or_obj "haxe.io.Error" (Obj.repr __exn_53)) : Haxe_io_Error.error) in (
      ignore _hx;
      ()
    ) else if HxRuntime.tags_has ["OcamlExn"] "String" then let _hx = (Obj.obj (Obj.repr __exn_53) : string) in (
      ignore _hx;
      ()
    ) else raise (__exn_53));
  ""
) in Obj.magic __fallback_result_55 with
  | HxRuntime.Hx_return __ret_54 -> Obj.obj __ret_54

let stage1args_resolveHomeDir = fun () -> try let __fallback_result_57 = let home = (HxSys.getEnv "HOME" : string) in (
  ignore (if home != Obj.magic (HxRuntime.hx_null) && HxString.length home > 0 then raise (HxRuntime.Hx_return (Obj.repr (home : string))) else ());
  let userProfile = (HxSys.getEnv "USERPROFILE" : string) in (
    ignore (if userProfile != Obj.magic (HxRuntime.hx_null) && HxString.length userProfile > 0 then raise (HxRuntime.Hx_return (Obj.repr (userProfile : string))) else ());
    ""
  )
) in Obj.magic __fallback_result_57 with
  | HxRuntime.Hx_return __ret_56 -> Obj.obj __ret_56

let stage1args_inferStdRootFromHaxerc = fun cwd2 -> try let __fallback_result_49 = let home = (stage1args_resolveHomeDir () : string) in (
  ignore (if HxString.length home = 0 then raise (HxRuntime.Hx_return (Obj.repr ("" : string))) else ());
  let tempString = ref ("" : string) in (
    ignore (if cwd2 == Obj.magic (HxRuntime.hx_null) || HxString.length cwd2 = 0 then let __assign_39 = ("." : string) in (
      tempString := __assign_39;
      __assign_39
    ) else let __assign_40 = (cwd2 : string) in (
      tempString := __assign_40;
      __assign_40
    ));
    let dir = ref (Haxe_io_Path.normalize (HxFileSystem.absolutePath (!tempString) : string) : string) in let previous = ref ("" : string) in (
      ignore (while not (HxString.equals (!dir) (!previous)) do ignore (let haxercPath = (Haxe_io_Path.join (Obj.magic (let __arr_41 = HxArray.create () in (
        ignore (HxArray.push __arr_41 (!dir));
        ignore (HxArray.push __arr_41 ".haxerc");
        __arr_41
      ))) : string) in (
        ignore (if HxFileSystem.exists haxercPath && not (HxFileSystem.isDirectory haxercPath) then ignore (let version = (stage1args_readHaxercVersion (haxercPath : string) : string) in if HxString.length version > 0 then ignore (let candidate = (Haxe_io_Path.normalize (Haxe_io_Path.join (Obj.magic (let __arr_42 = HxArray.create () in (
          ignore (HxArray.push __arr_42 home);
          ignore (HxArray.push __arr_42 "haxe");
          ignore (HxArray.push __arr_42 "versions");
          ignore (HxArray.push __arr_42 version);
          ignore (HxArray.push __arr_42 "std");
          __arr_42
        ))) : string) : string) in (
          ignore (if HxFileSystem.exists candidate && HxFileSystem.isDirectory candidate then raise (HxRuntime.Hx_return (Obj.repr (candidate : string))) else ());
          let hiddenCandidate = (Haxe_io_Path.normalize (Haxe_io_Path.join (Obj.magic (let __arr_43 = HxArray.create () in (
            ignore (HxArray.push __arr_43 home);
            ignore (HxArray.push __arr_43 ".haxe");
            ignore (HxArray.push __arr_43 "versions");
            ignore (HxArray.push __arr_43 version);
            ignore (HxArray.push __arr_43 "std");
            __arr_43
          ))) : string) : string) in if HxFileSystem.exists hiddenCandidate && HxFileSystem.isDirectory hiddenCandidate then raise (HxRuntime.Hx_return (Obj.repr (hiddenCandidate : string))) else ()
        )) else ()) else ());
        ignore (let __assign_44 = (!dir : string) in (
          previous := __assign_44;
          __assign_44
        ));
        let tempString1 = ref ("" : string) in (
          ignore (if StringTools.endsWith (!dir : string) ("/" : string) then let __assign_45 = (HxString.toStdString (!dir) ^ ".." : string) in (
            tempString1 := __assign_45;
            __assign_45
          ) else let __assign_46 = (HxString.toStdString (!dir) ^ "/.." : string) in (
            tempString1 := __assign_46;
            __assign_46
          ));
          let parentInput = (!tempString1 : string) in let __assign_47 = (Haxe_io_Path.normalize (HxFileSystem.absolutePath parentInput : string) : string) in (
            dir := __assign_47;
            __assign_47
          )
        )
      )) done);
      ""
    )
  )
) in Obj.magic __fallback_result_49 with
  | HxRuntime.Hx_return __ret_48 -> Obj.obj __ret_48

let stage1args_inferStdRoot = fun cwd2 -> try let __fallback_result_38 = (
  ignore (try let direct = (HxSys.getEnv "HAXE_STD_PATH" : string) in (
    ignore (if direct != Obj.magic (HxRuntime.hx_null) && HxString.length direct > 0 && HxFileSystem.exists direct && HxFileSystem.isDirectory direct then raise (HxRuntime.Hx_return (Obj.repr (direct : string))) else ());
    let haxePath = (HxSys.getEnv "HAXEPATH" : string) in (
      ignore (if haxePath != Obj.magic (HxRuntime.hx_null) && HxString.length haxePath > 0 then ignore (let candidate = (Haxe_io_Path.normalize (Haxe_io_Path.join (Obj.magic (let __arr_32 = HxArray.create () in (
        ignore (HxArray.push __arr_32 haxePath);
        ignore (HxArray.push __arr_32 "std");
        __arr_32
      ))) : string) : string) in if HxFileSystem.exists candidate && HxFileSystem.isDirectory candidate then raise (HxRuntime.Hx_return (Obj.repr (candidate : string))) else ()) else ());
      let lixCandidate = (stage1args_inferStdRootFromHaxerc (cwd2 : string) : string) in if HxString.length lixCandidate > 0 then raise (HxRuntime.Hx_return (Obj.repr (lixCandidate : string))) else ()
    )
  ) with
    | HxRuntime.Hx_break -> raise (HxRuntime.Hx_break)
    | HxRuntime.Hx_continue -> raise (HxRuntime.Hx_continue)
    | HxRuntime.Hx_return __ret_33 -> raise (HxRuntime.Hx_return __ret_33)
    | HxRuntime.Hx_exception (__exn_v_34, __exn_tags_35) -> if HxRuntime.tags_has __exn_tags_35 "haxe.io.Error" then let _hx = (Obj.obj (HxEnum.unbox_or_obj "haxe.io.Error" __exn_v_34) : Haxe_io_Error.error) in (
      ignore _hx;
      ()
    ) else if HxRuntime.tags_has __exn_tags_35 "String" then let _hx = (Obj.obj __exn_v_34 : string) in (
      ignore _hx;
      ()
    ) else HxRuntime.hx_throw_typed __exn_v_34 __exn_tags_35
    | __exn_36 -> if HxRuntime.tags_has ["OcamlExn"] "haxe.io.Error" then let _hx = (Obj.obj (HxEnum.unbox_or_obj "haxe.io.Error" (Obj.repr __exn_36)) : Haxe_io_Error.error) in (
      ignore _hx;
      ()
    ) else if HxRuntime.tags_has ["OcamlExn"] "String" then let _hx = (Obj.obj (Obj.repr __exn_36) : string) in (
      ignore _hx;
      ()
    ) else raise (__exn_36));
  ""
) in Obj.magic __fallback_result_38 with
  | HxRuntime.Hx_return __ret_37 -> Obj.obj __ret_37

let stage1args_inferStdRootForCwd = fun cwd2 -> stage1args_inferStdRoot (cwd2 : string)

let stage1args_expandHxmlArgs = fun args -> try let __fallback_result_69 = let sawHxml = ref false in let out = Obj.magic (HxArray.create ()) in let cwd2 = ref (HxFileSystem.absolutePath "." : string) in let i = ref 0 in (
  ignore (try while !i < HxArray.length args do try ignore (let a = (HxArray.get (Obj.magic args) (!i) : string) in (
    ignore (if a == Obj.magic (HxRuntime.hx_null) || HxString.length a = 0 then ignore ((
      ignore (i := HxInt.add (!i) 1);
      raise (HxRuntime.Hx_continue)
    )) else ());
    ignore (if (HxString.equals a "-C" || HxString.equals a "--cwd") && HxInt.add (!i) 1 < HxArray.length args then ignore (let next = (HxArray.get (Obj.magic args) (HxInt.add (!i) 1) : string) in (
      ignore (HxArray.push out a);
      ignore (HxArray.push out next);
      let tempRight = ref ("" : string) in (
        ignore (if Haxe_io_Path.isAbsolute (next : string) then let __assign_58 = (HxFileSystem.absolutePath next : string) in (
          tempRight := __assign_58;
          __assign_58
        ) else let __assign_59 = (HxFileSystem.absolutePath ((HxString.toStdString (!cwd2) ^ "/") ^ HxString.toStdString next) : string) in (
          tempRight := __assign_59;
          __assign_59
        ));
        ignore (let __assign_60 = (!tempRight : string) in (
          cwd2 := __assign_60;
          __assign_60
        ));
        ignore (i := HxInt.add (!i) 2);
        raise (HxRuntime.Hx_continue)
      )
    )) else ());
    ignore (if not (StringTools.startsWith (a : string) ("-" : string)) && StringTools.endsWith (a : string) (".hxml" : string) then ignore ((
      ignore (let __assign_61 = true in (
        sawHxml := __assign_61;
        __assign_61
      ));
      let tempString = ref ("" : string) in (
        ignore (if Haxe_io_Path.isAbsolute (a : string) then let __assign_62 = (HxFileSystem.absolutePath a : string) in (
          tempString := __assign_62;
          __assign_62
        ) else let __assign_63 = (HxFileSystem.absolutePath ((HxString.toStdString (!cwd2) ^ "/") ^ HxString.toStdString a) : string) in (
          tempString := __assign_63;
          __assign_63
        ));
        let hxmlPath = (!tempString : string) in (
          ignore (if not (HxFileSystem.exists hxmlPath) || HxFileSystem.isDirectory hxmlPath then ignore ((
            ignore (print_endline ("hxhx(stage1): hxml path is not a file: " ^ HxString.toStdString hxmlPath));
            raise (HxRuntime.Hx_return (Obj.repr (Obj.magic (HxRuntime.hx_null))))
          )) else ());
          let expanded = Obj.magic (Hxhx_Hxml.parseFile (hxmlPath : string)) in (
            ignore (if expanded == Obj.magic (HxRuntime.hx_null) then raise (HxRuntime.Hx_return (Obj.repr (Obj.magic (Obj.magic (HxRuntime.hx_null))))) else ());
            let _g = ref 0 in (
              ignore (while !_g < HxArray.length expanded do ignore (let t = (HxArray.get (Obj.magic expanded) (!_g) : string) in (
                ignore (let __old_64 = !_g in let __new_65 = HxInt.add __old_64 1 in (
                  ignore (_g := __new_65);
                  __new_65
                ));
                HxArray.push out t
              )) done);
              ignore (i := HxInt.add (!i) 1);
              raise (HxRuntime.Hx_continue)
            )
          )
        )
      )
    )) else ());
    ignore (HxArray.push out a);
    i := HxInt.add (!i) 1
  )) with
    | HxRuntime.Hx_continue -> () done with
    | HxRuntime.Hx_break -> ());
  let tempResult = ref (Obj.magic (HxRuntime.hx_null) : string HxArray.t) in (
    ignore (if !sawHxml then let __assign_66 = Obj.magic (Obj.magic out) in (
      tempResult := __assign_66;
      __assign_66
    ) else let __assign_67 = Obj.magic (Obj.magic args) in (
      tempResult := __assign_67;
      __assign_67
    ));
    !tempResult
  )
) in Obj.magic __fallback_result_69 with
  | HxRuntime.Hx_return __ret_68 -> Obj.obj __ret_68

let stage1args_parse = fun args permissive -> let permissive = if Obj.repr permissive == HxRuntime.hx_null then false else permissive in try let __fallback_result_31 = let expanded = Obj.magic (stage1args_expandHxmlArgs (Obj.magic args)) in (
  ignore (if expanded == Obj.magic (HxRuntime.hx_null) then raise (HxRuntime.Hx_return (Obj.repr (Obj.magic (Obj.magic (HxRuntime.hx_null))))) else ());
  let classPaths2 = Obj.magic (HxArray.create ()) in let main2 = ref ("" : string) in let noOutput2 = ref false in let roots2 = Obj.magic (HxArray.create ()) in let defines2 = Obj.magic (HxArray.create ()) in let libs2 = Obj.magic (HxArray.create ()) in let macros2 = Obj.magic (HxArray.create ()) in let resourceSpecs2 = Obj.magic (HxArray.create ()) in let cmdCommands2 = Obj.magic (HxArray.create ()) in let displayRequest2 = ref (Obj.magic (HxRuntime.hx_null) : string) in let cwd2 = ref ("." : string) in let stdRoot = ref ("" : string) in let hadCmd2 = ref false in let i = ref 0 in (
    ignore (try while !i < HxArray.length expanded do try ignore (let a = (HxArray.get (Obj.magic expanded) (!i) : string) in match a with
      | "--" -> ignore ((
        ignore (print_endline "hxhx(stage1): unexpected '--' separator");
        raise (HxRuntime.Hx_return (Obj.repr (Obj.magic (HxRuntime.hx_null))))
      ))
      | "--class-path" | "-cp" | "-p" -> ignore ((
        ignore (if HxInt.add (!i) 1 >= HxArray.length expanded then ignore ((
          ignore (print_endline ("hxhx(stage1): missing value after " ^ HxString.toStdString a));
          raise (HxRuntime.Hx_return (Obj.repr (Obj.magic (HxRuntime.hx_null))))
        )) else ());
        ignore (HxArray.push classPaths2 (HxArray.get (Obj.magic expanded) (HxInt.add (!i) 1)));
        i := HxInt.add (!i) 2
      ))
      | "--cmd" -> ignore (if permissive then ignore ((
        ignore (if HxInt.add (!i) 1 >= HxArray.length expanded then ignore ((
          ignore (print_endline "hxhx(stage1): missing value after --cmd");
          raise (HxRuntime.Hx_return (Obj.repr (Obj.magic (HxRuntime.hx_null))))
        )) else ());
        ignore (let __assign_19 = true in (
          hadCmd2 := __assign_19;
          __assign_19
        ));
        ignore (HxArray.push cmdCommands2 (HxArray.get (Obj.magic expanded) (HxInt.add (!i) 1)));
        i := HxInt.add (!i) 2
      )) else ignore ((
        ignore (if StringTools.startsWith (a : string) ("-" : string) then ignore ((
          ignore (if permissive then ignore ((
            ignore (print_endline ("hxhx(stage1): ignoring unsupported flag in permissive mode: " ^ HxString.toStdString a));
            ignore (i := HxInt.add (!i) 1);
            raise (HxRuntime.Hx_continue)
          )) else ());
          ignore (print_endline ("hxhx(stage1): unsupported flag: " ^ HxString.toStdString a));
          raise (HxRuntime.Hx_return (Obj.repr (Obj.magic (HxRuntime.hx_null))))
        )) else ());
        ignore (if permissive then ignore ((
          ignore (HxArray.push roots2 a);
          ignore (i := HxInt.add (!i) 1);
          raise (HxRuntime.Hx_continue)
        )) else ());
        ignore (print_endline ("hxhx(stage1): unsupported argument: " ^ HxString.toStdString a));
        raise (HxRuntime.Hx_return (Obj.repr (Obj.magic (HxRuntime.hx_null))))
      )))
      | "--cwd" | "-C" -> ignore ((
        ignore (if HxInt.add (!i) 1 >= HxArray.length expanded then ignore ((
          ignore (print_endline ("hxhx(stage1): missing value after " ^ HxString.toStdString a));
          raise (HxRuntime.Hx_return (Obj.repr (Obj.magic (HxRuntime.hx_null))))
        )) else ());
        ignore (let __assign_20 = (HxArray.get (Obj.magic expanded) (HxInt.add (!i) 1) : string) in (
          cwd2 := __assign_20;
          __assign_20
        ));
        i := HxInt.add (!i) 2
      ))
      | "--debug" -> ignore (if permissive then ignore ((
        ignore (HxArray.push defines2 "debug=1");
        i := HxInt.add (!i) 1
      )) else ignore ((
        ignore (if StringTools.startsWith (a : string) ("-" : string) then ignore ((
          ignore (if permissive then ignore ((
            ignore (print_endline ("hxhx(stage1): ignoring unsupported flag in permissive mode: " ^ HxString.toStdString a));
            ignore (i := HxInt.add (!i) 1);
            raise (HxRuntime.Hx_continue)
          )) else ());
          ignore (print_endline ("hxhx(stage1): unsupported flag: " ^ HxString.toStdString a));
          raise (HxRuntime.Hx_return (Obj.repr (Obj.magic (HxRuntime.hx_null))))
        )) else ());
        ignore (if permissive then ignore ((
          ignore (HxArray.push roots2 a);
          ignore (i := HxInt.add (!i) 1);
          raise (HxRuntime.Hx_continue)
        )) else ());
        ignore (print_endline ("hxhx(stage1): unsupported argument: " ^ HxString.toStdString a));
        raise (HxRuntime.Hx_return (Obj.repr (Obj.magic (HxRuntime.hx_null))))
      )))
      | "--display" -> ignore (if permissive then ignore ((
        ignore (if HxInt.add (!i) 1 >= HxArray.length expanded then ignore ((
          ignore (print_endline "hxhx(stage1): missing value after --display");
          raise (HxRuntime.Hx_return (Obj.repr (Obj.magic (HxRuntime.hx_null))))
        )) else ());
        ignore (let __assign_21 = Obj.magic (HxArray.get (Obj.magic expanded) (HxInt.add (!i) 1) : string) in (
          displayRequest2 := __assign_21;
          __assign_21
        ));
        ignore (HxArray.push defines2 "display=1");
        i := HxInt.add (!i) 2
      )) else ignore ((
        ignore (if StringTools.startsWith (a : string) ("-" : string) then ignore ((
          ignore (if permissive then ignore ((
            ignore (print_endline ("hxhx(stage1): ignoring unsupported flag in permissive mode: " ^ HxString.toStdString a));
            ignore (i := HxInt.add (!i) 1);
            raise (HxRuntime.Hx_continue)
          )) else ());
          ignore (print_endline ("hxhx(stage1): unsupported flag: " ^ HxString.toStdString a));
          raise (HxRuntime.Hx_return (Obj.repr (Obj.magic (HxRuntime.hx_null))))
        )) else ());
        ignore (if permissive then ignore ((
          ignore (HxArray.push roots2 a);
          ignore (i := HxInt.add (!i) 1);
          raise (HxRuntime.Hx_continue)
        )) else ());
        ignore (print_endline ("hxhx(stage1): unsupported argument: " ^ HxString.toStdString a));
        raise (HxRuntime.Hx_return (Obj.repr (Obj.magic (HxRuntime.hx_null))))
      )))
      | "--interp" -> ignore (if permissive then ignore ((
        ignore (HxArray.push defines2 "interp=1");
        i := HxInt.add (!i) 1
      )) else ignore ((
        ignore (if StringTools.startsWith (a : string) ("-" : string) then ignore ((
          ignore (if permissive then ignore ((
            ignore (print_endline ("hxhx(stage1): ignoring unsupported flag in permissive mode: " ^ HxString.toStdString a));
            ignore (i := HxInt.add (!i) 1);
            raise (HxRuntime.Hx_continue)
          )) else ());
          ignore (print_endline ("hxhx(stage1): unsupported flag: " ^ HxString.toStdString a));
          raise (HxRuntime.Hx_return (Obj.repr (Obj.magic (HxRuntime.hx_null))))
        )) else ());
        ignore (if permissive then ignore ((
          ignore (HxArray.push roots2 a);
          ignore (i := HxInt.add (!i) 1);
          raise (HxRuntime.Hx_continue)
        )) else ());
        ignore (print_endline ("hxhx(stage1): unsupported argument: " ^ HxString.toStdString a));
        raise (HxRuntime.Hx_return (Obj.repr (Obj.magic (HxRuntime.hx_null))))
      )))
      | "--library" -> ignore ((
        ignore (if HxInt.add (!i) 1 >= HxArray.length expanded then ignore ((
          ignore (print_endline "hxhx(stage1): missing value after --library");
          raise (HxRuntime.Hx_return (Obj.repr (Obj.magic (HxRuntime.hx_null))))
        )) else ());
        ignore (HxArray.push libs2 (HxArray.get (Obj.magic expanded) (HxInt.add (!i) 1)));
        i := HxInt.add (!i) 2
      ))
      | "--macro" -> ignore ((
        ignore (if HxInt.add (!i) 1 >= HxArray.length expanded then ignore ((
          ignore (print_endline "hxhx(stage1): missing value after --macro");
          raise (HxRuntime.Hx_return (Obj.repr (Obj.magic (HxRuntime.hx_null))))
        )) else ());
        ignore (HxArray.push macros2 (HxArray.get (Obj.magic expanded) (HxInt.add (!i) 1)));
        i := HxInt.add (!i) 2
      ))
      | "--main" | "-main" -> ignore ((
        ignore (if HxInt.add (!i) 1 >= HxArray.length expanded then ignore ((
          ignore (print_endline "hxhx(stage1): missing value after -main");
          raise (HxRuntime.Hx_return (Obj.repr (Obj.magic (HxRuntime.hx_null))))
        )) else ());
        ignore (let __assign_22 = (HxArray.get (Obj.magic expanded) (HxInt.add (!i) 1) : string) in (
          main2 := __assign_22;
          __assign_22
        ));
        i := HxInt.add (!i) 2
      ))
      | "--no-output" -> ignore ((
        ignore (let __assign_23 = true in (
          noOutput2 := __assign_23;
          __assign_23
        ));
        i := HxInt.add (!i) 1
      ))
      | "--resource" -> ignore (if permissive then ignore ((
        ignore (if HxInt.add (!i) 1 >= HxArray.length expanded then ignore ((
          ignore (print_endline "hxhx(stage1): missing value after --resource");
          raise (HxRuntime.Hx_return (Obj.repr (Obj.magic (HxRuntime.hx_null))))
        )) else ());
        ignore (HxArray.push resourceSpecs2 (HxArray.get (Obj.magic expanded) (HxInt.add (!i) 1)));
        i := HxInt.add (!i) 2
      )) else ignore ((
        ignore (if StringTools.startsWith (a : string) ("-" : string) then ignore ((
          ignore (if permissive then ignore ((
            ignore (print_endline ("hxhx(stage1): ignoring unsupported flag in permissive mode: " ^ HxString.toStdString a));
            ignore (i := HxInt.add (!i) 1);
            raise (HxRuntime.Hx_continue)
          )) else ());
          ignore (print_endline ("hxhx(stage1): unsupported flag: " ^ HxString.toStdString a));
          raise (HxRuntime.Hx_return (Obj.repr (Obj.magic (HxRuntime.hx_null))))
        )) else ());
        ignore (if permissive then ignore ((
          ignore (HxArray.push roots2 a);
          ignore (i := HxInt.add (!i) 1);
          raise (HxRuntime.Hx_continue)
        )) else ());
        ignore (print_endline ("hxhx(stage1): unsupported argument: " ^ HxString.toStdString a));
        raise (HxRuntime.Hx_return (Obj.repr (Obj.magic (HxRuntime.hx_null))))
      )))
      | "--std" -> ignore ((
        ignore (if HxInt.add (!i) 1 >= HxArray.length expanded then ignore ((
          ignore (print_endline "hxhx(stage1): missing value after --std");
          raise (HxRuntime.Hx_return (Obj.repr (Obj.magic (HxRuntime.hx_null))))
        )) else ());
        ignore (let __assign_24 = (HxArray.get (Obj.magic expanded) (HxInt.add (!i) 1) : string) in (
          stdRoot := __assign_24;
          __assign_24
        ));
        i := HxInt.add (!i) 2
      ))
      | "--display-details" | "--times" -> ignore (if permissive then ignore (i := HxInt.add (!i) 1) else ignore ((
        ignore (if StringTools.startsWith (a : string) ("-" : string) then ignore ((
          ignore (if permissive then ignore ((
            ignore (print_endline ("hxhx(stage1): ignoring unsupported flag in permissive mode: " ^ HxString.toStdString a));
            ignore (i := HxInt.add (!i) 1);
            raise (HxRuntime.Hx_continue)
          )) else ());
          ignore (print_endline ("hxhx(stage1): unsupported flag: " ^ HxString.toStdString a));
          raise (HxRuntime.Hx_return (Obj.repr (Obj.magic (HxRuntime.hx_null))))
        )) else ());
        ignore (if permissive then ignore ((
          ignore (HxArray.push roots2 a);
          ignore (i := HxInt.add (!i) 1);
          raise (HxRuntime.Hx_continue)
        )) else ());
        ignore (print_endline ("hxhx(stage1): unsupported argument: " ^ HxString.toStdString a));
        raise (HxRuntime.Hx_return (Obj.repr (Obj.magic (HxRuntime.hx_null))))
      )))
      | "--connect" | "--wait" -> ignore (if permissive then ignore ((
        ignore (if HxInt.add (!i) 1 >= HxArray.length expanded then ignore ((
          ignore (print_endline ("hxhx(stage1): missing value after " ^ HxString.toStdString a));
          raise (HxRuntime.Hx_return (Obj.repr (Obj.magic (HxRuntime.hx_null))))
        )) else ());
        i := HxInt.add (!i) 2
      )) else ignore ((
        ignore (if StringTools.startsWith (a : string) ("-" : string) then ignore ((
          ignore (if permissive then ignore ((
            ignore (print_endline ("hxhx(stage1): ignoring unsupported flag in permissive mode: " ^ HxString.toStdString a));
            ignore (i := HxInt.add (!i) 1);
            raise (HxRuntime.Hx_continue)
          )) else ());
          ignore (print_endline ("hxhx(stage1): unsupported flag: " ^ HxString.toStdString a));
          raise (HxRuntime.Hx_return (Obj.repr (Obj.magic (HxRuntime.hx_null))))
        )) else ());
        ignore (if permissive then ignore ((
          ignore (HxArray.push roots2 a);
          ignore (i := HxInt.add (!i) 1);
          raise (HxRuntime.Hx_continue)
        )) else ());
        ignore (print_endline ("hxhx(stage1): unsupported argument: " ^ HxString.toStdString a));
        raise (HxRuntime.Hx_return (Obj.repr (Obj.magic (HxRuntime.hx_null))))
      )))
      | "--as3" | "--cpp" | "--cs" | "--hl" | "--java" | "--js" | "--jvm" | "--lua" | "--neko" | "--php" | "--python" | "--swf" | "--xml" | "-as3" | "-cpp" | "-cs" | "-hl" | "-java" | "-js" | "-jvm" | "-lua" | "-neko" | "-php" | "-python" | "-swf" | "-xml" -> ignore (if permissive then ignore ((
        ignore (if HxInt.add (!i) 1 >= HxArray.length expanded then ignore ((
          ignore (print_endline ("hxhx(stage1): missing value after " ^ HxString.toStdString a));
          raise (HxRuntime.Hx_return (Obj.repr (Obj.magic (HxRuntime.hx_null))))
        )) else ());
        i := HxInt.add (!i) 2
      )) else ignore ((
        ignore (if StringTools.startsWith (a : string) ("-" : string) then ignore ((
          ignore (if permissive then ignore ((
            ignore (print_endline ("hxhx(stage1): ignoring unsupported flag in permissive mode: " ^ HxString.toStdString a));
            ignore (i := HxInt.add (!i) 1);
            raise (HxRuntime.Hx_continue)
          )) else ());
          ignore (print_endline ("hxhx(stage1): unsupported flag: " ^ HxString.toStdString a));
          raise (HxRuntime.Hx_return (Obj.repr (Obj.magic (HxRuntime.hx_null))))
        )) else ());
        ignore (if permissive then ignore ((
          ignore (HxArray.push roots2 a);
          ignore (i := HxInt.add (!i) 1);
          raise (HxRuntime.Hx_continue)
        )) else ());
        ignore (print_endline ("hxhx(stage1): unsupported argument: " ^ HxString.toStdString a));
        raise (HxRuntime.Hx_return (Obj.repr (Obj.magic (HxRuntime.hx_null))))
      )))
      | "-D" -> ignore ((
        ignore (if HxInt.add (!i) 1 >= HxArray.length expanded then ignore ((
          ignore (print_endline "hxhx(stage1): missing value after -D");
          raise (HxRuntime.Hx_return (Obj.repr (Obj.magic (HxRuntime.hx_null))))
        )) else ());
        ignore (HxArray.push defines2 (HxArray.get (Obj.magic expanded) (HxInt.add (!i) 1)));
        i := HxInt.add (!i) 2
      ))
      | "-cmd" -> ignore (if permissive then ignore ((
        ignore (if HxInt.add (!i) 1 >= HxArray.length expanded then ignore ((
          ignore (print_endline "hxhx(stage1): missing value after -cmd");
          raise (HxRuntime.Hx_return (Obj.repr (Obj.magic (HxRuntime.hx_null))))
        )) else ());
        ignore (let __assign_25 = true in (
          hadCmd2 := __assign_25;
          __assign_25
        ));
        ignore (HxArray.push cmdCommands2 (HxArray.get (Obj.magic expanded) (HxInt.add (!i) 1)));
        i := HxInt.add (!i) 2
      )) else ignore ((
        ignore (if StringTools.startsWith (a : string) ("-" : string) then ignore ((
          ignore (if permissive then ignore ((
            ignore (print_endline ("hxhx(stage1): ignoring unsupported flag in permissive mode: " ^ HxString.toStdString a));
            ignore (i := HxInt.add (!i) 1);
            raise (HxRuntime.Hx_continue)
          )) else ());
          ignore (print_endline ("hxhx(stage1): unsupported flag: " ^ HxString.toStdString a));
          raise (HxRuntime.Hx_return (Obj.repr (Obj.magic (HxRuntime.hx_null))))
        )) else ());
        ignore (if permissive then ignore ((
          ignore (HxArray.push roots2 a);
          ignore (i := HxInt.add (!i) 1);
          raise (HxRuntime.Hx_continue)
        )) else ());
        ignore (print_endline ("hxhx(stage1): unsupported argument: " ^ HxString.toStdString a));
        raise (HxRuntime.Hx_return (Obj.repr (Obj.magic (HxRuntime.hx_null))))
      )))
      | "--dce" | "-dce" -> ignore (if permissive then ignore ((
        ignore (if HxInt.add (!i) 1 >= HxArray.length expanded then ignore ((
          ignore (print_endline ("hxhx(stage1): missing value after " ^ HxString.toStdString a));
          raise (HxRuntime.Hx_return (Obj.repr (Obj.magic (HxRuntime.hx_null))))
        )) else ());
        ignore (HxArray.push defines2 ("dce=" ^ HxString.toStdString (HxArray.get (Obj.magic expanded) (HxInt.add (!i) 1))));
        i := HxInt.add (!i) 2
      )) else ignore ((
        ignore (if StringTools.startsWith (a : string) ("-" : string) then ignore ((
          ignore (if permissive then ignore ((
            ignore (print_endline ("hxhx(stage1): ignoring unsupported flag in permissive mode: " ^ HxString.toStdString a));
            ignore (i := HxInt.add (!i) 1);
            raise (HxRuntime.Hx_continue)
          )) else ());
          ignore (print_endline ("hxhx(stage1): unsupported flag: " ^ HxString.toStdString a));
          raise (HxRuntime.Hx_return (Obj.repr (Obj.magic (HxRuntime.hx_null))))
        )) else ());
        ignore (if permissive then ignore ((
          ignore (HxArray.push roots2 a);
          ignore (i := HxInt.add (!i) 1);
          raise (HxRuntime.Hx_continue)
        )) else ());
        ignore (print_endline ("hxhx(stage1): unsupported argument: " ^ HxString.toStdString a));
        raise (HxRuntime.Hx_return (Obj.repr (Obj.magic (HxRuntime.hx_null))))
      )))
      | "--java-lib" | "-java-lib" -> ignore (if permissive then ignore ((
        ignore (if HxInt.add (!i) 1 >= HxArray.length expanded then ignore ((
          ignore (print_endline ("hxhx(stage1): missing value after " ^ HxString.toStdString a));
          raise (HxRuntime.Hx_return (Obj.repr (Obj.magic (HxRuntime.hx_null))))
        )) else ());
        ignore (if HxArray.indexOf defines2 "hxhx_java_lib=1" 0 = -1 then ignore (HxArray.push defines2 "hxhx_java_lib=1") else ());
        i := HxInt.add (!i) 2
      )) else ignore ((
        ignore (if StringTools.startsWith (a : string) ("-" : string) then ignore ((
          ignore (if permissive then ignore ((
            ignore (print_endline ("hxhx(stage1): ignoring unsupported flag in permissive mode: " ^ HxString.toStdString a));
            ignore (i := HxInt.add (!i) 1);
            raise (HxRuntime.Hx_continue)
          )) else ());
          ignore (print_endline ("hxhx(stage1): unsupported flag: " ^ HxString.toStdString a));
          raise (HxRuntime.Hx_return (Obj.repr (Obj.magic (HxRuntime.hx_null))))
        )) else ());
        ignore (if permissive then ignore ((
          ignore (HxArray.push roots2 a);
          ignore (i := HxInt.add (!i) 1);
          raise (HxRuntime.Hx_continue)
        )) else ());
        ignore (print_endline ("hxhx(stage1): unsupported argument: " ^ HxString.toStdString a));
        raise (HxRuntime.Hx_return (Obj.repr (Obj.magic (HxRuntime.hx_null))))
      )))
      | "-lib" -> ignore ((
        ignore (if HxInt.add (!i) 1 >= HxArray.length expanded then ignore ((
          ignore (print_endline "hxhx(stage1): missing value after -lib");
          raise (HxRuntime.Hx_return (Obj.repr (Obj.magic (HxRuntime.hx_null))))
        )) else ());
        ignore (HxArray.push libs2 (HxArray.get (Obj.magic expanded) (HxInt.add (!i) 1)));
        i := HxInt.add (!i) 2
      ))
      | "--net-lib" | "-net-lib" -> ignore (if permissive then ignore ((
        ignore (if HxInt.add (!i) 1 >= HxArray.length expanded then ignore ((
          ignore (print_endline ("hxhx(stage1): missing value after " ^ HxString.toStdString a));
          raise (HxRuntime.Hx_return (Obj.repr (Obj.magic (HxRuntime.hx_null))))
        )) else ());
        ignore (if HxArray.indexOf defines2 "hxhx_net_lib=1" 0 = -1 then ignore (HxArray.push defines2 "hxhx_net_lib=1") else ());
        i := HxInt.add (!i) 2
      )) else ignore ((
        ignore (if StringTools.startsWith (a : string) ("-" : string) then ignore ((
          ignore (if permissive then ignore ((
            ignore (print_endline ("hxhx(stage1): ignoring unsupported flag in permissive mode: " ^ HxString.toStdString a));
            ignore (i := HxInt.add (!i) 1);
            raise (HxRuntime.Hx_continue)
          )) else ());
          ignore (print_endline ("hxhx(stage1): unsupported flag: " ^ HxString.toStdString a));
          raise (HxRuntime.Hx_return (Obj.repr (Obj.magic (HxRuntime.hx_null))))
        )) else ());
        ignore (if permissive then ignore ((
          ignore (HxArray.push roots2 a);
          ignore (i := HxInt.add (!i) 1);
          raise (HxRuntime.Hx_continue)
        )) else ());
        ignore (print_endline ("hxhx(stage1): unsupported argument: " ^ HxString.toStdString a));
        raise (HxRuntime.Hx_return (Obj.repr (Obj.magic (HxRuntime.hx_null))))
      )))
      | "-swf-lib" -> ignore (if permissive then ignore ((
        ignore (if HxInt.add (!i) 1 >= HxArray.length expanded then ignore ((
          ignore (print_endline "hxhx(stage1): missing value after -swf-lib");
          raise (HxRuntime.Hx_return (Obj.repr (Obj.magic (HxRuntime.hx_null))))
        )) else ());
        i := HxInt.add (!i) 2
      )) else ignore ((
        ignore (if StringTools.startsWith (a : string) ("-" : string) then ignore ((
          ignore (if permissive then ignore ((
            ignore (print_endline ("hxhx(stage1): ignoring unsupported flag in permissive mode: " ^ HxString.toStdString a));
            ignore (i := HxInt.add (!i) 1);
            raise (HxRuntime.Hx_continue)
          )) else ());
          ignore (print_endline ("hxhx(stage1): unsupported flag: " ^ HxString.toStdString a));
          raise (HxRuntime.Hx_return (Obj.repr (Obj.magic (HxRuntime.hx_null))))
        )) else ());
        ignore (if permissive then ignore ((
          ignore (HxArray.push roots2 a);
          ignore (i := HxInt.add (!i) 1);
          raise (HxRuntime.Hx_continue)
        )) else ());
        ignore (print_endline ("hxhx(stage1): unsupported argument: " ^ HxString.toStdString a));
        raise (HxRuntime.Hx_return (Obj.repr (Obj.magic (HxRuntime.hx_null))))
      )))
      | "--run" | "-x" -> ignore (if permissive then ignore ((
        ignore (if HxInt.add (!i) 1 >= HxArray.length expanded then ignore ((
          ignore (print_endline ("hxhx(stage1): missing value after " ^ HxString.toStdString a));
          raise (HxRuntime.Hx_return (Obj.repr (Obj.magic (HxRuntime.hx_null))))
        )) else ());
        ignore (let __assign_26 = (HxArray.get (Obj.magic expanded) (HxInt.add (!i) 1) : string) in (
          main2 := __assign_26;
          __assign_26
        ));
        ignore (i := HxInt.add (!i) 2);
        while !i < HxArray.length expanded && not (StringTools.startsWith (HxArray.get (Obj.magic expanded) (!i) : string) ("-" : string)) do ignore (let __old_27 = !i in let __new_28 = HxInt.add __old_27 1 in (
          ignore (i := __new_28);
          __old_27
        )) done
      )) else ignore ((
        ignore (if StringTools.startsWith (a : string) ("-" : string) then ignore ((
          ignore (if permissive then ignore ((
            ignore (print_endline ("hxhx(stage1): ignoring unsupported flag in permissive mode: " ^ HxString.toStdString a));
            ignore (i := HxInt.add (!i) 1);
            raise (HxRuntime.Hx_continue)
          )) else ());
          ignore (print_endline ("hxhx(stage1): unsupported flag: " ^ HxString.toStdString a));
          raise (HxRuntime.Hx_return (Obj.repr (Obj.magic (HxRuntime.hx_null))))
        )) else ());
        ignore (if permissive then ignore ((
          ignore (HxArray.push roots2 a);
          ignore (i := HxInt.add (!i) 1);
          raise (HxRuntime.Hx_continue)
        )) else ());
        ignore (print_endline ("hxhx(stage1): unsupported argument: " ^ HxString.toStdString a));
        raise (HxRuntime.Hx_return (Obj.repr (Obj.magic (HxRuntime.hx_null))))
      )))
      | _ -> ignore ((
        ignore (if StringTools.startsWith (a : string) ("-" : string) then ignore ((
          ignore (if permissive then ignore ((
            ignore (print_endline ("hxhx(stage1): ignoring unsupported flag in permissive mode: " ^ HxString.toStdString a));
            ignore (i := HxInt.add (!i) 1);
            raise (HxRuntime.Hx_continue)
          )) else ());
          ignore (print_endline ("hxhx(stage1): unsupported flag: " ^ HxString.toStdString a));
          raise (HxRuntime.Hx_return (Obj.repr (Obj.magic (HxRuntime.hx_null))))
        )) else ());
        ignore (if permissive then ignore ((
          ignore (HxArray.push roots2 a);
          ignore (i := HxInt.add (!i) 1);
          raise (HxRuntime.Hx_continue)
        )) else ());
        ignore (print_endline ("hxhx(stage1): unsupported argument: " ^ HxString.toStdString a));
        raise (HxRuntime.Hx_return (Obj.repr (Obj.magic (HxRuntime.hx_null))))
      ))) with
      | HxRuntime.Hx_continue -> () done with
      | HxRuntime.Hx_break -> ());
    ignore (if HxArray.length classPaths2 = 0 then ignore (HxArray.push classPaths2 ".") else ());
    ignore (if !stdRoot == Obj.magic (HxRuntime.hx_null) || HxString.length (!stdRoot) = 0 then ignore (let __assign_29 = (stage1args_inferStdRoot (!cwd2 : string) : string) in (
      stdRoot := __assign_29;
      __assign_29
    )) else ());
    ignore (if !stdRoot != Obj.magic (HxRuntime.hx_null) && HxString.length (!stdRoot) > 0 && HxArray.indexOf classPaths2 (!stdRoot) 0 = -1 then ignore (HxArray.push classPaths2 (!stdRoot)) else ());
    stage1args_create (Obj.magic classPaths2) (!main2 : string) (!noOutput2) (Obj.magic roots2) (Obj.magic defines2) (Obj.magic libs2) (Obj.magic macros2) (Obj.magic resourceSpecs2) (!displayRequest2 : string) (!cwd2 : string) (!hadCmd2) (Obj.magic cmdCommands2)
  )
) in Obj.magic __fallback_result_31 with
  | HxRuntime.Hx_return __ret_30 -> Obj.obj __ret_30

let stage1args_getClassPaths = fun a -> (Obj.magic a : stage1args_t).classPaths

let stage1args_getMain = fun a -> (Obj.magic a : stage1args_t).main

let stage1args_getNoOutput = fun a -> (Obj.magic a : stage1args_t).noOutput

let stage1args_getRoots = fun a -> (Obj.magic a : stage1args_t).roots

let stage1args_getDefines = fun a -> (Obj.magic a : stage1args_t).defines

let stage1args_getLibs = fun a -> (Obj.magic a : stage1args_t).libs

let stage1args_getMacros = fun a -> (Obj.magic a : stage1args_t).macros

let stage1args_getResourceSpecs = fun a -> (Obj.magic a : stage1args_t).resourceSpecs

let stage1args_getDisplayRequest = fun a -> (Obj.magic a : stage1args_t).displayRequest

let stage1args_getCwd = fun a -> (Obj.magic a : stage1args_t).cwd

let stage1args_getHadCmd = fun a -> (Obj.magic a : stage1args_t).hadCmd

let stage1args_getCmdCommands = fun a -> (Obj.magic a : stage1args_t).cmdCommands

(* Generated by reflaxe.ocaml (WIP) *)
(* Haxe type: hxhx.Stage1Resolver *)

let __reflaxe_ocaml__ = ()

type stage1resolver_t = { __hx_type : Obj.t }

let stage1resolver_create = fun () -> let self = ({ __hx_type = HxType.class_ "hxhx.Stage1Resolver" } : stage1resolver_t) in (
  ignore ();
  self
)

let stage1resolver___empty = fun () -> ({ __hx_type = HxType.class_ "hxhx.Stage1Resolver" } : stage1resolver_t)

let stage1resolver_normalizeSep = fun s -> let tempResult = ref ("" : string) in (
  ignore (if s == Obj.magic (HxRuntime.hx_null) then let __assign_1 = ("" : string) in (
    tempResult := __assign_1;
    __assign_1
  ) else let __assign_2 = (StringTools.replace (s : string) ("\\" : string) ("/" : string) : string) in (
    tempResult := __assign_2;
    __assign_2
  ));
  !tempResult
)

let stage1resolver_resolveClassPath = fun cwd cp -> let tempString = ref ("" : string) in (
  ignore (if cp == Obj.magic (HxRuntime.hx_null) then let __assign_3 = ("" : string) in (
    tempString := __assign_3;
    __assign_3
  ) else let __assign_4 = (StringTools.replace (cp : string) ("\\" : string) ("/" : string) : string) in (
    tempString := __assign_4;
    __assign_4
  ));
  let tempResult = ref ("" : string) in (
    ignore (if Haxe_io_Path.isAbsolute (!tempString : string) then let __assign_5 = (!tempString : string) in (
      tempResult := __assign_5;
      __assign_5
    ) else let __assign_6 = (Haxe_io_Path.normalize (Haxe_io_Path.join (Obj.magic (let __arr_7 = HxArray.create () in (
      ignore (HxArray.push __arr_7 cwd);
      ignore (HxArray.push __arr_7 (!tempString));
      __arr_7
    ))) : string) : string) in (
      tempResult := __assign_6;
      __assign_6
    ));
    !tempResult
  )
)

let stage1resolver_resolveMain = fun classPaths main cwd -> try let __fallback_result_16 = let parts = Obj.magic (HxString.split main ".") in (
  ignore (if HxArray.length parts = 0 then ignore ((
    ignore (print_endline ("hxhx(stage1): invalid -main: " ^ HxString.toStdString main));
    raise (HxRuntime.Hx_return (Obj.repr (Obj.magic (HxRuntime.hx_null))))
  )) else ());
  let className = (HxArray.get (Obj.magic parts) (HxInt.sub (HxArray.length parts) 1) : string) in let pkgParts = Obj.magic (HxArray.slice parts 0 (HxInt.sub (HxArray.length parts) 1)) in let pkg = (HxArray.join pkgParts "." (fun x -> x) : string) in (
    ignore (let _g = ref 0 in while !_g < HxArray.length classPaths do ignore (let cp = (HxArray.get (Obj.magic classPaths) (!_g) : string) in (
      ignore (let __old_8 = !_g in let __new_9 = HxInt.add __old_8 1 in (
        ignore (_g := __new_9);
        __new_9
      ));
      let base = (stage1resolver_resolveClassPath (cwd : string) (cp : string) : string) in let candidate = (Haxe_io_Path.join (Obj.magic (HxArray.concat (HxArray.concat (let __arr_10 = HxArray.create () in (
        ignore (HxArray.push __arr_10 base);
        __arr_10
      )) pkgParts) (let __arr_11 = HxArray.create () in (
        ignore (HxArray.push __arr_11 (HxString.toStdString className ^ ".hx"));
        __arr_11
      )))) : string) in if HxFileSystem.exists candidate && not (HxFileSystem.isDirectory candidate) then raise (HxRuntime.Hx_return (Obj.repr (let __anon_12 = HxAnon.create () in (
        ignore (HxAnon.set __anon_12 "path" (Obj.repr candidate));
        ignore (HxAnon.set __anon_12 "packagePath" (Obj.repr pkg));
        ignore (HxAnon.set __anon_12 "className" (Obj.repr className));
        __anon_12
      )))) else ()
    )) done);
    ignore (print_endline ("hxhx(stage1): could not find main module for -main " ^ HxString.toStdString main));
    ignore (let _g = ref 0 in while !_g < HxArray.length classPaths do ignore (let cp = (HxArray.get (Obj.magic classPaths) (!_g) : string) in (
      ignore (let __old_13 = !_g in let __new_14 = HxInt.add __old_13 1 in (
        ignore (_g := __new_14);
        __new_14
      ));
      print_endline ("  searched: " ^ HxString.toStdString (stage1resolver_resolveClassPath (cwd : string) (cp : string)))
    )) done);
    Obj.magic (HxRuntime.hx_null)
  )
) in Obj.magic __fallback_result_16 with
  | HxRuntime.Hx_return __ret_15 -> Obj.magic __ret_15

let stage1resolver_resolveModule = fun classPaths modulePath cwd -> try let __fallback_result_26 = let parts = Obj.magic (HxString.split modulePath ".") in (
  ignore (if HxArray.length parts = 0 then raise (HxRuntime.Hx_return (Obj.repr (HxRuntime.hx_null))) else ());
  let leafName = (HxArray.get (Obj.magic parts) (HxInt.sub (HxArray.length parts) 1) : string) in let _g = ref 0 in (
    ignore (while !_g < HxArray.length classPaths do ignore (let cp = (HxArray.get (Obj.magic classPaths) (!_g) : string) in (
      ignore (let __old_17 = !_g in let __new_18 = HxInt.add __old_17 1 in (
        ignore (_g := __new_18);
        __new_18
      ));
      let base = (stage1resolver_resolveClassPath (cwd : string) (cp : string) : string) in (
        ignore (let pkgParts = Obj.magic (HxArray.slice parts 0 (HxInt.sub (HxArray.length parts) 1)) in let pkg = (HxArray.join pkgParts "." (fun x -> x) : string) in let candidate = (Haxe_io_Path.join (Obj.magic (HxArray.concat (HxArray.concat (let __arr_19 = HxArray.create () in (
          ignore (HxArray.push __arr_19 base);
          __arr_19
        )) pkgParts) (let __arr_20 = HxArray.create () in (
          ignore (HxArray.push __arr_20 (HxString.toStdString leafName ^ ".hx"));
          __arr_20
        )))) : string) in if HxFileSystem.exists candidate && not (HxFileSystem.isDirectory candidate) then raise (HxRuntime.Hx_return (Obj.repr (let __anon_21 = HxAnon.create () in (
          ignore (HxAnon.set __anon_21 "path" (Obj.repr candidate));
          ignore (HxAnon.set __anon_21 "packagePath" (Obj.repr pkg));
          ignore (HxAnon.set __anon_21 "className" (Obj.repr leafName));
          __anon_21
        )))) else ());
        if HxArray.length parts >= 2 then ignore (let modName = (HxArray.get (Obj.magic parts) (HxInt.sub (HxArray.length parts) 2) : string) in let pkgParts = Obj.magic (HxArray.slice parts 0 (HxInt.sub (HxArray.length parts) 2)) in let pkg = (HxArray.join pkgParts "." (fun x -> x) : string) in let candidate = (Haxe_io_Path.join (Obj.magic (HxArray.concat (HxArray.concat (let __arr_22 = HxArray.create () in (
          ignore (HxArray.push __arr_22 base);
          __arr_22
        )) pkgParts) (let __arr_23 = HxArray.create () in (
          ignore (HxArray.push __arr_23 (HxString.toStdString modName ^ ".hx"));
          __arr_23
        )))) : string) in if HxFileSystem.exists candidate && not (HxFileSystem.isDirectory candidate) then raise (HxRuntime.Hx_return (Obj.repr (let __anon_24 = HxAnon.create () in (
          ignore (HxAnon.set __anon_24 "path" (Obj.repr candidate));
          ignore (HxAnon.set __anon_24 "packagePath" (Obj.repr pkg));
          ignore (HxAnon.set __anon_24 "className" (Obj.repr modName));
          __anon_24
        )))) else ()) else ()
      )
    )) done);
    Obj.magic (HxRuntime.hx_null)
  )
) in Obj.magic __fallback_result_26 with
  | HxRuntime.Hx_return __ret_25 -> Obj.magic __ret_25

(* Generated by reflaxe.ocaml (WIP) *)
(* Haxe type: hxhx.Stage1Compiler *)

let __reflaxe_ocaml__ = ()

type t = { __hx_type : Obj.t }

let create = fun () -> let self = ({ __hx_type = HxType.class_ "hxhx.Stage1Compiler" } : t) in (
  ignore ();
  self
)

let __empty = fun () -> ({ __hx_type = HxType.class_ "hxhx.Stage1Compiler" } : t)

let error = fun msg -> (
  ignore (print_endline ("hxhx(stage1): " ^ HxString.toStdString msg));
  2
)

let resolveLibraryPaths = fun lib cwd -> let seen = HxMap.create_string () in Obj.obj (HxAnon.get (Hxhx_LibraryResolver.resolve (lib : string) (cwd : string) seen 0) "classPaths")

let formatParseError = fun e -> HxParseError.toString (Obj.magic e) ()

let run = fun args -> try let __fallback_result_53 = let permissive = ref false in let filtered = Obj.magic (HxArray.create ()) in (
  ignore (let _g = ref 0 in try while !_g < HxArray.length args do try ignore (let a = (HxArray.get (Obj.magic args) (!_g) : string) in (
    ignore (let __old_1 = !_g in let __new_2 = HxInt.add __old_1 1 in (
      ignore (_g := __new_2);
      __new_2
    ));
    ignore (if HxString.equals a "--hxhx-permissive" then ignore ((
      ignore (let __assign_3 = true in (
        permissive := __assign_3;
        __assign_3
      ));
      raise (HxRuntime.Hx_continue)
    )) else ());
    HxArray.push filtered a
  )) with
    | HxRuntime.Hx_continue -> () done with
    | HxRuntime.Hx_break -> ());
  let parsed = Obj.magic (stage1args_parse (Obj.magic filtered) (!permissive)) in (
    ignore (if parsed == Obj.magic (HxRuntime.hx_null) then raise (HxRuntime.Hx_return (Obj.repr 2)) else ());
    ignore (if not ((Obj.magic parsed : stage1args_t).noOutput) then raise (HxRuntime.Hx_return (Obj.repr (error ("only --no-output is supported in stage1 bring-up" : string)))) else ());
    ignore (if (Obj.magic parsed : stage1args_t).main == Obj.magic (HxRuntime.hx_null) || HxString.length ((Obj.magic parsed : stage1args_t).main) = 0 then raise (HxRuntime.Hx_return (Obj.repr (error ("missing -main <TypeName>" : string)))) else ());
    let classPaths = Obj.magic (HxArray.copy ((Obj.magic parsed : stage1args_t).classPaths)) in (
      ignore (if !permissive && HxArray.length ((Obj.magic parsed : stage1args_t).libs) > 0 then ignore (let _g = ref 0 in let _g1 = Obj.magic ((Obj.magic parsed : stage1args_t).libs) in while !_g < HxArray.length _g1 do ignore (let lib = (HxArray.get (Obj.magic _g1) (!_g) : string) in (
        ignore (let __old_4 = !_g in let __new_5 = HxInt.add __old_4 1 in (
          ignore (_g := __new_5);
          __new_5
        ));
        try let _g2 = ref 0 in let _g3 = Obj.magic (resolveLibraryPaths (lib : string) ((Obj.magic parsed : stage1args_t).cwd : string)) in while !_g2 < HxArray.length _g3 do ignore (let p = (HxArray.get (Obj.magic _g3) (!_g2) : string) in (
          ignore (let __old_6 = !_g2 in let __new_7 = HxInt.add __old_6 1 in (
            ignore (_g2 := __new_7);
            __new_7
          ));
          HxArray.push classPaths p
        )) done with
          | HxRuntime.Hx_break -> raise (HxRuntime.Hx_break)
          | HxRuntime.Hx_continue -> raise (HxRuntime.Hx_continue)
          | HxRuntime.Hx_return __ret_8 -> raise (HxRuntime.Hx_return __ret_8)
          | HxRuntime.Hx_exception (__exn_v_9, __exn_tags_10) -> if HxRuntime.tags_has __exn_tags_10 "String" then let e = (Obj.obj __exn_v_9 : string) in (
            ignore e;
            raise (HxRuntime.Hx_return (Obj.repr (error ((("failed to resolve -lib " ^ HxString.toStdString lib) ^ ": ") ^ HxString.toStdString e : string))))
          ) else HxRuntime.hx_throw_typed __exn_v_9 __exn_tags_10
          | __exn_11 -> if HxRuntime.tags_has ["OcamlExn"] "String" then let e = (Obj.obj (Obj.repr __exn_11) : string) in (
            ignore e;
            raise (HxRuntime.Hx_return (Obj.repr (error ((("failed to resolve -lib " ^ HxString.toStdString lib) ^ ": ") ^ HxString.toStdString e : string))))
          ) else raise (__exn_11)
      )) done) else ());
      let resolved = stage1resolver_resolveMain (Obj.magic classPaths) ((Obj.magic parsed : stage1args_t).main : string) ((Obj.magic parsed : stage1args_t).cwd : string) in (
        ignore (if resolved == Obj.magic (HxRuntime.hx_null) then raise (HxRuntime.Hx_return (Obj.repr 2)) else ());
        let tempMaybeString = ref (Obj.magic (HxRuntime.hx_null) : string) in (
          ignore (try let path = (Obj.obj (HxAnon.get resolved "path") : string) in let __assign_12 = Obj.magic (HxFile.getContent (path : string) : string) in (
            tempMaybeString := __assign_12;
            __assign_12
          ) with
            | HxRuntime.Hx_break -> raise (HxRuntime.Hx_break)
            | HxRuntime.Hx_continue -> raise (HxRuntime.Hx_continue)
            | HxRuntime.Hx_return __ret_13 -> raise (HxRuntime.Hx_return __ret_13)
            | HxRuntime.Hx_exception (__exn_v_14, __exn_tags_15) -> if HxRuntime.tags_has __exn_tags_15 "haxe.io.Error" then let _hx = (Obj.obj (HxEnum.unbox_or_obj "haxe.io.Error" __exn_v_14) : Haxe_io_Error.error) in (
              ignore _hx;
              let __assign_17 = Obj.magic (Obj.magic (HxRuntime.hx_null)) in (
                tempMaybeString := __assign_17;
                __assign_17
              )
            ) else if HxRuntime.tags_has __exn_tags_15 "String" then let _hx = (Obj.obj __exn_v_14 : string) in (
              ignore _hx;
              let __assign_16 = Obj.magic (Obj.magic (HxRuntime.hx_null)) in (
                tempMaybeString := __assign_16;
                __assign_16
              )
            ) else HxRuntime.hx_throw_typed __exn_v_14 __exn_tags_15
            | __exn_18 -> if HxRuntime.tags_has ["OcamlExn"] "haxe.io.Error" then let _hx = (Obj.obj (HxEnum.unbox_or_obj "haxe.io.Error" (Obj.repr __exn_18)) : Haxe_io_Error.error) in (
              ignore _hx;
              let __assign_20 = Obj.magic (Obj.magic (HxRuntime.hx_null)) in (
                tempMaybeString := __assign_20;
                __assign_20
              )
            ) else if HxRuntime.tags_has ["OcamlExn"] "String" then let _hx = (Obj.obj (Obj.repr __exn_18) : string) in (
              ignore _hx;
              let __assign_19 = Obj.magic (Obj.magic (HxRuntime.hx_null)) in (
                tempMaybeString := __assign_19;
                __assign_19
              )
            ) else raise (__exn_18));
          let source = (!tempMaybeString : string) in (
            ignore (if source == Obj.magic (HxRuntime.hx_null) then raise (HxRuntime.Hx_return (Obj.repr (error ("failed to read: " ^ HxString.toStdString (Obj.obj (HxAnon.get resolved "path")) : string)))) else ());
            let definesMap = Obj.magic (HxDefineMap.fromRawDefines (Obj.magic ((Obj.magic parsed : stage1args_t).defines))) in (
              ignore (HxMap.set_string definesMap "sys" "1");
              ignore (HxMap.set_string definesMap "ocaml" "1");
              let filteredSource = (HxConditionalCompilation.filterSource (source : string) (Obj.magic definesMap) : string) in let tempHxModuleDecl = ref (Obj.magic (HxRuntime.hx_null) : HxModuleDecl.t) in (
                ignore (try let __assign_21 = Obj.magic (ParsedModule.getDecl (Obj.magic (ParserStage.parse (filteredSource : string) (Obj.obj (HxAnon.get resolved "path") : string))) ()) in (
                  tempHxModuleDecl := __assign_21;
                  __assign_21
                ) with
                  | HxRuntime.Hx_break -> raise (HxRuntime.Hx_break)
                  | HxRuntime.Hx_continue -> raise (HxRuntime.Hx_continue)
                  | HxRuntime.Hx_return __ret_22 -> raise (HxRuntime.Hx_return __ret_22)
                  | HxRuntime.Hx_exception (__exn_v_23, __exn_tags_24) -> if HxRuntime.tags_has __exn_tags_24 "HxParseError" then let e = (Obj.obj __exn_v_23 : HxParseError.t) in (
                    ignore e;
                    raise (HxRuntime.Hx_return (Obj.repr (error ("parse failed: " ^ HxString.toStdString (formatParseError (Obj.magic e)) : string))))
                  ) else if HxRuntime.tags_has __exn_tags_24 "String" then let e = (Obj.obj __exn_v_23 : string) in (
                    ignore e;
                    raise (HxRuntime.Hx_return (Obj.repr (error ("parse failed: " ^ HxString.toStdString e : string))))
                  ) else HxRuntime.hx_throw_typed __exn_v_23 __exn_tags_24
                  | __exn_25 -> if HxRuntime.tags_has ["OcamlExn"] "HxParseError" then let e = (Obj.obj (Obj.repr __exn_25) : HxParseError.t) in (
                    ignore e;
                    raise (HxRuntime.Hx_return (Obj.repr (error ("parse failed: " ^ HxString.toStdString (formatParseError (Obj.magic e)) : string))))
                  ) else if HxRuntime.tags_has ["OcamlExn"] "String" then let e = (Obj.obj (Obj.repr __exn_25) : string) in (
                    ignore e;
                    raise (HxRuntime.Hx_return (Obj.repr (error ("parse failed: " ^ HxString.toStdString e : string))))
                  ) else raise (__exn_25));
                let decl = Obj.magic (!tempHxModuleDecl) in let tempLeft = ref ("" : string) in (
                  ignore (let tmp = ((Obj.magic decl : HxModuleDecl.t).packagePath : string) in if tmp != Obj.magic (HxRuntime.hx_null) then let __assign_26 = (tmp : string) in (
                    tempLeft := __assign_26;
                    __assign_26
                  ) else let __assign_27 = ("" : string) in (
                    tempLeft := __assign_27;
                    __assign_27
                  ));
                  ignore (if not (HxString.equals (!tempLeft) (Obj.obj (HxAnon.get resolved "packagePath"))) then ignore (let tempRight = ref ("" : string) in (
                    ignore (let tmp = ((Obj.magic decl : HxModuleDecl.t).packagePath : string) in if tmp != Obj.magic (HxRuntime.hx_null) then let __assign_28 = (tmp : string) in (
                      tempRight := __assign_28;
                      __assign_28
                    ) else let __assign_29 = ("" : string) in (
                      tempRight := __assign_29;
                      __assign_29
                    ));
                    raise (HxRuntime.Hx_return (Obj.repr (error (((((("package mismatch for \"" ^ HxString.toStdString ((Obj.magic parsed : stage1args_t).main)) ^ "\": expected \"") ^ HxString.toStdString (Obj.obj (HxAnon.get resolved "packagePath"))) ^ "\" but parsed \"") ^ HxString.toStdString (!tempRight)) ^ "\"" : string))))
                  )) else ());
                  let hasToplevelMain = HxModuleDecl.getHasToplevelMain (Obj.magic decl) in (
                    ignore (if not (hasToplevelMain) then ignore ((
                      ignore (if not (HxString.equals ((Obj.magic ((Obj.magic decl : HxModuleDecl.t).mainClass) : HxClassDecl.t).name) (Obj.obj (HxAnon.get resolved "className"))) then raise (HxRuntime.Hx_return (Obj.repr (error ((((("expected main class \"" ^ HxString.toStdString (Obj.obj (HxAnon.get resolved "className"))) ^ "\" but parsed \"") ^ HxString.toStdString ((Obj.magic ((Obj.magic decl : HxModuleDecl.t).mainClass) : HxClassDecl.t).name)) ^ "\" in ") ^ HxString.toStdString (Obj.obj (HxAnon.get resolved "path")) : string)))) else ());
                      if not ((Obj.magic ((Obj.magic decl : HxModuleDecl.t).mainClass) : HxClassDecl.t).hasStaticMain) then raise (HxRuntime.Hx_return (Obj.repr (error (("missing entrypoint main for " ^ HxString.toStdString ((Obj.magic parsed : stage1args_t).main)) ^ " (expected static function main or toplevel function main)" : string)))) else ()
                    )) else ());
                    let queue = Obj.magic (HxArray.create ()) in (
                      ignore (let _g = ref 0 in let _g1 = Obj.magic ((Obj.magic decl : HxModuleDecl.t).imports) in while !_g < HxArray.length _g1 do ignore (let imp = (HxArray.get (Obj.magic _g1) (!_g) : string) in (
                        ignore (let __old_30 = !_g in let __new_31 = HxInt.add __old_30 1 in (
                          ignore (_g := __new_31);
                          __new_31
                        ));
                        HxArray.push queue imp
                      )) done);
                      let visited = HxMap.create_string () in let q = ref 0 in (
                        ignore (try while !q < HxArray.length queue do try ignore (let imp = (HxArray.get (Obj.magic queue) (let __old_32 = !q in let __new_33 = HxInt.add __old_32 1 in (
                          ignore (q := __new_33);
                          __old_32
                        )) : string) in (
                          ignore (if imp == Obj.magic (HxRuntime.hx_null) || HxString.length imp = 0 then raise (HxRuntime.Hx_continue) else ());
                          ignore (if HxMap.exists_string visited imp then raise (HxRuntime.Hx_continue) else ());
                          ignore (HxMap.set_string visited imp true);
                          ignore (if StringTools.endsWith (imp : string) (".*" : string) then ignore (let base = (HxString.substr imp 0 (HxInt.sub (HxString.length imp) 2) : string) in let baseResolved = stage1resolver_resolveModule (Obj.magic classPaths) (base : string) ((Obj.magic parsed : stage1args_t).cwd : string) in (
                            ignore (if baseResolved == Obj.magic (HxRuntime.hx_null) then ignore ((
                              ignore (print_endline ("stage1=warn import_wildcard " ^ HxString.toStdString imp));
                              raise (HxRuntime.Hx_continue)
                            )) else ());
                            ignore (if not (HxMap.exists_string visited base) then ignore (HxArray.push queue base) else ());
                            raise (HxRuntime.Hx_continue)
                          )) else ());
                          let impResolved = stage1resolver_resolveModule (Obj.magic classPaths) (imp : string) ((Obj.magic parsed : stage1args_t).cwd : string) in (
                            ignore (if impResolved == Obj.magic (HxRuntime.hx_null) then raise (HxRuntime.Hx_return (Obj.repr (error ("import_missing " ^ HxString.toStdString imp : string)))) else ());
                            let tempMaybeString1 = ref (Obj.magic (HxRuntime.hx_null) : string) in (
                              ignore (try let path = (Obj.obj (HxAnon.get impResolved "path") : string) in let __assign_34 = Obj.magic (HxFile.getContent (path : string) : string) in (
                                tempMaybeString1 := __assign_34;
                                __assign_34
                              ) with
                                | HxRuntime.Hx_break -> raise (HxRuntime.Hx_break)
                                | HxRuntime.Hx_continue -> raise (HxRuntime.Hx_continue)
                                | HxRuntime.Hx_return __ret_35 -> raise (HxRuntime.Hx_return __ret_35)
                                | HxRuntime.Hx_exception (__exn_v_36, __exn_tags_37) -> if HxRuntime.tags_has __exn_tags_37 "haxe.io.Error" then let _hx = (Obj.obj (HxEnum.unbox_or_obj "haxe.io.Error" __exn_v_36) : Haxe_io_Error.error) in (
                                  ignore _hx;
                                  let __assign_39 = Obj.magic (Obj.magic (HxRuntime.hx_null)) in (
                                    tempMaybeString1 := __assign_39;
                                    __assign_39
                                  )
                                ) else if HxRuntime.tags_has __exn_tags_37 "String" then let _hx = (Obj.obj __exn_v_36 : string) in (
                                  ignore _hx;
                                  let __assign_38 = Obj.magic (Obj.magic (HxRuntime.hx_null)) in (
                                    tempMaybeString1 := __assign_38;
                                    __assign_38
                                  )
                                ) else HxRuntime.hx_throw_typed __exn_v_36 __exn_tags_37
                                | __exn_40 -> if HxRuntime.tags_has ["OcamlExn"] "haxe.io.Error" then let _hx = (Obj.obj (HxEnum.unbox_or_obj "haxe.io.Error" (Obj.repr __exn_40)) : Haxe_io_Error.error) in (
                                  ignore _hx;
                                  let __assign_42 = Obj.magic (Obj.magic (HxRuntime.hx_null)) in (
                                    tempMaybeString1 := __assign_42;
                                    __assign_42
                                  )
                                ) else if HxRuntime.tags_has ["OcamlExn"] "String" then let _hx = (Obj.obj (Obj.repr __exn_40) : string) in (
                                  ignore _hx;
                                  let __assign_41 = Obj.magic (Obj.magic (HxRuntime.hx_null)) in (
                                    tempMaybeString1 := __assign_41;
                                    __assign_41
                                  )
                                ) else raise (__exn_40));
                              let impSrc = (!tempMaybeString1 : string) in (
                                ignore (if impSrc == Obj.magic (HxRuntime.hx_null) then raise (HxRuntime.Hx_return (Obj.repr (error ("import_unreadable " ^ HxString.toStdString (Obj.obj (HxAnon.get impResolved "path")) : string)))) else ());
                                let tempHxModuleDecl1 = ref (Obj.magic (HxRuntime.hx_null) : HxModuleDecl.t) in (
                                  ignore (try let filteredImp = (HxConditionalCompilation.filterSource (impSrc : string) (Obj.magic definesMap) : string) in let __assign_43 = Obj.magic (ParsedModule.getDecl (Obj.magic (ParserStage.parse (filteredImp : string) (Obj.obj (HxAnon.get impResolved "path") : string))) ()) in (
                                    tempHxModuleDecl1 := __assign_43;
                                    __assign_43
                                  ) with
                                    | HxRuntime.Hx_break -> raise (HxRuntime.Hx_break)
                                    | HxRuntime.Hx_continue -> raise (HxRuntime.Hx_continue)
                                    | HxRuntime.Hx_return __ret_44 -> raise (HxRuntime.Hx_return __ret_44)
                                    | HxRuntime.Hx_exception (__exn_v_45, __exn_tags_46) -> if HxRuntime.tags_has __exn_tags_46 "HxParseError" then let e = (Obj.obj __exn_v_45 : HxParseError.t) in (
                                      ignore e;
                                      raise (HxRuntime.Hx_return (Obj.repr (error ((("parse failed for import \"" ^ HxString.toStdString imp) ^ "\": ") ^ HxString.toStdString (formatParseError (Obj.magic e)) : string))))
                                    ) else if HxRuntime.tags_has __exn_tags_46 "String" then let e = (Obj.obj __exn_v_45 : string) in (
                                      ignore e;
                                      raise (HxRuntime.Hx_return (Obj.repr (error ((("parse failed for import \"" ^ HxString.toStdString imp) ^ "\": ") ^ HxString.toStdString e : string))))
                                    ) else HxRuntime.hx_throw_typed __exn_v_45 __exn_tags_46
                                    | __exn_47 -> if HxRuntime.tags_has ["OcamlExn"] "HxParseError" then let e = (Obj.obj (Obj.repr __exn_47) : HxParseError.t) in (
                                      ignore e;
                                      raise (HxRuntime.Hx_return (Obj.repr (error ((("parse failed for import \"" ^ HxString.toStdString imp) ^ "\": ") ^ HxString.toStdString (formatParseError (Obj.magic e)) : string))))
                                    ) else if HxRuntime.tags_has ["OcamlExn"] "String" then let e = (Obj.obj (Obj.repr __exn_47) : string) in (
                                      ignore e;
                                      raise (HxRuntime.Hx_return (Obj.repr (error ((("parse failed for import \"" ^ HxString.toStdString imp) ^ "\": ") ^ HxString.toStdString e : string))))
                                    ) else raise (__exn_47));
                                  let impDecl = Obj.magic (!tempHxModuleDecl1) in let parsedName = ((Obj.magic ((Obj.magic impDecl : HxModuleDecl.t).mainClass) : HxClassDecl.t).name : string) in (
                                    ignore (if parsedName != Obj.magic (HxRuntime.hx_null) && HxString.length parsedName > 0 && not (HxString.equals parsedName "Unknown") && not (HxString.equals parsedName (Obj.obj (HxAnon.get impResolved "className"))) then ignore (print_endline ("stage1=warn import_class_mismatch " ^ HxString.toStdString imp)) else ());
                                    let tempLeft1 = ref ("" : string) in (
                                      ignore (let tmp = ((Obj.magic impDecl : HxModuleDecl.t).packagePath : string) in if tmp != Obj.magic (HxRuntime.hx_null) then let __assign_48 = (tmp : string) in (
                                        tempLeft1 := __assign_48;
                                        __assign_48
                                      ) else let __assign_49 = ("" : string) in (
                                        tempLeft1 := __assign_49;
                                        __assign_49
                                      ));
                                      ignore (if not (HxString.equals (!tempLeft1) (Obj.obj (HxAnon.get impResolved "packagePath"))) then ignore ((
                                        ignore (print_endline ("stage1=warn import_package_mismatch " ^ HxString.toStdString imp));
                                        raise (HxRuntime.Hx_continue)
                                      )) else ());
                                      let _g = ref 0 in let _g1 = Obj.magic ((Obj.magic impDecl : HxModuleDecl.t).imports) in while !_g < HxArray.length _g1 do ignore (let imp2 = (HxArray.get (Obj.magic _g1) (!_g) : string) in (
                                        ignore (let __old_50 = !_g in let __new_51 = HxInt.add __old_50 1 in (
                                          ignore (_g := __new_51);
                                          __new_51
                                        ));
                                        HxArray.push queue imp2
                                      )) done
                                    )
                                  )
                                )
                              )
                            )
                          )
                        )) with
                          | HxRuntime.Hx_continue -> () done with
                          | HxRuntime.Hx_break -> ());
                        ignore (print_endline "stage1=ok");
                        ignore (print_endline ("main=" ^ HxString.toStdString ((Obj.magic parsed : stage1args_t).main)));
                        ignore (print_endline ("file=" ^ HxString.toStdString (Obj.obj (HxAnon.get resolved "path"))));
                        0
                      )
                    )
                  )
                )
              )
            )
          )
        )
      )
    )
  )
) in Obj.magic __fallback_result_53 with
  | HxRuntime.Hx_return __ret_52 -> Obj.obj __ret_52