# 1 "ParserStage.ml"
(* Generated by reflaxe.ocaml (WIP) *)
(* Haxe type: ParserStage *)

let __reflaxe_ocaml__ = ()

type t = { __hx_type : Obj.t }

let create = fun () -> let self = ({ __hx_type = HxType.class_ "ParserStage" } : t) in (
  ignore (ignore ());
  self
)

let __empty = fun () -> ({ __hx_type = HxType.class_ "ParserStage" } : t)

let expectedMainClassFromFile = fun filePath -> try let __fallback_result_4 = (
  ignore (if filePath == Obj.magic (HxRuntime.hx_null) || HxString.length filePath = 0 then raise (HxRuntime.Hx_return (Obj.repr (Obj.magic (HxRuntime.hx_null)))) else ());
  let name = (Haxe_io_Path.withoutDirectory (filePath : string) : string) in let dot = HxString.lastIndexOf name "." (HxString.length name) in let tempResult = ref (Obj.magic (HxRuntime.hx_null) : string) in (
    ignore (if dot <= 0 then let __assign_1 = Obj.magic (name : string) in (
      tempResult := __assign_1;
      __assign_1
    ) else let __assign_2 = Obj.magic (HxString.substr name 0 dot : string) in (
      tempResult := __assign_2;
      __assign_2
    ));
    !tempResult
  )
) in Obj.magic __fallback_result_4 with
  | HxRuntime.Hx_return __ret_3 -> Obj.obj __ret_3

let isIdentCode = fun code -> code >= 65 && code <= 90 || code >= 97 && code <= 122 || code >= 48 && code <= 57 || code = 95

let startsWithWord = fun source index word -> try let __fallback_result_8 = (
  ignore (if index < 0 || HxInt.add index (HxString.length word) > HxString.length source then raise (HxRuntime.Hx_return (Obj.repr false)) else ());
  ignore (if not (HxString.equals (HxString.substr source index (HxString.length word)) word) then raise (HxRuntime.Hx_return (Obj.repr false)) else ());
  let beforeOk = index = 0 || not (isIdentCode (let __nullable_int_5 = HxString.charCodeAt source (HxInt.sub index 1) in if __nullable_int_5 == HxRuntime.hx_null then 0 else Obj.obj __nullable_int_5)) in let after = HxInt.add index (HxString.length word) in let afterOk = after >= HxString.length source || not (isIdentCode (let __nullable_int_6 = HxString.charCodeAt source after in if __nullable_int_6 == HxRuntime.hx_null then 0 else Obj.obj __nullable_int_6)) in beforeOk && afterOk
) in Obj.magic __fallback_result_8 with
  | HxRuntime.Hx_return __ret_7 -> Obj.obj __ret_7

let skipSpaces = fun source index -> try let __fallback_result_15 = let i = ref index in (
  ignore (while !i < HxString.length source do ignore (let _g = HxString.charCodeAt source (!i) in if _g == HxRuntime.hx_null then raise (HxRuntime.Hx_return (Obj.repr (!i))) else ignore (let __switch_11 = _g in if __switch_11 == HxRuntime.hx_null then raise (HxRuntime.Hx_return (Obj.repr (!i))) else match Obj.obj __switch_11 with
    | 9 | 10 | 13 | 32 -> ignore (let __old_12 = !i in let __new_13 = HxInt.add __old_12 1 in (
      ignore (i := __new_13);
      __old_12
    ))
    | _ -> raise (HxRuntime.Hx_return (Obj.repr (!i))))) done);
  !i
) in Obj.magic __fallback_result_15 with
  | HxRuntime.Hx_return __ret_14 -> Obj.obj __ret_14

let findMatchingBrace = fun source openIndex -> try let __fallback_result_56 = let depth = ref 1 in let i = ref (HxInt.add openIndex 1) in let stringQuote = ref 0 in let escaped = ref false in let lineComment = ref false in let blockComment = ref false in (
  ignore (try while !i < HxString.length source do try ignore (let code = HxString.charCodeAt source (!i) in let tempMaybeNumber = ref (HxRuntime.hx_null : Obj.t) in (
    ignore (if HxInt.add (!i) 1 < HxString.length source then let __assign_16 = Obj.magic (HxString.charCodeAt source (HxInt.add (!i) 1)) in (
      tempMaybeNumber := __assign_16;
      __assign_16
    ) else let __assign_17 = Obj.magic (Obj.repr (-1)) in (
      tempMaybeNumber := __assign_17;
      __assign_17
    ));
    let next = Obj.magic (!tempMaybeNumber) in (
      ignore (if !lineComment then ignore ((
        ignore (if (let __nullable_18 = code in if __nullable_18 == HxRuntime.hx_null then false else Obj.obj __nullable_18 = 10) || (let __nullable_19 = code in if __nullable_19 == HxRuntime.hx_null then false else Obj.obj __nullable_19 = 13) then ignore (let __assign_20 = false in (
          lineComment := __assign_20;
          __assign_20
        )) else ());
        ignore (let __old_21 = !i in let __new_22 = HxInt.add __old_21 1 in (
          ignore (i := __new_22);
          __old_21
        ));
        raise (HxRuntime.Hx_continue)
      )) else ());
      ignore (if !blockComment then ignore ((
        ignore (if (let __nullable_23 = code in if __nullable_23 == HxRuntime.hx_null then false else Obj.obj __nullable_23 = 42) && (let __nullable_24 = next in if __nullable_24 == HxRuntime.hx_null then false else Obj.obj __nullable_24 = 47) then ignore ((
          ignore (let __assign_25 = false in (
            blockComment := __assign_25;
            __assign_25
          ));
          i := HxInt.add (!i) 2
        )) else ignore (let __old_26 = !i in let __new_27 = HxInt.add __old_26 1 in (
          ignore (i := __new_27);
          __old_26
        )));
        raise (HxRuntime.Hx_continue)
      )) else ());
      ignore (if !stringQuote <> 0 then ignore ((
        ignore (if !escaped then ignore (let __assign_28 = false in (
          escaped := __assign_28;
          __assign_28
        )) else ignore (if let __nullable_29 = code in if __nullable_29 == HxRuntime.hx_null then false else Obj.obj __nullable_29 = 92 then ignore (let __assign_30 = true in (
          escaped := __assign_30;
          __assign_30
        )) else ignore (if let __nullable_31 = code in if __nullable_31 == HxRuntime.hx_null then false else Obj.obj __nullable_31 = !stringQuote then ignore (let __assign_32 = 0 in (
          stringQuote := __assign_32;
          __assign_32
        )) else ())));
        ignore (let __old_33 = !i in let __new_34 = HxInt.add __old_33 1 in (
          ignore (i := __new_34);
          __old_33
        ));
        raise (HxRuntime.Hx_continue)
      )) else ());
      ignore (if (let __nullable_35 = code in if __nullable_35 == HxRuntime.hx_null then false else Obj.obj __nullable_35 = 47) && (let __nullable_36 = next in if __nullable_36 == HxRuntime.hx_null then false else Obj.obj __nullable_36 = 47) then ignore ((
        ignore (let __assign_37 = true in (
          lineComment := __assign_37;
          __assign_37
        ));
        ignore (i := HxInt.add (!i) 2);
        raise (HxRuntime.Hx_continue)
      )) else ());
      ignore (if (let __nullable_38 = code in if __nullable_38 == HxRuntime.hx_null then false else Obj.obj __nullable_38 = 47) && (let __nullable_39 = next in if __nullable_39 == HxRuntime.hx_null then false else Obj.obj __nullable_39 = 42) then ignore ((
        ignore (let __assign_40 = true in (
          blockComment := __assign_40;
          __assign_40
        ));
        ignore (i := HxInt.add (!i) 2);
        raise (HxRuntime.Hx_continue)
      )) else ());
      ignore (if (let __nullable_41 = code in if __nullable_41 == HxRuntime.hx_null then false else Obj.obj __nullable_41 = 34) || (let __nullable_42 = code in if __nullable_42 == HxRuntime.hx_null then false else Obj.obj __nullable_42 = 39) then ignore ((
        ignore (let __assign_43 = let __nullable_int_44 = code in if __nullable_int_44 == HxRuntime.hx_null then 0 else Obj.obj __nullable_int_44 in (
          stringQuote := __assign_43;
          __assign_43
        ));
        ignore (let __old_45 = !i in let __new_46 = HxInt.add __old_45 1 in (
          ignore (i := __new_46);
          __old_45
        ));
        raise (HxRuntime.Hx_continue)
      )) else ());
      ignore (if let __nullable_47 = code in if __nullable_47 == HxRuntime.hx_null then false else Obj.obj __nullable_47 = 123 then ignore (let __old_48 = !depth in let __new_49 = HxInt.add __old_48 1 in (
        ignore (depth := __new_49);
        __old_48
      )) else ignore (if let __nullable_50 = code in if __nullable_50 == HxRuntime.hx_null then false else Obj.obj __nullable_50 = 125 then ignore ((
        ignore (let __old_51 = !depth in let __new_52 = HxInt.add __old_51 (-1) in (
          ignore (depth := __new_52);
          __old_51
        ));
        if !depth = 0 then raise (HxRuntime.Hx_return (Obj.repr (!i))) else ()
      )) else ()));
      let __old_53 = !i in let __new_54 = HxInt.add __old_53 1 in (
        ignore (i := __new_54);
        __old_53
      )
    )
  )) with
    | HxRuntime.Hx_continue -> () done with
    | HxRuntime.Hx_break -> ());
  -1
) in Obj.magic __fallback_result_56 with
  | HxRuntime.Hx_return __ret_55 -> Obj.obj __ret_55

let scanToplevelMainFunction = fun source -> try let __fallback_result_74 = (
  ignore (if source == Obj.magic (HxRuntime.hx_null) || HxString.length source = 0 then raise (HxRuntime.Hx_return (Obj.repr (Obj.magic (Obj.magic (HxRuntime.hx_null))))) else ());
  let index = ref 0 in (
    ignore (try while !index < HxString.length source do try ignore (let found = HxString.indexOf source "function" (!index) in (
      ignore (if found < 0 then raise (HxRuntime.Hx_return (Obj.repr (Obj.magic (Obj.magic (HxRuntime.hx_null))))) else ());
      ignore (let __assign_57 = HxInt.add found (HxString.length "function") in (
        index := __assign_57;
        __assign_57
      ));
      ignore (if not (startsWithWord (source : string) found ("function" : string)) then raise (HxRuntime.Hx_continue) else ());
      let nameStart = skipSpaces (source : string) (!index) in (
        ignore (if not (startsWithWord (source : string) nameStart ("main" : string)) then raise (HxRuntime.Hx_continue) else ());
        let hx_open = HxString.indexOf source "{" (HxInt.add nameStart (HxString.length "main")) in (
          ignore (if hx_open < 0 then raise (HxRuntime.Hx_return (Obj.repr (Obj.magic (Obj.magic (HxRuntime.hx_null))))) else ());
          let close = findMatchingBrace (source : string) hx_open in (
            ignore (if close < 0 then raise (HxRuntime.Hx_return (Obj.repr (Obj.magic (Obj.magic (HxRuntime.hx_null))))) else ());
            let bodyText = (HxString.substring source (HxInt.add hx_open 1) close : string) in let body = ref (Obj.magic (let __arr_58 = HxArray.create () in __arr_58)) in (
              ignore (try let __assign_59 = Obj.magic (HxParser.parseFunctionBodyText (bodyText : string)) in (
                body := __assign_59;
                __assign_59
              ) with
                | HxRuntime.Hx_break -> raise (HxRuntime.Hx_break)
                | HxRuntime.Hx_continue -> raise (HxRuntime.Hx_continue)
                | HxRuntime.Hx_return __ret_60 -> raise (HxRuntime.Hx_return __ret_60)
                | HxRuntime.Hx_exception (__exn_v_61, __exn_tags_62) -> if HxRuntime.tags_has __exn_tags_62 "HxParseError" then let _hx = (Obj.obj __exn_v_61 : HxParseError.t) in (
                  ignore _hx;
                  let __assign_65 = Obj.magic (let __arr_66 = HxArray.create () in __arr_66) in (
                    body := __assign_65;
                    __assign_65
                  )
                ) else if HxRuntime.tags_has __exn_tags_62 "String" then let _hx = (Obj.obj __exn_v_61 : string) in (
                  ignore _hx;
                  let __assign_63 = Obj.magic (let __arr_64 = HxArray.create () in __arr_64) in (
                    body := __assign_63;
                    __assign_63
                  )
                ) else HxRuntime.hx_throw_typed __exn_v_61 __exn_tags_62
                | __exn_67 -> if HxRuntime.tags_has ["OcamlExn"] "HxParseError" then let _hx = (Obj.obj (Obj.repr __exn_67) : HxParseError.t) in (
                  ignore _hx;
                  let __assign_70 = Obj.magic (let __arr_71 = HxArray.create () in __arr_71) in (
                    body := __assign_70;
                    __assign_70
                  )
                ) else if HxRuntime.tags_has ["OcamlExn"] "String" then let _hx = (Obj.obj (Obj.repr __exn_67) : string) in (
                  ignore _hx;
                  let __assign_68 = Obj.magic (let __arr_69 = HxArray.create () in __arr_69) in (
                    body := __assign_68;
                    __assign_68
                  )
                ) else raise (__exn_67));
              raise (HxRuntime.Hx_return (Obj.repr (HxFunctionDecl.create ("main" : string) (Obj.magic (HxVisibility.Public)) true (Obj.magic (let __arr_72 = HxArray.create () in __arr_72)) ("Void" : string) (Obj.magic (!body)) ("" : string) (Obj.magic (Obj.magic (HxRuntime.hx_null))) (Obj.magic (HxPos.unknown ())) (Obj.magic (HxPos.unknown ())) (bodyText : string))))
            )
          )
        )
      )
    )) with
      | HxRuntime.Hx_continue -> () done with
      | HxRuntime.Hx_break -> ());
    Obj.magic (HxRuntime.hx_null)
  )
) in Obj.magic __fallback_result_74 with
  | HxRuntime.Hx_return __ret_73 -> Obj.obj __ret_73

let parseViaNativeHooks = fun source expectedMainClass -> let tempString = ref ("" : string) in (
  ignore (if expectedMainClass != Obj.magic (HxRuntime.hx_null) && HxString.length expectedMainClass > 0 then let __assign_190 = (HxHxNativeParser.parse_module_decl_with_expected (source : string) (expectedMainClass : string) : string) in (
    tempString := __assign_190;
    __assign_190
  ) else let __assign_191 = (HxHxNativeParser.parse_module_decl (source : string) : string) in (
    tempString := __assign_191;
    __assign_191
  ));
  ParserStageNativeDecode.decodeNativeProtocol (!tempString : string)
)

let parse = fun source filePath -> let expectedMainClass = (expectedMainClassFromFile (filePath : string) : string) in let tempHxModuleDecl = ref (Obj.magic (HxRuntime.hx_null) : HxModuleDecl.t) in let enrichNativeDecl = fun nativeDecl -> try let __fallback_result_173 = let main = ref (Obj.magic (HxModuleDecl.getMainClass (Obj.magic nativeDecl))) in let mainName = ref (HxClassDecl.getName (Obj.magic (!main)) : string) in let staticPatchApplied = ref false in let scannedClassStaticsByName = HxMap.create_string () in (
  ignore (let _g = ref 0 in let tempArray = ref (Obj.magic (HxRuntime.hx_null) : HxClassDecl.t HxArray.t) in (
    ignore (let mainClassName = (Obj.magic (HxRuntime.hx_null) : string) in let __assign_75 = Obj.magic (ParserStageScanHelpers.scanModuleLocalHelperClasses (source : string) (mainClassName : string)) in (
      tempArray := __assign_75;
      __assign_75
    ));
    let _g1 = Obj.magic (!tempArray) in while !_g < HxArray.length _g1 do ignore (let scanned = Obj.magic (HxArray.get (Obj.magic _g1) (!_g)) in (
      ignore (let __old_76 = !_g in let __new_77 = HxInt.add __old_76 1 in (
        ignore (_g := __new_77);
        __new_77
      ));
      let tempMaybeString = ref (Obj.magic (HxRuntime.hx_null) : string) in (
        ignore (if scanned == Obj.magic (HxRuntime.hx_null) then let __assign_78 = Obj.magic (Obj.magic (HxRuntime.hx_null)) in (
          tempMaybeString := __assign_78;
          __assign_78
        ) else let __assign_79 = Obj.magic (HxClassDecl.getName (Obj.magic scanned) : string) in (
          tempMaybeString := __assign_79;
          __assign_79
        ));
        let scannedName = (!tempMaybeString : string) in if scannedName != Obj.magic (HxRuntime.hx_null) && HxString.length scannedName > 0 && not (HxMap.exists_string scannedClassStaticsByName scannedName) then ignore (HxMap.set_string scannedClassStaticsByName scannedName scanned) else ()
      )
    )) done
  ));
  let patchClassStaticFlagsFromScan = fun cls -> try let __fallback_result_126 = (
    ignore (if cls == Obj.magic (HxRuntime.hx_null) then raise (HxRuntime.Hx_return (Obj.repr (Obj.magic cls))) else ());
    let className = (HxClassDecl.getName (Obj.magic cls) : string) in (
      ignore (if className == Obj.magic (HxRuntime.hx_null) || HxString.length className = 0 then raise (HxRuntime.Hx_return (Obj.repr (Obj.magic cls))) else ());
      let scanned = Obj.magic (HxMap.get_string scannedClassStaticsByName className) in (
        ignore (if scanned == Obj.magic (HxRuntime.hx_null) then raise (HxRuntime.Hx_return (Obj.repr (Obj.magic cls))) else ());
        let scannedFnStaticByName = HxMap.create_string () in let scannedFnByName = HxMap.create_string () in (
          ignore (let _g = ref 0 in let _g1 = Obj.magic (HxClassDecl.getFunctions (Obj.magic scanned)) in while !_g < HxArray.length _g1 do ignore (let fn = Obj.magic (HxArray.get (Obj.magic _g1) (!_g)) in (
            ignore (let __old_80 = !_g in let __new_81 = HxInt.add __old_80 1 in (
              ignore (_g := __new_81);
              __new_81
            ));
            let fnName = (HxFunctionDecl.getName (Obj.magic fn) : string) in if fnName != Obj.magic (HxRuntime.hx_null) && HxString.length fnName > 0 then ignore ((
              ignore (let value = HxFunctionDecl.getIsStatic (Obj.magic fn) in HxMap.set_string scannedFnStaticByName fnName value);
              HxMap.set_string scannedFnByName fnName fn
            )) else ()
          )) done);
          let hasMetadata = fun values marker -> try let __fallback_result_85 = (
            ignore (if values == Obj.magic (HxRuntime.hx_null) then raise (HxRuntime.Hx_return (Obj.repr false)) else ());
            ignore (let _g = ref 0 in while !_g < HxArray.length values do ignore (let value = (HxArray.get (Obj.magic values) (!_g) : string) in (
              ignore (let __old_82 = !_g in let __new_83 = HxInt.add __old_82 1 in (
                ignore (_g := __new_83);
                __new_83
              ));
              if HxString.equals value marker then raise (HxRuntime.Hx_return (Obj.repr true)) else ()
            )) done);
            false
          ) in Obj.magic __fallback_result_85 with
            | HxRuntime.Hx_return __ret_84 -> Obj.obj __ret_84 in let mergeScannedMetadata = fun fn scannedFn -> let out = Obj.magic (HxArray.copy (HxFunctionDecl.getMetadata (Obj.magic fn))) in (
            ignore (if scannedFn != Obj.magic (HxRuntime.hx_null) && hasMetadata (Obj.magic (HxFunctionDecl.getMetadata (Obj.magic scannedFn))) ("macro" : string) && not (hasMetadata (Obj.magic out) ("macro" : string)) then ignore (HxArray.push out "macro") else ());
            out
          ) in let sameMetadata = fun left right -> try let __fallback_result_89 = (
            ignore (if left == Obj.magic (HxRuntime.hx_null) || right == Obj.magic (HxRuntime.hx_null) then raise (HxRuntime.Hx_return (Obj.repr (Obj.repr left == Obj.repr right))) else ());
            ignore (if HxArray.length left <> HxArray.length right then raise (HxRuntime.Hx_return (Obj.repr false)) else ());
            ignore (let _g = ref 0 in let _g1 = HxArray.length left in while !_g < _g1 do ignore (let i = let __old_86 = !_g in let __new_87 = HxInt.add __old_86 1 in (
              ignore (_g := __new_87);
              __old_86
            ) in if not (HxString.equals (HxArray.get (Obj.magic left) i) (HxArray.get (Obj.magic right) i)) then raise (HxRuntime.Hx_return (Obj.repr false)) else ()) done);
            true
          ) in Obj.magic __fallback_result_89 with
            | HxRuntime.Hx_return __ret_88 -> Obj.obj __ret_88 in let changed = ref false in let scannedExtendsPath = (HxClassDecl.getExtendsPath (Obj.magic scanned) : string) in let tempString = ref ("" : string) in (
            ignore (if scannedExtendsPath != Obj.magic (HxRuntime.hx_null) && HxString.length scannedExtendsPath > 0 then let __assign_90 = (scannedExtendsPath : string) in (
              tempString := __assign_90;
              __assign_90
            ) else let __assign_91 = (HxClassDecl.getExtendsPath (Obj.magic cls) : string) in (
              tempString := __assign_91;
              __assign_91
            ));
            let extendsPath = (!tempString : string) in (
              ignore (if not (HxString.equals extendsPath (HxClassDecl.getExtendsPath (Obj.magic cls))) then ignore (let __assign_92 = true in (
                changed := __assign_92;
                __assign_92
              )) else ());
              let patchedFns = Obj.magic (HxArray.create ()) in let existingFnNames = HxMap.create_string () in (
                ignore (let _g = ref 0 in let _g1 = Obj.magic (HxClassDecl.getFunctions (Obj.magic cls)) in while !_g < HxArray.length _g1 do ignore (let fn = Obj.magic (HxArray.get (Obj.magic _g1) (!_g)) in (
                  ignore (let __old_93 = !_g in let __new_94 = HxInt.add __old_93 1 in (
                    ignore (_g := __new_94);
                    __new_94
                  ));
                  let fnName = (HxFunctionDecl.getName (Obj.magic fn) : string) in let tempMaybeBool = ref (HxRuntime.hx_null : Obj.t) in (
                    ignore (if fnName == Obj.magic (HxRuntime.hx_null) then let __assign_95 = Obj.magic (HxRuntime.hx_null) in (
                      tempMaybeBool := __assign_95;
                      __assign_95
                    ) else let __assign_96 = Obj.magic (HxMap.get_string scannedFnStaticByName fnName) in (
                      tempMaybeBool := __assign_96;
                      __assign_96
                    ));
                    let scannedStatic = Obj.magic (!tempMaybeBool) in let tempMaybeBool1 = ref (HxRuntime.hx_null : Obj.t) in (
                      ignore (if scannedStatic == Obj.magic (HxRuntime.hx_null) then let __assign_97 = Obj.magic (HxRuntime.box_bool (HxFunctionDecl.getIsStatic (Obj.magic fn))) in (
                        tempMaybeBool1 := __assign_97;
                        __assign_97
                      ) else let __assign_98 = Obj.magic (Obj.repr scannedStatic) in (
                        tempMaybeBool1 := __assign_98;
                        __assign_98
                      ));
                      let isStatic = Obj.magic (!tempMaybeBool1) in let tempMaybeHxFunctionDecl = ref (Obj.magic (HxRuntime.hx_null) : HxFunctionDecl.t) in (
                        ignore (if fnName == Obj.magic (HxRuntime.hx_null) then let __assign_99 = Obj.magic (Obj.magic (Obj.magic (HxRuntime.hx_null))) in (
                          tempMaybeHxFunctionDecl := __assign_99;
                          __assign_99
                        ) else let __assign_100 = Obj.magic (Obj.magic (HxMap.get_string scannedFnByName fnName)) in (
                          tempMaybeHxFunctionDecl := __assign_100;
                          __assign_100
                        ));
                        let scannedFn = Obj.magic (!tempMaybeHxFunctionDecl) in let metadata = Obj.magic (mergeScannedMetadata (Obj.magic fn) (Obj.magic scannedFn)) in let metadataChanged = not (sameMetadata (Obj.magic metadata) (Obj.magic (HxFunctionDecl.getMetadata (Obj.magic fn)))) in let tempArray1 = ref (Obj.magic (HxRuntime.hx_null) : HxStmt.hxstmt HxArray.t) in (
                          ignore (if scannedFn == Obj.magic (HxRuntime.hx_null) then let __assign_101 = Obj.magic (let __arr_102 = HxArray.create () in __arr_102) in (
                            tempArray1 := __assign_101;
                            __assign_101
                          ) else let __assign_103 = Obj.magic (HxFunctionDecl.getBody (Obj.magic scannedFn)) in (
                            tempArray1 := __assign_103;
                            __assign_103
                          ));
                          let scannedBody = Obj.magic (!tempArray1) in let bodyChanged = HxString.equals fnName "new" && HxArray.length (HxFunctionDecl.getBody (Obj.magic fn)) = 0 && HxArray.length scannedBody > 0 in let tempArray2 = ref (Obj.magic (HxRuntime.hx_null) : HxStmt.hxstmt HxArray.t) in (
                            ignore (if bodyChanged then let __assign_104 = Obj.magic scannedBody in (
                              tempArray2 := __assign_104;
                              __assign_104
                            ) else let __assign_105 = Obj.magic (HxFunctionDecl.getBody (Obj.magic fn)) in (
                              tempArray2 := __assign_105;
                              __assign_105
                            ));
                            let body = Obj.magic (!tempArray2) in let tempString1 = ref ("" : string) in (
                              ignore (if bodyChanged then let __assign_106 = (HxFunctionDecl.getBodyText (Obj.magic scannedFn) : string) in (
                                tempString1 := __assign_106;
                                __assign_106
                              ) else let __assign_107 = (HxFunctionDecl.getBodyText (Obj.magic fn) : string) in (
                                tempString1 := __assign_107;
                                __assign_107
                              ));
                              let bodyText = (!tempString1 : string) in (
                                ignore (if not (let __nullable_108 = isStatic in if __nullable_108 == HxRuntime.hx_null then false else Obj.obj __nullable_108 = HxFunctionDecl.getIsStatic (Obj.magic fn)) then ignore (let __assign_109 = true in (
                                  changed := __assign_109;
                                  __assign_109
                                )) else ());
                                ignore (if metadataChanged then ignore (let __assign_110 = true in (
                                  changed := __assign_110;
                                  __assign_110
                                )) else ());
                                ignore (if bodyChanged then ignore (let __assign_111 = true in (
                                  changed := __assign_111;
                                  __assign_111
                                )) else ());
                                ignore (if fnName != Obj.magic (HxRuntime.hx_null) && HxString.length fnName > 0 then ignore (HxMap.set_string existingFnNames fnName true) else ());
                                let tempHxFunctionDecl = ref (Obj.magic (HxRuntime.hx_null) : HxFunctionDecl.t) in (
                                  ignore (if (let __nullable_112 = isStatic in if __nullable_112 == HxRuntime.hx_null then false else Obj.obj __nullable_112 = HxFunctionDecl.getIsStatic (Obj.magic fn)) && not (metadataChanged) && not (bodyChanged) then let __assign_113 = Obj.magic fn in (
                                    tempHxFunctionDecl := __assign_113;
                                    __assign_113
                                  ) else let __assign_114 = Obj.magic (HxFunctionDecl.create (HxFunctionDecl.getName (Obj.magic fn) : string) (Obj.magic (HxFunctionDecl.getVisibility (Obj.magic fn))) (let __nullable_bool_115 = isStatic in if __nullable_bool_115 == HxRuntime.hx_null then false else HxRuntime.unbox_bool_or_obj __nullable_bool_115) (Obj.magic (HxFunctionDecl.getArgs (Obj.magic fn))) (HxFunctionDecl.getReturnTypeHint (Obj.magic fn) : string) (Obj.magic body) (HxFunctionDecl.getReturnStringLiteral (Obj.magic fn) : string) (Obj.magic metadata) (Obj.magic (HxFunctionDecl.getPos (Obj.magic fn))) (Obj.magic (HxFunctionDecl.getEndPos (Obj.magic fn))) (bodyText : string)) in (
                                    tempHxFunctionDecl := __assign_114;
                                    __assign_114
                                  ));
                                  HxArray.push patchedFns (!tempHxFunctionDecl)
                                )
                              )
                            )
                          )
                        )
                      )
                    )
                  )
                )) done);
                ignore (let _g = ref 0 in let _g1 = Obj.magic (HxClassDecl.getFunctions (Obj.magic scanned)) in try while !_g < HxArray.length _g1 do try ignore (let fn = Obj.magic (HxArray.get (Obj.magic _g1) (!_g)) in (
                  ignore (let __old_116 = !_g in let __new_117 = HxInt.add __old_116 1 in (
                    ignore (_g := __new_117);
                    __new_117
                  ));
                  let fnName = (HxFunctionDecl.getName (Obj.magic fn) : string) in (
                    ignore (if fnName == Obj.magic (HxRuntime.hx_null) || HxString.length fnName = 0 || HxMap.exists_string existingFnNames fnName then raise (HxRuntime.Hx_continue) else ());
                    ignore (HxArray.push patchedFns fn);
                    ignore (HxMap.set_string existingFnNames fnName true);
                    let __assign_118 = true in (
                      changed := __assign_118;
                      __assign_118
                    )
                  )
                )) with
                  | HxRuntime.Hx_continue -> () done with
                  | HxRuntime.Hx_break -> ());
                let patchedFields = Obj.magic (HxArray.create ()) in let existingFieldNames = HxMap.create_string () in (
                  ignore (let _g = ref 0 in let _g1 = Obj.magic (HxClassDecl.getFields (Obj.magic cls)) in while !_g < HxArray.length _g1 do ignore (let f = Obj.magic (HxArray.get (Obj.magic _g1) (!_g)) in (
                    ignore (let __old_119 = !_g in let __new_120 = HxInt.add __old_119 1 in (
                      ignore (_g := __new_120);
                      __new_120
                    ));
                    ignore (HxArray.push patchedFields f);
                    let fieldName = (HxFieldDecl.getName (Obj.magic f) : string) in if fieldName != Obj.magic (HxRuntime.hx_null) && HxString.length fieldName > 0 then ignore (HxMap.set_string existingFieldNames fieldName true) else ()
                  )) done);
                  ignore (let _g = ref 0 in let _g1 = Obj.magic (HxClassDecl.getFields (Obj.magic scanned)) in try while !_g < HxArray.length _g1 do try ignore (let f = Obj.magic (HxArray.get (Obj.magic _g1) (!_g)) in (
                    ignore (let __old_121 = !_g in let __new_122 = HxInt.add __old_121 1 in (
                      ignore (_g := __new_122);
                      __new_122
                    ));
                    let fieldName = (HxFieldDecl.getName (Obj.magic f) : string) in (
                      ignore (if fieldName == Obj.magic (HxRuntime.hx_null) || HxString.length fieldName = 0 || HxMap.exists_string existingFieldNames fieldName then raise (HxRuntime.Hx_continue) else ());
                      ignore (HxArray.push patchedFields f);
                      ignore (HxMap.set_string existingFieldNames fieldName true);
                      let __assign_123 = true in (
                        changed := __assign_123;
                        __assign_123
                      )
                    )
                  )) with
                    | HxRuntime.Hx_continue -> () done with
                    | HxRuntime.Hx_break -> ());
                  ignore (if not (!changed) then raise (HxRuntime.Hx_return (Obj.repr (Obj.magic cls))) else ());
                  ignore (let __assign_124 = true in (
                    staticPatchApplied := __assign_124;
                    __assign_124
                  ));
                  HxClassDecl.create (HxClassDecl.getName (Obj.magic cls) : string) (HxClassDecl.getHasStaticMain (Obj.magic cls)) (Obj.magic patchedFns) (Obj.magic patchedFields) (extendsPath : string)
                )
              )
            )
          )
        )
      )
    )
  ) in Obj.magic __fallback_result_126 with
    | HxRuntime.Hx_return __ret_125 -> Obj.obj __ret_125 in let tempArray3 = ref (Obj.magic (HxRuntime.hx_null) : HxClassDecl.t HxArray.t) in (
    ignore (let mainTypeName = (Obj.magic (HxRuntime.hx_null) : string) in let __assign_127 = Obj.magic (ParserStageScanHelpers.scanModuleLocalHelperEnums (source : string) (mainTypeName : string)) in (
      tempArray3 := __assign_127;
      __assign_127
    ));
    let enumDeclsAll = Obj.magic (!tempArray3) in let tempArray4 = ref (Obj.magic (HxRuntime.hx_null) : HxClassDecl.t HxArray.t) in (
      ignore (let mainTypeName = (Obj.magic (HxRuntime.hx_null) : string) in let __assign_128 = Obj.magic (ParserStageScanHelpers.scanModuleLocalHelperTypedefs (source : string) (mainTypeName : string)) in (
        tempArray4 := __assign_128;
        __assign_128
      ));
      let typedefDeclsAll = Obj.magic (!tempArray4) in let tempArray5 = ref (Obj.magic (HxRuntime.hx_null) : HxClassDecl.t HxArray.t) in (
        ignore (let mainTypeName = (Obj.magic (HxRuntime.hx_null) : string) in let __assign_129 = Obj.magic (ParserStageScanHelpers.scanModuleLocalHelperAbstracts (source : string) (mainTypeName : string)) in (
          tempArray5 := __assign_129;
          __assign_129
        ));
        let abstractDeclsAll = Obj.magic (!tempArray5) in (
          ignore (if (!mainName == Obj.magic (HxRuntime.hx_null) || HxString.length (!mainName) = 0 || HxString.equals (!mainName) "Unknown") && expectedMainClass != Obj.magic (HxRuntime.hx_null) then ignore (let tryPickMainFrom = fun candidates -> try let __fallback_result_135 = (
            ignore (if candidates == Obj.magic (HxRuntime.hx_null) then raise (HxRuntime.Hx_return (Obj.repr false)) else ());
            ignore (let _g = ref 0 in while !_g < HxArray.length candidates do ignore (let c = Obj.magic (HxArray.get (Obj.magic candidates) (!_g)) in (
              ignore (let __old_130 = !_g in let __new_131 = HxInt.add __old_130 1 in (
                ignore (_g := __new_131);
                __new_131
              ));
              let nm = (HxClassDecl.getName (Obj.magic c) : string) in if nm != Obj.magic (HxRuntime.hx_null) && HxString.equals nm expectedMainClass then ignore ((
                ignore (let __assign_132 = Obj.magic c in (
                  main := __assign_132;
                  __assign_132
                ));
                ignore (let __assign_133 = (nm : string) in (
                  mainName := __assign_133;
                  __assign_133
                ));
                raise (HxRuntime.Hx_return (Obj.repr true))
              )) else ()
            )) done);
            false
          ) in Obj.magic __fallback_result_135 with
            | HxRuntime.Hx_return __ret_134 -> Obj.obj __ret_134 in if not (tryPickMainFrom (Obj.magic enumDeclsAll)) then ignore (if not (tryPickMainFrom (Obj.magic typedefDeclsAll)) then ignore (tryPickMainFrom (Obj.magic abstractDeclsAll)) else ()) else ()) else ());
          ignore (if HxModuleDecl.getHasToplevelMain (Obj.magic nativeDecl) && expectedMainClass != Obj.magic (HxRuntime.hx_null) && HxString.length expectedMainClass > 0 then ignore (let topMain = Obj.magic (scanToplevelMainFunction (source : string)) in if topMain != Obj.magic (HxRuntime.hx_null) then ignore (let mainHasMain = ref false in (
            ignore (let _g = ref 0 in let _g1 = Obj.magic (HxClassDecl.getFunctions (Obj.magic (!main))) in try while !_g < HxArray.length _g1 do try ignore (let fn = Obj.magic (HxArray.get (Obj.magic _g1) (!_g)) in (
              ignore (let __old_136 = !_g in let __new_137 = HxInt.add __old_136 1 in (
                ignore (_g := __new_137);
                __new_137
              ));
              if HxString.equals (HxFunctionDecl.getName (Obj.magic fn)) "main" then ignore ((
                ignore (let __assign_138 = true in (
                  mainHasMain := __assign_138;
                  __assign_138
                ));
                raise (HxRuntime.Hx_break)
              )) else ()
            )) with
              | HxRuntime.Hx_continue -> () done with
              | HxRuntime.Hx_break -> ());
            if !mainName == Obj.magic (HxRuntime.hx_null) || HxString.length (!mainName) = 0 || HxString.equals (!mainName) "Unknown" || not (HxString.equals (!mainName) expectedMainClass) then ignore ((
              ignore (let __assign_139 = Obj.magic (HxClassDecl.create (expectedMainClass : string) true (Obj.magic (let __arr_140 = HxArray.create () in (
                ignore (HxArray.push __arr_140 topMain);
                __arr_140
              ))) (Obj.magic (let __arr_141 = HxArray.create () in __arr_141)) (Obj.magic (HxRuntime.hx_null))) in (
                main := __assign_139;
                __assign_139
              ));
              let __assign_142 = (expectedMainClass : string) in (
                mainName := __assign_142;
                __assign_142
              )
            )) else ignore (if not (!mainHasMain) then ignore (let functions = Obj.magic (HxArray.copy (HxClassDecl.getFunctions (Obj.magic (!main)))) in (
              ignore (HxArray.push functions topMain);
              let __assign_143 = Obj.magic (HxClassDecl.create (HxClassDecl.getName (Obj.magic (!main)) : string) true (Obj.magic functions) (Obj.magic (HxClassDecl.getFields (Obj.magic (!main)))) (HxClassDecl.getExtendsPath (Obj.magic (!main)) : string)) in (
                main := __assign_143;
                __assign_143
              )
            )) else ())
          )) else ()) else ());
          ignore (let __assign_144 = Obj.magic (patchClassStaticFlagsFromScan (Obj.magic (!main))) in (
            main := __assign_144;
            __assign_144
          ));
          let existingClasses = Obj.magic (HxArray.create ()) in (
            ignore (let _g = ref 0 in let _g1 = Obj.magic (HxModuleDecl.getClasses (Obj.magic nativeDecl)) in while !_g < HxArray.length _g1 do ignore (let c = Obj.magic (HxArray.get (Obj.magic _g1) (!_g)) in (
              ignore (let __old_145 = !_g in let __new_146 = HxInt.add __old_145 1 in (
                ignore (_g := __new_146);
                __new_146
              ));
              HxArray.push existingClasses (patchClassStaticFlagsFromScan (Obj.magic c))
            )) done);
            let existingNames = HxMap.create_string () in (
              ignore (let _g = ref 0 in while !_g < HxArray.length existingClasses do ignore (let c = Obj.magic (HxArray.get (Obj.magic existingClasses) (!_g)) in (
                ignore (let __old_147 = !_g in let __new_148 = HxInt.add __old_147 1 in (
                  ignore (_g := __new_148);
                  __new_148
                ));
                let tempMaybeString1 = ref (Obj.magic (HxRuntime.hx_null) : string) in (
                  ignore (if c == Obj.magic (HxRuntime.hx_null) then let __assign_149 = Obj.magic (Obj.magic (HxRuntime.hx_null)) in (
                    tempMaybeString1 := __assign_149;
                    __assign_149
                  ) else let __assign_150 = Obj.magic (HxClassDecl.getName (Obj.magic c) : string) in (
                    tempMaybeString1 := __assign_150;
                    __assign_150
                  ));
                  let nm = (!tempMaybeString1 : string) in if nm != Obj.magic (HxRuntime.hx_null) && HxString.length nm > 0 then ignore (HxMap.set_string existingNames nm true) else ()
                )
              )) done);
              let isMissingAndNotMain = fun c -> let tempMaybeString2 = ref (Obj.magic (HxRuntime.hx_null) : string) in (
                ignore (if c == Obj.magic (HxRuntime.hx_null) then let __assign_151 = Obj.magic (Obj.magic (HxRuntime.hx_null)) in (
                  tempMaybeString2 := __assign_151;
                  __assign_151
                ) else let __assign_152 = Obj.magic (HxClassDecl.getName (Obj.magic c) : string) in (
                  tempMaybeString2 := __assign_152;
                  __assign_152
                ));
                let nm = (!tempMaybeString2 : string) in nm != Obj.magic (HxRuntime.hx_null) && HxString.length nm > 0 && not (HxString.equals nm (!mainName)) && not (HxMap.exists_string existingNames nm)
              ) in let extras = Obj.magic (HxArray.create ()) in (
                ignore (let _g = ref 0 in let _g1 = Obj.magic (ParserStageScanHelpers.scanModuleLocalHelperClasses (source : string) (!mainName : string)) in while !_g < HxArray.length _g1 do ignore (let c = Obj.magic (HxArray.get (Obj.magic _g1) (!_g)) in (
                  ignore (let __old_153 = !_g in let __new_154 = HxInt.add __old_153 1 in (
                    ignore (_g := __new_154);
                    __new_154
                  ));
                  if isMissingAndNotMain (Obj.magic c) then ignore (HxArray.push extras c) else ()
                )) done);
                let enumDecls = Obj.magic (HxArray.create ()) in (
                  ignore (let _g = ref 0 in while !_g < HxArray.length enumDeclsAll do ignore (let c = Obj.magic (HxArray.get (Obj.magic enumDeclsAll) (!_g)) in (
                    ignore (let __old_155 = !_g in let __new_156 = HxInt.add __old_155 1 in (
                      ignore (_g := __new_156);
                      __new_156
                    ));
                    if isMissingAndNotMain (Obj.magic c) then ignore (HxArray.push enumDecls c) else ()
                  )) done);
                  let typedefDecls = Obj.magic (HxArray.create ()) in (
                    ignore (let _g = ref 0 in while !_g < HxArray.length typedefDeclsAll do ignore (let c = Obj.magic (HxArray.get (Obj.magic typedefDeclsAll) (!_g)) in (
                      ignore (let __old_157 = !_g in let __new_158 = HxInt.add __old_157 1 in (
                        ignore (_g := __new_158);
                        __new_158
                      ));
                      if isMissingAndNotMain (Obj.magic c) then ignore (HxArray.push typedefDecls c) else ()
                    )) done);
                    let abstractDecls = Obj.magic (HxArray.create ()) in (
                      ignore (let _g = ref 0 in while !_g < HxArray.length abstractDeclsAll do ignore (let c = Obj.magic (HxArray.get (Obj.magic abstractDeclsAll) (!_g)) in (
                        ignore (let __old_159 = !_g in let __new_160 = HxInt.add __old_159 1 in (
                          ignore (_g := __new_160);
                          __new_160
                        ));
                        if isMissingAndNotMain (Obj.magic c) then ignore (HxArray.push abstractDecls c) else ()
                      )) done);
                      ignore (if HxArray.length extras = 0 && HxArray.length enumDecls = 0 && HxArray.length typedefDecls = 0 && HxArray.length abstractDecls = 0 && not (!staticPatchApplied) && Obj.repr (!main) == Obj.repr (HxModuleDecl.getMainClass (Obj.magic nativeDecl)) then raise (HxRuntime.Hx_return (Obj.repr (Obj.magic nativeDecl))) else ());
                      let classes = Obj.magic (HxArray.create ()) in let seen = HxMap.create_string () in let pushUnique = fun c -> ignore (try (
                        ignore (if c == Obj.magic (HxRuntime.hx_null) then raise (HxRuntime.Hx_return (Obj.repr ())) else ());
                        let nm = (HxClassDecl.getName (Obj.magic c) : string) in (
                          ignore (if nm != Obj.magic (HxRuntime.hx_null) && HxString.length nm > 0 && HxMap.exists_string seen nm then raise (HxRuntime.Hx_return (Obj.repr ())) else ());
                          ignore (HxArray.push classes c);
                          if nm != Obj.magic (HxRuntime.hx_null) && HxString.length nm > 0 then ignore (HxMap.set_string seen nm true) else ()
                        )
                      ) with
                        | HxRuntime.Hx_return __ret_161 -> Obj.obj __ret_161) in (
                        ignore (pushUnique (Obj.magic (!main)));
                        ignore (let _g = ref 0 in while !_g < HxArray.length existingClasses do ignore (let c = Obj.magic (HxArray.get (Obj.magic existingClasses) (!_g)) in (
                          ignore (let __old_162 = !_g in let __new_163 = HxInt.add __old_162 1 in (
                            ignore (_g := __new_163);
                            __new_163
                          ));
                          pushUnique (Obj.magic c)
                        )) done);
                        ignore (let _g = ref 0 in while !_g < HxArray.length extras do ignore (let c = Obj.magic (HxArray.get (Obj.magic extras) (!_g)) in (
                          ignore (let __old_164 = !_g in let __new_165 = HxInt.add __old_164 1 in (
                            ignore (_g := __new_165);
                            __new_165
                          ));
                          pushUnique (Obj.magic c)
                        )) done);
                        ignore (let _g = ref 0 in while !_g < HxArray.length enumDecls do ignore (let c = Obj.magic (HxArray.get (Obj.magic enumDecls) (!_g)) in (
                          ignore (let __old_166 = !_g in let __new_167 = HxInt.add __old_166 1 in (
                            ignore (_g := __new_167);
                            __new_167
                          ));
                          pushUnique (Obj.magic c)
                        )) done);
                        ignore (let _g = ref 0 in while !_g < HxArray.length typedefDecls do ignore (let c = Obj.magic (HxArray.get (Obj.magic typedefDecls) (!_g)) in (
                          ignore (let __old_168 = !_g in let __new_169 = HxInt.add __old_168 1 in (
                            ignore (_g := __new_169);
                            __new_169
                          ));
                          pushUnique (Obj.magic c)
                        )) done);
                        ignore (let _g = ref 0 in while !_g < HxArray.length abstractDecls do ignore (let c = Obj.magic (HxArray.get (Obj.magic abstractDecls) (!_g)) in (
                          ignore (let __old_170 = !_g in let __new_171 = HxInt.add __old_170 1 in (
                            ignore (_g := __new_171);
                            __new_171
                          ));
                          pushUnique (Obj.magic c)
                        )) done);
                        HxModuleDecl.create (HxModuleDecl.getPackagePath (Obj.magic nativeDecl) : string) (Obj.magic (HxModuleDecl.getImports (Obj.magic nativeDecl))) (Obj.magic (!main)) (Obj.magic classes) (HxModuleDecl.getHeaderOnly (Obj.magic nativeDecl)) (HxModuleDecl.getHasToplevelMain (Obj.magic nativeDecl))
                      )
                    )
                  )
                )
              )
            )
          )
        )
      )
    )
  )
) in Obj.magic __fallback_result_173 with
  | HxRuntime.Hx_return __ret_172 -> Obj.obj __ret_172 in let v = (HxSys.getEnv "HIH_FORCE_HX_PARSER" : string) in (
  ignore (if HxString.equals v "1" || HxString.equals v "true" || HxString.equals v "yes" then let __assign_174 = Obj.magic (enrichNativeDecl (Obj.magic (HxParser.parseModule (Obj.magic (HxParser.create (source : string))) (expectedMainClass : string)))) in (
    tempHxModuleDecl := __assign_174;
    __assign_174
  ) else let fallbackAfterNativeFailure = fun nativeError -> try let __fallback_result_180 = let strict = (HxSys.getEnv "HIH_NATIVE_PARSER_STRICT" : string) in (
    ignore (if HxString.equals strict "1" || HxString.equals strict "true" || HxString.equals strict "yes" then ignore (HxType.hx_throw_typed_rtti (Obj.repr nativeError) ["Dynamic"; "String"]) else ());
    try raise (HxRuntime.Hx_return (Obj.repr (Obj.magic (enrichNativeDecl (Obj.magic (HxParser.parseModule (Obj.magic (HxParser.create (source : string))) (expectedMainClass : string))))))) with
      | HxRuntime.Hx_break -> raise (HxRuntime.Hx_break)
      | HxRuntime.Hx_continue -> raise (HxRuntime.Hx_continue)
      | HxRuntime.Hx_return __ret_175 -> raise (HxRuntime.Hx_return __ret_175)
      | HxRuntime.Hx_exception (__exn_v_176, __exn_tags_177) -> if HxRuntime.tags_has __exn_tags_177 "HxParseError" then let _hx = (Obj.obj __exn_v_176 : HxParseError.t) in (
        ignore _hx;
        HxType.hx_throw_typed_rtti (Obj.repr nativeError) ["Dynamic"; "String"]
      ) else if HxRuntime.tags_has __exn_tags_177 "String" then let _hx = (Obj.obj __exn_v_176 : string) in (
        ignore _hx;
        HxType.hx_throw_typed_rtti (Obj.repr nativeError) ["Dynamic"; "String"]
      ) else HxRuntime.hx_throw_typed __exn_v_176 __exn_tags_177
      | __exn_178 -> if HxRuntime.tags_has ["OcamlExn"] "HxParseError" then let _hx = (Obj.obj (Obj.repr __exn_178) : HxParseError.t) in (
        ignore _hx;
        HxType.hx_throw_typed_rtti (Obj.repr nativeError) ["Dynamic"; "String"]
      ) else if HxRuntime.tags_has ["OcamlExn"] "String" then let _hx = (Obj.obj (Obj.repr __exn_178) : string) in (
        ignore _hx;
        HxType.hx_throw_typed_rtti (Obj.repr nativeError) ["Dynamic"; "String"]
      ) else raise (__exn_178)
  ) in Obj.magic __fallback_result_180 with
    | HxRuntime.Hx_return __ret_179 -> Obj.obj __ret_179 in try let __assign_181 = Obj.magic (enrichNativeDecl (Obj.magic (parseViaNativeHooks (source : string) (expectedMainClass : string)))) in (
    tempHxModuleDecl := __assign_181;
    __assign_181
  ) with
    | HxRuntime.Hx_break -> raise (HxRuntime.Hx_break)
    | HxRuntime.Hx_continue -> raise (HxRuntime.Hx_continue)
    | HxRuntime.Hx_return __ret_182 -> raise (HxRuntime.Hx_return __ret_182)
    | HxRuntime.Hx_exception (__exn_v_183, __exn_tags_184) -> if HxRuntime.tags_has __exn_tags_184 "String" then let eNative = (Obj.obj __exn_v_183 : string) in (
      ignore eNative;
      let __assign_185 = Obj.magic (fallbackAfterNativeFailure (eNative : string)) in (
        tempHxModuleDecl := __assign_185;
        __assign_185
      )
    ) else HxRuntime.hx_throw_typed __exn_v_183 __exn_tags_184
    | __exn_186 -> if HxRuntime.tags_has ["OcamlExn"] "String" then let eNative = (Obj.obj (Obj.repr __exn_186) : string) in (
      ignore eNative;
      let __assign_187 = Obj.magic (fallbackAfterNativeFailure (eNative : string)) in (
        tempHxModuleDecl := __assign_187;
        __assign_187
      )
    ) else raise (__exn_186));
  let decl = Obj.magic (!tempHxModuleDecl) in let tempMaybeString3 = ref (Obj.magic (HxRuntime.hx_null) : string) in (
    ignore (if filePath == Obj.magic (HxRuntime.hx_null) || HxString.length filePath = 0 then let __assign_188 = Obj.magic ("<memory>" : string) in (
      tempMaybeString3 := __assign_188;
      __assign_188
    ) else let __assign_189 = Obj.magic (filePath : string) in (
      tempMaybeString3 := __assign_189;
      __assign_189
    ));
    let path = (!tempMaybeString3 : string) in ParsedModule.create (source : string) (Obj.magic decl) (path : string)
  )
)

let scanHelperClasses = fun source mainClassName -> ParserStageScanHelpers.scanModuleLocalHelperClasses (source : string) (mainClassName : string)

let scanHelperEnums = fun source mainTypeName -> ParserStageScanHelpers.scanModuleLocalHelperEnums (source : string) (mainTypeName : string)

let scanHelperTypedefs = fun source mainTypeName -> ParserStageScanHelpers.scanModuleLocalHelperTypedefs (source : string) (mainTypeName : string)

let scanHelperAbstracts = fun source mainTypeName -> ParserStageScanHelpers.scanModuleLocalHelperAbstracts (source : string) (mainTypeName : string)