# 1 "TypedBackendFieldReadCatalog.ml"
(* Generated by reflaxe.ocaml (WIP) *)
(* Haxe type: TypedBackendFieldReadCatalog *)

let __reflaxe_ocaml__ = ()

type t = { __hx_type : Obj.t; mutable entries : TypedBackendFieldReadProjection.t HxArray.t; mutable byProjectedName : TypedBackendFieldReadProjection.t HxMap.string_map }

let create = fun reads -> let self = ({ __hx_type = HxType.class_ "TypedBackendFieldReadCatalog"; entries = Obj.magic (HxRuntime.hx_null); byProjectedName = Obj.magic (HxRuntime.hx_null) } : t) in (
  ignore (ignore (let exactReads = Obj.magic (HxMap.create_string ()) in let names = Obj.magic (HxArray.create ()) in (
    ignore (if reads != Obj.magic (HxRuntime.hx_null) then ignore (let _g = ref 0 in while !_g < HxArray.length reads do ignore (let read = Obj.magic (HxArray.get (Obj.magic reads) (!_g)) in (
      ignore (let __old_1 = !_g in let __new_2 = HxInt.add __old_1 1 in (
        ignore (_g := __new_2);
        __new_2
      ));
      ignore (if read == Obj.magic (HxRuntime.hx_null) then ignore (HxType.hx_throw_typed_rtti (Obj.repr "typed backend field-read catalog cannot contain a null projection") ["Dynamic"]) else ());
      let name = (TypedBackendFieldReadProjection.getProjectedName (Obj.magic read) () : string) in let existing = Obj.magic (HxMap.get_string (Obj.magic exactReads) (name : string)) in if existing == Obj.magic (HxRuntime.hx_null) then ignore ((
        ignore (HxMap.set_string (Obj.magic exactReads) (name : string) read);
        HxArray.push names name
      )) else ignore (if not (HxString.equals (TypedBackendFieldReadProjection.getCanonicalIdentity (Obj.magic existing) ()) (TypedBackendFieldReadProjection.getCanonicalIdentity (Obj.magic read) ())) then ignore (HxType.hx_throw_typed_rtti (Obj.repr ("conflicting typed field-read facts for transport name " ^ HxString.toStdString name)) ["Dynamic"]) else ())
    )) done) else ());
    ignore (HxArray.sort names (fun left right -> HxReflect.compare (Obj.repr left) (Obj.repr right)));
    ignore (let __assign_3 = Obj.magic (let __arr_4 = HxArray.create () in __arr_4) in (
      (Obj.magic self : t).entries <- __assign_3;
      __assign_3
    ));
    ignore (let __assign_5 = Obj.magic (HxMap.create_string ()) in (
      (Obj.magic self : t).byProjectedName <- __assign_5;
      __assign_5
    ));
    let _g = ref 0 in while !_g < HxArray.length names do ignore (let name = (HxArray.get (Obj.magic names) (!_g) : string) in (
      ignore (let __old_6 = !_g in let __new_7 = HxInt.add __old_6 1 in (
        ignore (_g := __new_7);
        __new_7
      ));
      let read = Obj.magic (HxMap.get_string (Obj.magic exactReads) (name : string)) in (
        ignore (if read == Obj.magic (HxRuntime.hx_null) then ignore (HxType.hx_throw_typed_rtti (Obj.repr "typed backend field-read catalog lost a normalized projection") ["Dynamic"]) else ());
        ignore (HxArray.push ((Obj.magic self : t).entries) read);
        let _this = Obj.magic ((Obj.magic self : t).byProjectedName) in HxMap.set_string (Obj.magic _this) (name : string) read
      )
    )) done
  )));
  self
)

let __empty = fun () -> ({ __hx_type = HxType.class_ "TypedBackendFieldReadCatalog"; entries = Obj.magic (HxRuntime.hx_null); byProjectedName = Obj.magic (HxRuntime.hx_null) } : t)

let getEntries = fun self () -> HxArray.copy ((Obj.magic self : t).entries)

let getReservedProjectedNames = fun self () -> let _g = Obj.magic (let __arr_8 = HxArray.create () in __arr_8) in let _g1 = ref 0 in let _g2 = Obj.magic ((Obj.magic self : t).entries) in (
  ignore (while !_g1 < HxArray.length _g2 do ignore (let entry = Obj.magic (HxArray.get (Obj.magic _g2) (!_g1)) in (
    ignore (let __old_9 = !_g1 in let __new_10 = HxInt.add __old_9 1 in (
      ignore (_g1 := __new_10);
      __new_10
    ));
    HxArray.push _g (TypedBackendFieldReadProjection.getProjectedName (Obj.magic entry) ())
  )) done);
  _g
)

let findByProjectedName = fun self (projectedName : string) -> let tempResult = ref (Obj.magic (HxRuntime.hx_null) : TypedBackendFieldReadProjection.t) in (
  ignore (if projectedName == HxString.hx_null_string then let __assign_11 = Obj.magic (Obj.magic (Obj.magic (HxRuntime.hx_null))) in (
    tempResult := __assign_11;
    __assign_11
  ) else let _this = Obj.magic ((Obj.magic self : t).byProjectedName) in let __assign_12 = Obj.magic (Obj.magic (HxMap.get_string (Obj.magic _this) (projectedName : string))) in (
    tempResult := __assign_12;
    __assign_12
  ));
  !tempResult
)