(* Generated by reflaxe.ocaml (WIP) *)
(* Haxe type: TyperIndex *)

let __reflaxe_ocaml__ = ()

type t = { __hx_type : Obj.t; mutable byFullName : TyClassInfo.t HxMap.string_map; mutable byShortName : TyClassInfo.t HxArray.t HxMap.string_map }

let create = fun () -> let self = ({ __hx_type = HxType.class_ "TyperIndex"; byFullName = Obj.magic (HxRuntime.hx_null); byShortName = Obj.magic (HxRuntime.hx_null) } : t) in (
  ignore (ignore ((
    ignore (let __assign_1 = Obj.magic (HxMap.create_string ()) in (
      (Obj.magic self : t).byFullName <- __assign_1;
      __assign_1
    ));
    let __assign_2 = Obj.magic (HxMap.create_string ()) in (
      (Obj.magic self : t).byShortName <- __assign_2;
      __assign_2
    )
  )));
  self
)

let __empty = fun () -> ({ __hx_type = HxType.class_ "TyperIndex"; byFullName = Obj.magic (HxRuntime.hx_null); byShortName = Obj.magic (HxRuntime.hx_null) } : t)

let getByFullName = fun self (fullName : string) -> let tempResult = ref (Obj.magic (HxRuntime.hx_null) : TyClassInfo.t) in (
  ignore (if HxMap.exists_string ((Obj.magic self : t).byFullName) fullName then let __assign_3 = Obj.magic (Obj.magic (HxMap.get_string ((Obj.magic self : t).byFullName) fullName)) in (
    tempResult := __assign_3;
    __assign_3
  ) else let __assign_4 = Obj.magic (Obj.magic (Obj.magic (HxRuntime.hx_null))) in (
    tempResult := __assign_4;
    __assign_4
  ));
  !tempResult
)

let getByShortName = fun self (shortName : string) -> let tempResult = ref (Obj.magic (HxRuntime.hx_null) : TyClassInfo.t HxArray.t) in (
  ignore (if HxMap.exists_string ((Obj.magic self : t).byShortName) shortName then let __assign_5 = Obj.magic (HxMap.get_string ((Obj.magic self : t).byShortName) shortName) in (
    tempResult := __assign_5;
    __assign_5
  ) else let __assign_6 = Obj.magic (let __arr_7 = HxArray.create () in __arr_7) in (
    tempResult := __assign_6;
    __assign_6
  ));
  !tempResult
)

let addClass = fun self (info : TyClassInfo.t) -> ignore (ignore (try (
  ignore (if info == Obj.magic (HxRuntime.hx_null) then raise (HxRuntime.Hx_return (Obj.repr ())) else ());
  let fullName = (TyClassInfo.getFullName (Obj.magic info) () : string) in (
    ignore (HxMap.set_string ((Obj.magic self : t).byFullName) fullName info);
    let shortName = (TyClassInfo.getShortName (Obj.magic info) () : string) in let tempMaybeArray = ref (Obj.magic (HxRuntime.hx_null) : TyClassInfo.t HxArray.t) in (
      ignore (if HxMap.exists_string ((Obj.magic self : t).byShortName) shortName then let __assign_8 = Obj.magic (Obj.magic (HxMap.get_string ((Obj.magic self : t).byShortName) shortName)) in (
        tempMaybeArray := __assign_8;
        __assign_8
      ) else let __assign_9 = Obj.magic (Obj.magic (let __arr_10 = HxArray.create () in __arr_10)) in (
        tempMaybeArray := __assign_9;
        __assign_9
      ));
      let arr = Obj.magic (!tempMaybeArray) in (
        ignore (HxArray.push arr info);
        HxMap.set_string ((Obj.magic self : t).byShortName) shortName arr
      )
    )
  )
) with
  | HxRuntime.Hx_return __ret_11 -> Obj.obj __ret_11))

let resolveTypePath = fun self (typePath : string) (packagePath : string) (imports : string HxArray.t) -> try let __fallback_result_22 = (
  ignore (if typePath == Obj.magic (HxRuntime.hx_null) then raise (HxRuntime.Hx_return (Obj.repr (Obj.magic (Obj.magic (HxRuntime.hx_null))))) else ());
  let raw = (StringTools.trim (typePath : string) : string) in (
    ignore (if HxString.length raw = 0 then raise (HxRuntime.Hx_return (Obj.repr (Obj.magic (Obj.magic (HxRuntime.hx_null))))) else ());
    ignore (if HxString.indexOf raw "." 0 >= 0 then ignore (let direct = Obj.magic (getByFullName (Obj.magic self) (raw : string)) in if direct != Obj.magic (HxRuntime.hx_null) then raise (HxRuntime.Hx_return (Obj.repr (Obj.magic direct))) else ()) else ());
    ignore (if imports != Obj.magic (HxRuntime.hx_null) then ignore (let _g = ref 0 in try while !_g < HxArray.length imports do try ignore (let imp = (HxArray.get (Obj.magic imports) (!_g) : string) in (
      ignore (let __old_12 = !_g in let __new_13 = HxInt.add __old_12 1 in (
        ignore (_g := __new_13);
        __new_13
      ));
      ignore (if imp == Obj.magic (HxRuntime.hx_null) || HxString.length imp = 0 then raise (HxRuntime.Hx_continue) else ());
      let parts = Obj.magic (HxString.split imp ".") in let tempString = ref ("" : string) in (
        ignore (if HxArray.length parts = 0 then let __assign_14 = ("" : string) in (
          tempString := __assign_14;
          __assign_14
        ) else let __assign_15 = (HxArray.get (Obj.magic parts) (HxInt.sub (HxArray.length parts) 1) : string) in (
          tempString := __assign_15;
          __assign_15
        ));
        let last = (!tempString : string) in if HxString.equals last raw then ignore (let hit = Obj.magic (getByFullName (Obj.magic self) (imp : string)) in if hit != Obj.magic (HxRuntime.hx_null) then raise (HxRuntime.Hx_return (Obj.repr (Obj.magic hit))) else ()) else ()
      )
    )) with
      | HxRuntime.Hx_continue -> () done with
      | HxRuntime.Hx_break -> ()) else ());
    let tempString1 = ref ("" : string) in (
      ignore (if packagePath == Obj.magic (HxRuntime.hx_null) then let __assign_16 = ("" : string) in (
        tempString1 := __assign_16;
        __assign_16
      ) else let __assign_17 = (StringTools.trim (packagePath : string) : string) in (
        tempString1 := __assign_17;
        __assign_17
      ));
      ignore (if HxString.length (!tempString1) > 0 then ignore (let cur = ref (!tempString1 : string) in try while true do try ignore (let candidate = ((HxString.toStdString (!cur) ^ ".") ^ HxString.toStdString raw : string) in let hit = Obj.magic (getByFullName (Obj.magic self) (candidate : string)) in (
        ignore (if hit != Obj.magic (HxRuntime.hx_null) then raise (HxRuntime.Hx_return (Obj.repr (Obj.magic hit))) else ());
        let lastDot = HxString.lastIndexOf (!cur) "." (HxString.length (!cur)) in (
          ignore (if lastDot < 0 then raise (HxRuntime.Hx_break) else ());
          let __assign_18 = (HxString.substr (!cur) 0 lastDot : string) in (
            cur := __assign_18;
            __assign_18
          )
        )
      )) with
        | HxRuntime.Hx_continue -> () done with
        | HxRuntime.Hx_break -> ()) else ());
      let alts = Obj.magic (getByShortName (Obj.magic self) (raw : string)) in let tempResult = ref (Obj.magic (HxRuntime.hx_null) : TyClassInfo.t) in (
        ignore (if HxArray.length alts = 1 then let __assign_19 = Obj.magic (Obj.magic (HxArray.get (Obj.magic alts) 0)) in (
          tempResult := __assign_19;
          __assign_19
        ) else let __assign_20 = Obj.magic (Obj.magic (Obj.magic (HxRuntime.hx_null))) in (
          tempResult := __assign_20;
          __assign_20
        ));
        !tempResult
      )
    )
  )
) in Obj.magic __fallback_result_22 with
  | HxRuntime.Hx_return __ret_21 -> Obj.obj __ret_21

let classFullName = fun pkg cls -> let tempString = ref ("" : string) in (
  ignore (if pkg == Obj.magic (HxRuntime.hx_null) then let __assign_23 = ("" : string) in (
    tempString := __assign_23;
    __assign_23
  ) else let __assign_24 = (StringTools.trim (pkg : string) : string) in (
    tempString := __assign_24;
    __assign_24
  ));
  let tempResult = ref ("" : string) in (
    ignore (if HxString.length (!tempString) = 0 then let __assign_25 = (cls : string) in (
      tempResult := __assign_25;
      __assign_25
    ) else let __assign_26 = ((HxString.toStdString (!tempString) ^ ".") ^ HxString.toStdString cls : string) in (
      tempResult := __assign_26;
      __assign_26
    ));
    !tempResult
  )
)

let expectedModuleNameFromFile = fun filePath -> try let __fallback_result_30 = (
  ignore (if filePath == Obj.magic (HxRuntime.hx_null) || HxString.length filePath = 0 then raise (HxRuntime.Hx_return (Obj.repr (Obj.magic (HxRuntime.hx_null)))) else ());
  let name = (Haxe_io_Path.withoutDirectory (filePath : string) : string) in let dot = HxString.lastIndexOf name "." (HxString.length name) in let tempResult = ref (Obj.magic (HxRuntime.hx_null) : string) in (
    ignore (if dot <= 0 then let __assign_27 = Obj.magic (name : string) in (
      tempResult := __assign_27;
      __assign_27
    ) else let __assign_28 = Obj.magic (HxString.substr name 0 dot : string) in (
      tempResult := __assign_28;
      __assign_28
    ));
    !tempResult
  )
) in Obj.magic __fallback_result_30 with
  | HxRuntime.Hx_return __ret_29 -> Obj.obj __ret_29

let classFullNameInModule = fun pkg moduleName clsName -> let tempString = ref ("" : string) in (
  ignore (if pkg == Obj.magic (HxRuntime.hx_null) then let __assign_31 = ("" : string) in (
    tempString := __assign_31;
    __assign_31
  ) else let __assign_32 = (StringTools.trim (pkg : string) : string) in (
    tempString := __assign_32;
    __assign_32
  ));
  let tempString1 = ref ("" : string) in (
    ignore (if moduleName == Obj.magic (HxRuntime.hx_null) then let __assign_33 = ("" : string) in (
      tempString1 := __assign_33;
      __assign_33
    ) else let __assign_34 = (StringTools.trim (moduleName : string) : string) in (
      tempString1 := __assign_34;
      __assign_34
    ));
    let tempString2 = ref ("" : string) in (
      ignore (if HxString.length (!tempString1) = 0 || HxString.equals (!tempString1) "Unknown" then let __assign_35 = ("" : string) in (
        tempString2 := __assign_35;
        __assign_35
      ) else let __assign_36 = (!tempString1 : string) in (
        tempString2 := __assign_36;
        __assign_36
      ));
      let tempString3 = ref ("" : string) in (
        ignore (if clsName == Obj.magic (HxRuntime.hx_null) then let __assign_37 = ("" : string) in (
          tempString3 := __assign_37;
          __assign_37
        ) else let __assign_38 = (StringTools.trim (clsName : string) : string) in (
          tempString3 := __assign_38;
          __assign_38
        ));
        ignore (if HxString.length (!tempString2) > 0 && HxString.length (!tempString3) > 0 && not (HxString.equals (!tempString3) (!tempString2)) then ignore (let tempRight = ref ("" : string) in (
          ignore (if HxString.length (!tempString) = 0 then let __assign_39 = (!tempString2 : string) in (
            tempRight := __assign_39;
            __assign_39
          ) else let __assign_40 = ((HxString.toStdString (!tempString) ^ ".") ^ HxString.toStdString (!tempString2) : string) in (
            tempRight := __assign_40;
            __assign_40
          ));
          let __assign_41 = (!tempRight : string) in (
            tempString := __assign_41;
            __assign_41
          )
        )) else ());
        let tempResult = ref ("" : string) in (
          ignore (if HxString.length (!tempString) = 0 then let __assign_42 = (!tempString3 : string) in (
            tempResult := __assign_42;
            __assign_42
          ) else let __assign_43 = ((HxString.toStdString (!tempString) ^ ".") ^ HxString.toStdString (!tempString3) : string) in (
            tempResult := __assign_43;
            __assign_43
          ));
          !tempResult
        )
      )
    )
  )
)

let build = fun resolved -> try let __fallback_result_57 = let idx = Obj.magic (create ()) in (
  ignore (if resolved == Obj.magic (HxRuntime.hx_null) then raise (HxRuntime.Hx_return (Obj.repr (Obj.magic idx))) else ());
  let _g = ref 0 in (
    ignore (while !_g < HxArray.length resolved do ignore (let m = Obj.magic (HxArray.get (Obj.magic resolved) (!_g)) in (
      ignore (let __old_44 = !_g in let __new_45 = HxInt.add __old_44 1 in (
        ignore (_g := __new_45);
        __new_45
      ));
      let pm = Obj.magic (ResolvedModule.getParsed (Obj.magic m)) in let decl = Obj.magic (ParsedModule.getDecl (Obj.magic pm) ()) in let pkg = (HxModuleDecl.getPackagePath (Obj.magic decl) : string) in let moduleName = (expectedModuleNameFromFile (ResolvedModule.getFilePath (Obj.magic m) : string) : string) in let _g2 = ref 0 in let _g1 = Obj.magic (HxModuleDecl.getClasses (Obj.magic decl)) in try while !_g2 < HxArray.length _g1 do try ignore (let cls = Obj.magic (HxArray.get (Obj.magic _g1) (!_g2)) in (
        ignore (let __old_46 = !_g2 in let __new_47 = HxInt.add __old_46 1 in (
          ignore (_g2 := __new_47);
          __new_47
        ));
        let clsName = (HxClassDecl.getName (Obj.magic cls) : string) in (
          ignore (if clsName == Obj.magic (HxRuntime.hx_null) || HxString.length clsName = 0 || HxString.equals clsName "Unknown" then raise (HxRuntime.Hx_continue) else ());
          let full = (classFullNameInModule (pkg : string) (moduleName : string) (clsName : string) : string) in let fields = Obj.magic (HxMap.create_string ()) in (
            ignore (let _g3 = ref 0 in let _g4 = Obj.magic (HxClassDecl.getFields (Obj.magic cls)) in while !_g3 < HxArray.length _g4 do ignore (let f = Obj.magic (HxArray.get (Obj.magic _g4) (!_g3)) in (
              ignore (let __old_48 = !_g3 in let __new_49 = HxInt.add __old_48 1 in (
                ignore (_g3 := __new_49);
                __new_49
              ));
              HxMap.set_string fields (HxFieldDecl.getName (Obj.magic f)) (TyType.fromHintText (HxFieldDecl.getTypeHint (Obj.magic f) : string))
            )) done);
            let statics = Obj.magic (HxMap.create_string ()) in let instances = Obj.magic (HxMap.create_string ()) in (
              ignore (let _g3 = ref 0 in let _g4 = Obj.magic (HxClassDecl.getFunctions (Obj.magic cls)) in while !_g3 < HxArray.length _g4 do ignore (let fn = Obj.magic (HxArray.get (Obj.magic _g4) (!_g3)) in (
                ignore (let __old_50 = !_g3 in let __new_51 = HxInt.add __old_50 1 in (
                  ignore (_g3 := __new_51);
                  __new_51
                ));
                let fnName = (HxFunctionDecl.getName (Obj.magic fn) : string) in let isStatic = HxFunctionDecl.getIsStatic (Obj.magic fn) in let args = Obj.magic (HxArray.create ()) in (
                  ignore (let _g5 = ref 0 in let _g6 = Obj.magic (HxFunctionDecl.getArgs (Obj.magic fn)) in while !_g5 < HxArray.length _g6 do ignore (let a = Obj.magic (HxArray.get (Obj.magic _g6) (!_g5)) in (
                    ignore (let __old_52 = !_g5 in let __new_53 = HxInt.add __old_52 1 in (
                      ignore (_g5 := __new_53);
                      __new_53
                    ));
                    HxArray.push args (TyType.fromHintText (HxFunctionArg.getTypeHint (Obj.magic a) : string))
                  )) done);
                  let retHint = (HxFunctionDecl.getReturnTypeHint (Obj.magic fn) : string) in let tempTyType = ref (Obj.magic (HxRuntime.hx_null) : TyType.t) in (
                    ignore (if HxString.equals fnName "new" then let __assign_54 = Obj.magic (TyType.fromHintText (full : string)) in (
                      tempTyType := __assign_54;
                      __assign_54
                    ) else let __assign_55 = Obj.magic (TyType.fromHintText (retHint : string)) in (
                      tempTyType := __assign_55;
                      __assign_55
                    ));
                    let ret = Obj.magic (!tempTyType) in let hx_sig = Obj.magic (TyFunSig.create (fnName : string) isStatic (Obj.magic args) (Obj.magic ret)) in if isStatic then ignore (HxMap.set_string statics fnName hx_sig) else ignore (HxMap.set_string instances fnName hx_sig)
                  )
                )
              )) done);
              addClass (Obj.magic idx) (Obj.magic (TyClassInfo.create (full : string) (clsName : string) (ResolvedModule.getModulePath (Obj.magic m) : string) (Obj.magic fields) (Obj.magic statics) (Obj.magic instances)))
            )
          )
        )
      )) with
        | HxRuntime.Hx_continue -> () done with
        | HxRuntime.Hx_break -> ()
    )) done);
    idx
  )
) in Obj.magic __fallback_result_57 with
  | HxRuntime.Hx_return __ret_56 -> Obj.obj __ret_56