package backend.cpp;

import backend.BackendContext;
import backend.EmitArtifact;
import backend.EmitResult;
import backend.GenIrProgram;
import haxe.io.Path;

typedef CppAnonStruct = {
	var name:String;
	var fieldNames:Array<String>;
	var fieldTypes:Array<String>;
}

/**
	Small native C++ source-emission target core.

	Why
	- Full1 Cpp evidence now reaches Stage3 target dispatch after hxcpp's Neko
	  helper-tool path succeeds. The next useful seam is not another placeholder;
	  it is a concrete target core that can emit and optionally build the smallest
	  C++ artifact.
	- This must not pretend to be hxcpp parity. Unsupported Haxe semantics should
	  fail with C++-specific diagnostics until they are implemented deliberately.

	What
	- Emits one `src/<Main>.cpp` for a static `main`.
	- Supports a tiny smoke subset: blocks, local vars, `Sys.println(...)`,
	  literals, identifiers, `Std.string(...)`, and `+` concatenation/arithmetic.
	- If build is requested and `-D no-compilation` is absent, invokes a local C++
	  compiler (`c++`, `g++`, or `clang++`) to produce an executable.

	How
	- Keep this target independent from `SourceTargetCommon`; C++/hxcpp will need
	  different runtime and packaging rules from Python/C#/Lua/PHP.
	- Grow support one focused CI blocker at a time, with repo-local coverage
	  before rerunning the upstream-derived Cpp gate.
**/
class CppTargetCore {
	public static function emit(program:GenIrProgram, context:BackendContext):EmitResult {
		final main = mainModule(program, context);
		final className = sanitizeIdentifier(HxClassDecl.getName(main.cls));
		final sourceDir = Path.join([context.outputDir, "src"]);
		final sourcePath = context.outputFileHint != null
			&& context.outputFileHint.length > 0 ? context.outputFileHint : Path.join([sourceDir, className + ".cpp"]);
		ensureParentDirectory(sourcePath);
		sys.io.File.saveContent(sourcePath, renderProgram(program, main));

		if (context.buildExecutable && !context.hasDefine("no-compilation")) {
			final exePath = executablePath(context.outputDir, className);
			ensureParentDirectory(exePath);
			final compiler = cppCompilerCommand();
			if (compiler == null)
				throw "C++ source backend MVP executable packaging requires `c++`, `g++`, or `clang++` on PATH";
			final code = Sys.command(compiler, ["-std=c++17", sourcePath, "-o", exePath]);
			if (code != 0)
				throw "C++ source backend MVP executable packaging failed with exit code " + code;
			return new EmitResult(exePath, [
				new EmitArtifact("entry_cpp_source", sourcePath),
				new EmitArtifact("entry_cpp_exe", exePath)
			], true);
		}

		return new EmitResult(sourcePath, [new EmitArtifact("entry_cpp_source", sourcePath)], false);
	}

	static function findMainModule(program:GenIrProgram, context:BackendContext):Null<{decl:HxModuleDecl, cls:HxClassDecl, fn:HxFunctionDecl}> {
		final wanted = context.mainModule == null ? "" : context.mainModule;
		var fallback:Null<{decl:HxModuleDecl, cls:HxClassDecl, fn:HxFunctionDecl}> = null;
		for (typed in program.getTypedModules()) {
			final decl = typed.getParsed().getDecl();
			final pkg = HxModuleDecl.getPackagePath(decl);
			for (cls in HxModuleDecl.getClasses(decl)) {
				final clsName = HxClassDecl.getName(cls);
				final fullName = pkg == null || pkg.length == 0 ? clsName : pkg + "." + clsName;
				for (fn in HxClassDecl.getFunctions(cls)) {
					if (HxFunctionDecl.getIsStatic(fn) && HxFunctionDecl.getName(fn) == "main") {
						final found = {decl: decl, cls: cls, fn: fn};
						if (fallback == null)
							fallback = found;
						if (wanted.length == 0 || wanted == clsName || wanted == fullName)
							return found;
					}
				}
			}
		}
		return fallback;
	}

	static function mainModule(program:GenIrProgram, context:BackendContext):{decl:HxModuleDecl, cls:HxClassDecl, fn:HxFunctionDecl} {
		final found = findMainModule(program, context);
		if (found == null)
			throw "C++ source backend MVP requires a static main entrypoint";
		return found;
	}

	static function renderProgram(program:GenIrProgram, main:{decl:HxModuleDecl, cls:HxClassDecl, fn:HxFunctionDecl}):String {
		final className = sanitizeIdentifier(HxClassDecl.getName(main.cls));
		final out = new Array<String>();
		out.push("// Generated by hxhx Stage3 C++ source backend MVP");
		out.push("#include <iostream>");
		out.push("#include <string>");
		out.push("#include <vector>");
		out.push("");
		out.push("static std::vector<std::string> __hxhx_args(int argc, char** argv) {");
		out.push("  std::vector<std::string> out;");
		out.push("  for (int i = 1; i < argc; ++i) out.push_back(std::string(argv[i]));");
		out.push("  return out;");
		out.push("}");
		out.push("");
		out.push("static int __hxhx_index_of(const std::string& source, const std::string& needle, int start) {");
		out.push("  auto pos = source.find(needle, start < 0 ? 0 : static_cast<std::size_t>(start));");
		out.push("  return pos == std::string::npos ? -1 : static_cast<int>(pos);");
		out.push("}");
		out.push("");
		out.push("static int __hxhx_index_of(const std::vector<std::string>& values, const std::string& needle, int start) {");
		out.push("  int begin = start < 0 ? 0 : start;");
		out.push("  for (int i = begin; i < static_cast<int>(values.size()); ++i) if (values[i] == needle) return i;");
		out.push("  return -1;");
		out.push("}");
		out.push("");
		for (decl in renderAnonStructs(collectAnonStructs(program))) {
			for (line in decl)
				out.push(line);
			out.push("");
		}
		for (decl in renderHelperClasses(program, main.cls)) {
			for (line in decl)
				out.push(line);
			out.push("");
		}
		out.push("int main(int argc, char** argv) {");
		out.push("  (void)argc;");
		out.push("  (void)argv;");
		for (line in renderStmts(HxFunctionDecl.getBody(main.fn), "  "))
			out.push(line);
		out.push("  return 0;");
		out.push("}");
		return out.join("\n") + "\n";
	}

	/**
		Collects anonymous-object aggregate shapes before C++ source emission.

		Why
		- C++ needs a concrete type before code can declare `auto info = ...` and
		  later read `info.field`.
		- A dynamic anonymous-object runtime would be too broad for this Full1
		  burn-down seam, so the MVP emits one small aggregate struct per field
		  signature.

		What/How
		- Walks the parsed program for `EAnon` literals, including nested values.
		- Emits nested anonymous structs before their parents so field types are
		  declared in dependency order.
		- Infers only the tiny type subset the Cpp MVP already knows how to print;
		  unsupported dynamic behavior should remain a later explicit seam.
	**/
	static function collectAnonStructs(program:GenIrProgram):Array<CppAnonStruct> {
		final out = new Array<CppAnonStruct>();
		final seen = new haxe.ds.StringMap<Bool>();
		function addExpr(expr:HxExpr):Void {
			switch (expr) {
				case EAnon(fieldNames, fieldValues):
					for (value in fieldValues)
						addExpr(value);
					final struct = anonStruct(fieldNames, fieldValues);
					if (!seen.exists(struct.name)) {
						seen.set(struct.name, true);
						out.push(struct);
					}
				case EField(receiver, _):
					addExpr(receiver);
				case ECall(callee, args):
					addExpr(callee);
					for (arg in args)
						addExpr(arg);
				case EArrayDecl(values):
					for (value in values)
						addExpr(value);
				case EArrayAccess(array, index):
					addExpr(array);
					addExpr(index);
				case EBinop(_, left, right):
					addExpr(left);
					addExpr(right);
				case EUnop(_, inner):
					addExpr(inner);
				case ETernary(cond, thenExpr, elseExpr):
					addExpr(cond);
					addExpr(thenExpr);
					addExpr(elseExpr);
				case ENew(_, args):
					for (arg in args)
						addExpr(arg);
				case ECast(inner, _) | EUntyped(inner):
					addExpr(inner);
				case ESwitch(scrutinee, _, exprs):
					addExpr(scrutinee);
					for (expr in exprs)
						addExpr(expr);
				case EArrayComprehension(_, iterable, guardExpr, yieldExpr):
					addExpr(iterable);
					if (guardExpr != null)
						addExpr(guardExpr);
					addExpr(yieldExpr);
				case EMacroExpr(inner, _):
					addExpr(inner);
				case _:
			}
		}
		function addStmt(stmt:HxStmt):Void {
			switch (stmt) {
				case SBlock(stmts, _):
					for (s in stmts)
						addStmt(s);
				case SVar(_, _, init, _):
					if (init != null)
						addExpr(init);
				case SIf(cond, thenBranch, elseBranch, _):
					addExpr(cond);
					addStmt(thenBranch);
					if (elseBranch != null)
						addStmt(elseBranch);
				case SExpr(expr, _) | SReturn(expr, _):
					addExpr(expr);
				case SForIn(_, iterable, body, _):
					addExpr(iterable);
					addStmt(body);
				case SForKeyValue(_, _, iterable, body, _):
					addExpr(iterable);
					addStmt(body);
				case SWhile(cond, body, _):
					addExpr(cond);
					addStmt(body);
				case SDoWhile(body, cond, _):
					addStmt(body);
					addExpr(cond);
				case SSwitch(scrutinee, _, bodies, _):
					addExpr(scrutinee);
					for (body in bodies)
						addStmt(body);
				case STry(tryBody, catches, _):
					addStmt(tryBody);
					for (c in catches)
						addStmt(c.body);
				case SThrow(expr, _):
					addExpr(expr);
				case SReturnVoid(_) | SBreak(_) | SContinue(_):
			}
		}
		for (typed in program.getTypedModules()) {
			final decl = typed.getParsed().getDecl();
			for (cls in HxModuleDecl.getClasses(decl)) {
				for (field in HxClassDecl.getFields(cls)) {
					final init = HxFieldDecl.getInit(field);
					if (init != null)
						addExpr(init);
				}
				for (fn in HxClassDecl.getFunctions(cls))
					for (stmt in HxFunctionDecl.getBody(fn))
						addStmt(stmt);
			}
		}
		return out;
	}

	static function renderAnonStructs(structs:Array<CppAnonStruct>):Array<Array<String>> {
		final out = new Array<Array<String>>();
		for (struct in structs) {
			final lines = ["struct " + struct.name + " {"];
			for (i in 0...struct.fieldNames.length)
				lines.push("  " + struct.fieldTypes[i] + " " + sanitizeIdentifier(struct.fieldNames[i]) + ";");
			lines.push("};");
			out.push(lines);
		}
		return out;
	}

	static function anonStruct(fieldNames:Array<String>, fieldValues:Array<HxExpr>):CppAnonStruct {
		final count = fieldNames.length < fieldValues.length ? fieldNames.length : fieldValues.length;
		final names = new Array<String>();
		final types = new Array<String>();
		for (i in 0...count) {
			names.push(fieldNames[i]);
			types.push(cppAnonFieldType(fieldValues[i]));
		}
		return {name: anonStructName(names, types), fieldNames: names, fieldTypes: types};
	}

	static function anonStructName(fieldNames:Array<String>, fieldTypes:Array<String>):String {
		final parts = ["__hxhx_anon"];
		for (i in 0...fieldNames.length)
			parts.push(sanitizeIdentifier(fieldNames[i]) + "_" + sanitizeTypePath(fieldTypes[i]));
		return parts.join("_");
	}

	static function cppAnonFieldType(expr:HxExpr):String {
		return switch (expr) {
			case EString(_):
				"std::string";
			case EFloat(_):
				"double";
			case EBool(_):
				"bool";
			case EArrayDecl(elements):
				"std::vector<" + arrayElementType(elements) + ">";
			case EAnon(fieldNames, fieldValues):
				final struct = anonStruct(fieldNames, fieldValues);
				struct.name;
			case _:
				"int";
		};
	}

	static function renderHelperClasses(program:GenIrProgram, mainClass:HxClassDecl):Array<Array<String>> {
		final out = new Array<Array<String>>();
		final emitted = new haxe.ds.StringMap<Bool>();
		final mainName = HxClassDecl.getName(mainClass);
		for (typed in program.getTypedModules()) {
			final decl = typed.getParsed().getDecl();
			for (cls in HxModuleDecl.getClasses(decl)) {
				final rawName = HxClassDecl.getName(cls);
				if (rawName == mainName || emitted.exists(rawName) || HxClassDecl.getIsInterface(cls))
					continue;
				emitted.set(rawName, true);
				out.push(renderHelperClass(cls));
			}
		}
		return out;
	}

	static function renderHelperClass(cls:HxClassDecl):Array<String> {
		final className = sanitizeTypePath(HxClassDecl.getName(cls));
		final out = ["struct " + className + " {"];
		for (field in HxClassDecl.getFields(cls)) {
			if (HxFieldDecl.getIsStatic(field))
				continue;
			final typeName = cppTypeHint(HxFieldDecl.getTypeHint(field));
			final init = HxFieldDecl.getInit(field);
			final rhs = init == null ? cppDefaultValue(typeName) : renderExpr(init);
			out.push("  " + typeName + " " + sanitizeIdentifier(HxFieldDecl.getName(field)) + " = " + rhs + ";");
		}
		final ctor = findConstructor(cls);
		if (ctor == null) {
			out.push("  " + className + "() {}");
		} else {
			out.push("  " + className + "(" + renderFunctionArgs(HxFunctionDecl.getArgs(ctor)) + ") {");
			for (line in renderStmts(HxFunctionDecl.getBody(ctor), "    "))
				out.push(line);
			out.push("  }");
		}
		for (fn in HxClassDecl.getFunctions(cls)) {
			if (HxFunctionDecl.getIsStatic(fn) || HxFunctionDecl.getName(fn) == "new")
				continue;
			for (line in renderHelperMethod(fn))
				out.push(line);
		}
		out.push("};");
		return out;
	}

	static function renderHelperMethod(fn:HxFunctionDecl):Array<String> {
		final returnType = cppTypeHint(HxFunctionDecl.getReturnTypeHint(fn));
		final out = ["  "
			+ returnType
			+ " "
			+ sanitizeIdentifier(HxFunctionDecl.getName(fn))
			+ "("
			+ renderFunctionArgs(HxFunctionDecl.getArgs(fn))
			+ ") {"];
		for (line in renderStmts(HxFunctionDecl.getBody(fn), "    "))
			out.push(line);
		out.push("  }");
		return out;
	}

	static function findConstructor(cls:HxClassDecl):Null<HxFunctionDecl> {
		for (fn in HxClassDecl.getFunctions(cls))
			if (!HxFunctionDecl.getIsStatic(fn) && HxFunctionDecl.getName(fn) == "new")
				return fn;
		return null;
	}

	static function renderFunctionArgs(args:Array<HxFunctionArg>):String {
		return [
			for (arg in args)
				cppTypeHint(HxFunctionArg.getTypeHint(arg)) + " " + sanitizeIdentifier(HxFunctionArg.getName(arg))
		].join(", ");
	}

	static function renderStmts(stmts:Array<HxStmt>, indent:String):Array<String> {
		final out = new Array<String>();
		for (stmt in stmts) {
			for (line in renderStmt(stmt, indent))
				out.push(line);
		}
		return out;
	}

	static function renderStmt(stmt:HxStmt, indent:String):Array<String> {
		return switch (stmt) {
			case SBlock(stmts, _):
				final out = [indent + "{"];
				for (line in renderStmts(stmts, indent + "  "))
					out.push(line);
				out.push(indent + "}");
				out;
			case SIf(cond, thenBranch, elseBranch, _):
				final out = [indent + "if " + conditionExpr(cond) + " {"];
				for (line in renderStmtBlockContent(thenBranch, indent + "  "))
					out.push(line);
				if (elseBranch == null) {
					out.push(indent + "}");
				} else {
					out.push(indent + "} else {");
					for (line in renderStmtBlockContent(elseBranch, indent + "  "))
						out.push(line);
					out.push(indent + "}");
				}
				out;
			case SExpr(ECall(EField(EIdent("Sys"), "println"), args), _) if (args.length == 1):
				[indent + "std::cout << " + stringExpr(args[0]) + " << std::endl;"];
			case SExpr(ECall(EIdent("trace"), args), _) if (args.length >= 1):
				[indent + "std::cout << " + stringExpr(args[0]) + " << std::endl;"];
			case SExpr(ECall(ESuper, _), _):
				[indent + "/* base constructor call omitted */"];
			case SExpr(expr, _):
				[indent + renderExpr(expr) + ";"];
			case SVar(name, _typeHint, init, _):
				final rhs = init == null ? "0" : renderExpr(init);
					[indent + "auto " + sanitizeIdentifier(name) + " = " + rhs + ";"];
			case SReturn(expr, _):
				[indent + "return static_cast<int>(" + renderExpr(expr) + ");"];
			case SReturnVoid(_):
				[indent + "return 0;"];
			case _:
				throw "C++ source backend MVP unsupported statement: " + stmtKind(stmt);
		};
	}

	static function renderStmtBlockContent(stmt:HxStmt, indent:String):Array<String> {
		return switch (stmt) {
			case SBlock(stmts, _):
				renderStmts(stmts, indent);
			case _:
				renderStmt(stmt, indent);
		};
	}

	static function conditionExpr(expr:HxExpr):String {
		return switch (expr) {
			case EBinop(_, _, _):
				renderExpr(expr);
			case _:
				"(" + renderExpr(expr) + ")";
		};
	}

	static function renderExpr(expr:HxExpr):String {
		return switch (expr) {
			case ENull:
				"nullptr";
			case EBool(value):
				value ? "true" : "false";
			case EString(value):
				quoteString(value);
			case EInt(value):
				Std.string(value);
			case EFloat(value):
				Std.string(value);
			case EThis:
				"(*this)";
			case EIdent(name):
				sanitizeIdentifier(name);
			case EField(EThis, field):
				"this->" + sanitizeIdentifier(field);
			case ENew(typePath, args):
				sanitizeTypePath(typePath) + "(" + [for (arg in args) renderExpr(arg)].join(", ") + ")";
			case ECall(EField(EIdent("Sys"), "args"), args) if (args.length == 0):
				"__hxhx_args(argc, argv)";
			case ECall(EField(EIdent("NativeArray"), "create"), args) if (args.length == 1):
				"std::vector<int>(" + renderExpr(args[0]) + ")";
			case EArrayDecl(elements):
				arrayExpr(elements);
			case EField(receiver, "length"):
				"(" + renderExpr(receiver) + ".size())";
			case EArrayAccess(array, index):
				"(" + renderExpr(array) + "[" + renderExpr(index) + "])";
			case EAnon(fieldNames, fieldValues):
				anonExpr(fieldNames, fieldValues);
			case EField(receiver, field):
				"(" + renderExpr(receiver) + "." + sanitizeIdentifier(field) + ")";
			case ECall(EField(receiver, "indexOf"), args) if (args.length == 1 || args.length == 2):
				indexOfExpr(receiver, args);
			case ECall(EField(EIdent("Std"), "string"), args) if (args.length == 1):
				stringExpr(args[0]);
			case ECall(EField(receiver, method), args):
				renderExpr(receiver)
				+ "."
				+ sanitizeIdentifier(method)
				+ "("
				+ [for (arg in args) renderExpr(arg)].join(", ") + ")";
			case EBinop("+", left, right) if (isStringLike(left) || isStringLike(right)):
				"("
				+ stringExpr(left)
				+ " + "
				+ stringExpr(right)
				+ ")";
			case EBinop("=", left, right):
				renderExpr(left) + " = " + renderExpr(right);
			case EBinop(op, left, right) if (isSimpleBinaryOp(op)):
				"(" + renderExpr(left) + " " + op + " " + renderExpr(right) + ")";
			case EUnop("-", inner):
				"(-" + renderExpr(inner) + ")";
			case ETernary(cond, thenExpr, elseExpr):
				"("
				+ conditionExpr(cond)
				+ " ? "
				+ renderExpr(thenExpr)
				+ " : "
				+ renderExpr(elseExpr)
				+ ")";
			case EUntyped(inner):
				renderExpr(inner);
			case _:
				throw "C++ source backend MVP unsupported expression: " + exprKind(expr);
		};
	}

	static function stringExpr(expr:HxExpr):String {
		return switch (expr) {
			case EString(value):
				"std::string(" + quoteString(value) + ")";
			case EBool(_):
				"std::string(" + renderExpr(expr) + " ? \"true\" : \"false\")";
			case EInt(_) | EFloat(_):
				"std::to_string(" + renderExpr(expr) + ")";
			case ECall(EField(EIdent("Std"), "string"), args) if (args.length == 1):
				stringExpr(args[0]);
			case ECall(EField(_, "indexOf"), args) if (args.length == 1 || args.length == 2):
				"std::to_string(" + renderExpr(expr) + ")";
			case EField(_, "length"):
				"std::to_string(" + renderExpr(expr) + ")";
			case EArrayAccess(_, _):
				"std::string(" + renderExpr(expr) + ")";
			case EBinop("+", left, right) if (isStringLike(left) || isStringLike(right)):
				"("
				+ stringExpr(left)
				+ " + "
				+ stringExpr(right)
				+ ")";
			case ETernary(cond, thenExpr, elseExpr) if (isStringLike(thenExpr) && isStringLike(elseExpr)):
				"("
				+ conditionExpr(cond)
				+ " ? "
				+ stringExpr(thenExpr)
				+ " : "
				+ stringExpr(elseExpr)
				+ ")";
			case EIdent(name):
				"std::string(" + sanitizeIdentifier(name) + ")";
			case _:
				"std::to_string(" + renderExpr(expr) + ")";
		};
	}

	static function indexOfExpr(receiver:HxExpr, args:Array<HxExpr>):String {
		final source = renderExpr(receiver);
		final needle = stringExpr(args[0]);
		final start = args.length == 2 ? renderExpr(args[1]) : "0";
		return "__hxhx_index_of(" + source + ", " + needle + ", " + start + ")";
	}

	static function anonExpr(fieldNames:Array<String>, fieldValues:Array<HxExpr>):String {
		final struct = anonStruct(fieldNames, fieldValues);
		final values = [
			for (i in 0...struct.fieldNames.length)
				struct.fieldTypes[i] == "std::string" ? stringExpr(fieldValues[i]) : renderExpr(fieldValues[i])
		];
		return struct.name + "{" + values.join(", ") + "}";
	}

	static function arrayExpr(elements:Array<HxExpr>):String {
		final typeName = arrayElementType(elements);
		final values = [
			for (element in elements)
				typeName == "std::string" ? stringExpr(element) : renderExpr(element)
		];
		return "std::vector<" + typeName + ">{" + values.join(", ") + "}";
	}

	static function arrayElementType(elements:Array<HxExpr>):String {
		for (element in elements)
			if (isStringLike(element))
				return "std::string";
		for (element in elements)
			switch (element) {
				case EFloat(_):
					return "double";
				case _: // keep scanning
			}
		for (element in elements)
			switch (element) {
				case EBool(_):
					return "bool";
				case _: // keep scanning
			}
		return "int";
	}

	static function isStringLike(expr:HxExpr):Bool {
		return switch (expr) {
			case EString(_):
				true;
			case ECall(EField(EIdent("Std"), "string"), args) if (args.length == 1):
				true;
			case EBinop("+", left, right): isStringLike(left) || isStringLike(right);
			case ETernary(_, thenExpr, elseExpr): isStringLike(thenExpr) && isStringLike(elseExpr);
			case _:
				false;
		};
	}

	static function isSimpleBinaryOp(op:String):Bool {
		return op == "+" || op == "-" || op == "*" || op == "/" || op == "==" || op == "!=" || op == "<" || op == "<=" || op == ">" || op == ">=";
	}

	static function stmtKind(stmt:HxStmt):String {
		return switch (stmt) {
			case SBlock(_, _): "SBlock";
			case SVar(_, _, _, _): "SVar";
			case SIf(_, _, _, _): "SIf";
			case SForIn(_, _, _, _): "SForIn";
			case SForKeyValue(_, _, _, _, _): "SForKeyValue";
			case SWhile(_, _, _): "SWhile";
			case SDoWhile(_, _, _): "SDoWhile";
			case SSwitch(_, _, _, _): "SSwitch";
			case STry(_, _, _): "STry";
			case SBreak(_): "SBreak";
			case SContinue(_): "SContinue";
			case SThrow(_, _): "SThrow";
			case SReturn(_, _): "SReturn";
			case SReturnVoid(_): "SReturnVoid";
			case SExpr(expr, _): "SExpr(" + exprKind(expr) + ")";
		};
	}

	static function exprKind(expr:HxExpr):String {
		return switch (expr) {
			case ENull: "ENull";
			case EBool(_): "EBool";
			case EString(_): "EString";
			case EInt(_): "EInt";
			case EFloat(_): "EFloat";
			case EEnumValue(_): "EEnumValue";
			case EThis: "EThis";
			case ESuper: "ESuper";
			case EIdent(name): "EIdent(" + name + ")";
			case EField(receiver, field): "EField(" + exprKind(receiver) + "." + field + ")";
			case ECall(callee, _): "ECall(" + exprKind(callee) + ")";
			case EMacroExpr(_, _): "EMacroExpr";
			case EMacroType(_): "EMacroType";
			case ELambda(_, _): "ELambda";
			case EArrayComprehension(_, _, _): "EArrayComprehension";
			case EArrayDecl(_): "EArrayDecl";
			case EArrayAccess(_, _): "EArrayAccess";
			case ERange(_, _): "ERange";
			case EAnon(_, _): "EAnon";
			case EUnop(op, _): "EUnop(" + op + ")";
			case EBinop(op, _, _): "EBinop(" + op + ")";
			case ETernary(_, _, _): "ETernary";
			case ESwitchRaw(_): "ESwitchRaw";
			case ESwitch(_, _, _): "ESwitch";
			case ETryCatchRaw(_): "ETryCatchRaw";
			case ENew(typePath, _): "ENew(" + typePath + ")";
			case ECast(_, _): "ECast";
			case EUntyped(_): "EUntyped";
			case EUnsupported(reason): "EUnsupported(" + reason + ")";
		};
	}

	static function quoteString(value:String):String {
		var out = "\"";
		for (i in 0...value.length) {
			final code = value.charCodeAt(i);
			out += switch (code) {
				case 34: "\\\"";
				case 92: "\\\\";
				case 10: "\\n";
				case 13: "\\r";
				case 9: "\\t";
				case _: String.fromCharCode(code);
			};
		}
		return out + "\"";
	}

	static function sanitizeIdentifier(name:String):String {
		if (name == null || name.length == 0)
			return "_";
		final out = new StringBuf();
		for (i in 0...name.length) {
			final c = name.charAt(i);
			final ok = (c >= "a" && c <= "z") || (c >= "A" && c <= "Z") || c == "_" || (i > 0 && c >= "0" && c <= "9");
			out.add(ok ? c : "_");
		}
		final s = out.toString();
		final first = s.charAt(0);
		if (first >= "0" && first <= "9")
			return "_" + s;
		return switch (s) {
			case "auto" | "bool" | "break" | "case" | "catch" | "class" | "const" | "continue" | "delete" | "do" | "double" | "else" | "false" | "float" |
				"for" | "if" | "int" | "long" | "namespace" | "new" | "nullptr" | "private" | "public" | "return" | "short" | "static" | "std" | "struct" |
				"switch" | "this" | "throw" | "true" | "try" | "void" | "while":
				s
				+ "_";
			case _:
				s;
		};
	}

	static function executablePath(outputDir:String, className:String):String {
		return Path.join([outputDir, className]);
	}

	static function ensureDirectory(path:String):Void {
		if (path == null || path.length == 0 || sys.FileSystem.exists(path))
			return;
		final parent = Path.directory(path);
		if (parent != null && parent.length > 0 && parent != path)
			ensureDirectory(parent);
		sys.FileSystem.createDirectory(path);
	}

	static function ensureParentDirectory(filePath:String):Void {
		final parent = Path.directory(filePath);
		if (parent != null && parent.length > 0)
			ensureDirectory(parent);
	}

	static function commandExists(name:String):Bool {
		return Sys.command("sh", ["-c", "command -v " + name + " >/dev/null 2>&1"]) == 0;
	}

	static function cppCompilerCommand():Null<String> {
		for (candidate in ["c++", "g++", "clang++"])
			if (commandExists(candidate))
				return candidate;
		return null;
	}

	static function sanitizeTypePath(path:String):String {
		if (path == null || path.length == 0)
			return "_";
		return sanitizeIdentifier(StringTools.replace(path, ".", "_"));
	}

	static function cppTypeHint(typeHint:String):String {
		final hint = typeHint == null ? "" : StringTools.trim(typeHint);
		return switch (hint) {
			case "String" | "StdTypes.String":
				"std::string";
			case "Int" | "StdTypes.Int":
				"int";
			case "Float" | "StdTypes.Float":
				"double";
			case "Bool" | "StdTypes.Bool":
				"bool";
			case _ if (StringTools.startsWith(hint, "Array<") && StringTools.endsWith(hint, ">")):
				"std::vector<" + cppTypeHint(hint.substr("Array<".length, hint.length - "Array<".length - 1)) + ">";
			case _:
				"std::string";
		};
	}

	static function cppDefaultValue(typeName:String):String {
		return switch (typeName) {
			case "std::string":
				"std::string()";
			case "double":
				"0.0";
			case "bool":
				"false";
			case _ if (StringTools.startsWith(typeName, "std::vector<")):
				"{}";
			case _:
				"0";
		};
	}
}
