package backend.vm;

import backend.BackendContext;
import backend.EmitArtifact;
import backend.EmitResult;
import backend.GenIrProgram;
import haxe.io.Path;
import sys.FileSystem;
import sys.io.File;

/**
	MVP native Neko target core.

	Why
	- Full1 C++/hxcpp evidence now reaches hxcpp's `tools/hxcpp/compile.hxml`,
	  which compiles a Neko build tool under `HXHX_FORBID_STAGE0=1`.
	- Keeping Neko as a fail-fast placeholder hides the next real blocker behind
	  target-routing noise. This core moves Neko to an honest source-emission seam.

	What
	- Emits a small Neko source program from the Stage3 GenIR subset.
	- Compiles that source to `.n` bytecode with `nekoc` when available.
	- Supports an internal `-D hxhx_neko_source_only` diagnostic mode for focused
	  source-shape tests on machines that only have the Neko runtime shim.

	How
	- Generate simple top-level Neko functions named from Haxe class/static-method
	  paths (`Main.main` -> `Main_main`).
	- Fail fast with target-specific unsupported diagnostics for constructs outside
	  the MVP instead of fabricating runtime/library behavior.
**/
class NekoTargetCore {
	public static inline var SOURCE_ONLY_DEFINE = "hxhx_neko_source_only";

	public static function emit(program:GenIrProgram, context:BackendContext):EmitResult {
		final outputPath = outputBytecodePath(context);
		final sourcePath = sourcePathForBytecode(outputPath);
		ensureDirectory(Path.directory(sourcePath));

		final source = renderProgram(program, context);
		File.saveContent(sourcePath, source);

		if (context.hasDefine(SOURCE_ONLY_DEFINE)) {
			return new EmitResult(sourcePath, [new EmitArtifact("entry_neko_source", sourcePath)], false);
		}

		final nekoc = resolveNekoc();
		if (nekoc == null) {
			throw "Neko native backend requires `nekoc` to compile Neko source to .n bytecode. Install the Neko compiler or rerun with -D "
				+ SOURCE_ONLY_DEFINE
				+ " for source-only diagnostics.";
		}

		final code = Sys.command(nekoc, [sourcePath]);
		if (code != 0)
			throw "nekoc failed with exit code " + code + " while compiling " + sourcePath;
		if (!FileSystem.exists(outputPath))
			throw "nekoc completed but did not produce expected bytecode artifact: " + outputPath;
		return new EmitResult(outputPath, [
			new EmitArtifact("entry_neko_bytecode", outputPath),
			new EmitArtifact("neko_source", sourcePath)
		], false);
	}

	static function outputBytecodePath(context:BackendContext):String {
		if (context.outputFileHint != null && context.outputFileHint.length > 0)
			return Path.normalize(context.outputFileHint);
		final main = context.mainModule == null || context.mainModule.length == 0 ? "main" : context.mainModule.split(".").pop();
		return Path.join([context.outputDir, main + ".n"]);
	}

	static function sourcePathForBytecode(outputPath:String):String {
		final dir = Path.directory(outputPath);
		final base = Path.withoutExtension(Path.withoutDirectory(outputPath));
		return Path.join([dir, base + ".neko"]);
	}

	static function resolveNekoc():Null<String> {
		final explicit = Sys.getEnv("NEKOC_BIN");
		if (explicit != null && explicit.length > 0 && commandWorks(explicit))
			return explicit;
		return commandWorks("nekoc") ? "nekoc" : null;
	}

	static function commandWorks(command:String):Bool {
		final code = Sys.command("sh", ["-c", "command -v " + shellQuote(command) + " >/dev/null 2>&1"]);
		return code == 0;
	}

	static function renderProgram(program:GenIrProgram, context:BackendContext):String {
		final modules = program.getTypedModules();
		if (modules.length == 0)
			throw "Neko native backend received an empty program";

		final out = new Array<String>();
		out.push("// Generated by hxhx native Neko backend MVP");
		out.push("");

		final main = findMain(modules, context.mainModule);
		if (main == null)
			throw "Neko native backend requires a static main entrypoint";
		final mainDecl = main.decl;
		final mainClass = main.cls;
		final pkg = HxModuleDecl.getPackagePath(mainDecl);
		final className = HxClassDecl.getName(mainClass);
		final fullClassName = pkg == null || pkg.length == 0 ? className : pkg + "." + className;
		for (field in HxClassDecl.getFields(mainClass)) {
			if (!HxFieldDecl.getIsStatic(field))
				unsupported("instance field", fullClassName + "." + HxFieldDecl.getName(field));
		}
		for (fn in HxClassDecl.getFunctions(mainClass)) {
			if (!HxFunctionDecl.getIsStatic(fn))
				unsupported("instance method", fullClassName + "." + HxFunctionDecl.getName(fn));
			renderFunction(out, fullClassName, fn);
		}
		final entry = mangleFunction(fullClassName, "main");
		out.push(entry + "();");
		out.push("");
		return out.join("\n");
	}

	static function findMain(modules:Array<TypedModule>, requested:String):Null<{decl:HxModuleDecl, cls:HxClassDecl}> {
		var fallback:Null<{decl:HxModuleDecl, cls:HxClassDecl}> = null;
		for (typed in modules) {
			final decl = typed.getParsed().getDecl();
			final pkg = HxModuleDecl.getPackagePath(decl);
			for (cls in HxModuleDecl.getClasses(decl)) {
				final className = HxClassDecl.getName(cls);
				final fullClassName = pkg == null || pkg.length == 0 ? className : pkg + "." + className;
				for (fn in HxClassDecl.getFunctions(cls)) {
					if (HxFunctionDecl.getIsStatic(fn) && HxFunctionDecl.getName(fn) == "main") {
						final found = {decl: decl, cls: cls};
						if (fallback == null)
							fallback = found;
						if (matchesMain(requested, fullClassName))
							return found;
					}
				}
			}
		}
		return fallback;
	}

	static function renderFunction(out:Array<String>, fullClassName:String, fn:HxFunctionDecl):Void {
		final args = new Array<String>();
		for (arg in HxFunctionDecl.getArgs(fn))
			args.push(safeIdent(arg.name));
		out.push("var " + mangleFunction(fullClassName, HxFunctionDecl.getName(fn)) + " = function(" + args.join(", ") + ") {");
		for (stmt in HxFunctionDecl.getBody(fn))
			renderStmt(out, stmt, "  ");
		out.push("}");
		out.push("");
	}

	static function renderStmt(out:Array<String>, stmt:HxStmt, indent:String):Void {
		switch (stmt) {
			case SBlock(stmts, _):
				out.push(indent + "{");
				for (s in stmts)
					renderStmt(out, s, indent + "  ");
				out.push(indent + "}");
			case SVar(name, _, init, _):
				out.push(indent + "var " + safeIdent(name) + (init == null ? "" : " = " + renderExpr(init)) + ";");
			case SIf(cond, thenBranch, elseBranch, _):
				out.push(indent + "if " + renderExpr(cond) + " ");
				renderStmt(out, thenBranch, indent);
				if (elseBranch != null) {
					out.push(indent + "else ");
					renderStmt(out, elseBranch, indent);
				}
			case SWhile(cond, body, _):
				out.push(indent + "while " + renderExpr(cond) + " ");
				renderStmt(out, body, indent);
			case SReturnVoid(_):
				out.push(indent + "return null;");
			case SReturn(expr, _):
				out.push(indent + "return " + renderExpr(expr) + ";");
			case SExpr(expr, _):
				out.push(indent + renderExpr(expr) + ";");
			case SBreak(_):
				out.push(indent + "break;");
			case SContinue(_):
				out.push(indent + "continue;");
			case SThrow(expr, _):
				out.push(indent + "$throw(" + renderExpr(expr) + ");");
			case SForIn(_, _, _, _) | SForKeyValue(_, _, _, _, _) | SDoWhile(_, _, _) | SSwitch(_, _, _, _) | STry(_, _, _):
				unsupported("statement", Std.string(stmt));
		}
	}

	static function renderExpr(expr:HxExpr):String {
		return switch (expr) {
			case ENull:
				"null";
			case EBool(value):
				value ? "true" : "false";
			case EString(value):
				quote(value);
			case EInt(value):
				Std.string(value);
			case EFloat(value):
				Std.string(value);
			case EEnumValue(name):
				quote(name);
			case EThis:
				unsupportedExpr("this");
			case ESuper:
				unsupportedExpr("super");
			case EIdent(name):
				safeIdent(name);
			case EField(obj, field):
				renderExpr(obj) + "." + safeIdent(field);
			case ECall(callee, args):
				renderCall(callee, args);
			case EUnop(op, inner):
				"(" + op + renderExpr(inner) + ")";
			case EBinop(op, left, right):
				"(" + renderExpr(left) + " " + op + " " + renderExpr(right) + ")";
			case ETernary(cond, thenExpr, elseExpr):
				"("
				+ renderExpr(cond)
				+ " ? "
				+ renderExpr(thenExpr)
				+ " : "
				+ renderExpr(elseExpr)
				+ ")";
			case ECast(inner, _) | EUntyped(inner) | EMacroExpr(inner, _):
				renderExpr(inner);
			case EArrayDecl(values):
				"[" + [for (v in values) renderExpr(v)].join(", ") + "]";
			case EArrayAccess(array, index):
				renderExpr(array) + "[" + renderExpr(index) + "]";
			case EAnon(fieldNames, fieldValues):
				renderAnon(fieldNames, fieldValues);
			case EArrayComprehension(_, _, _, _) | ERange(_, _) | ELambda(_, _) | ENew(_, _) | EMacroType(_) | ETryCatchRaw(_) | ESwitchRaw(_) |
				ESwitch(_, _, _) | EUnsupported(_):
				unsupportedExpr(exprTag(expr));
		}
	}

	static function exprTag(expr:HxExpr):String {
		return switch (expr) {
			case ENull: "ENull";
			case EBool(_): "EBool";
			case EString(_): "EString";
			case EInt(_): "EInt";
			case EFloat(_): "EFloat";
			case EEnumValue(_): "EEnumValue";
			case EThis: "EThis";
			case ESuper: "ESuper";
			case EIdent(_): "EIdent";
			case EField(_, _): "EField";
			case ECall(_, _): "ECall";
			case EMacroExpr(_, _): "EMacroExpr";
			case EMacroType(typeText): "EMacroType(" + typeText + ")";
			case ELambda(_, _): "ELambda";
			case ETryCatchRaw(raw): "ETryCatchRaw(" + raw + ")";
			case ESwitchRaw(raw): "ESwitchRaw(" + raw + ")";
			case ESwitch(_, _, _): "ESwitch";
			case ENew(typePath, _): "ENew(" + typePath + ")";
			case EUnop(op, _): "EUnop(" + op + ")";
			case EBinop(op, _, _): "EBinop(" + op + ")";
			case ETernary(_, _, _): "ETernary";
			case EAnon(_, _): "EAnon";
			case EArrayComprehension(_, _, _, _): "EArrayComprehension";
			case EArrayDecl(_): "EArrayDecl";
			case EArrayAccess(_, _): "EArrayAccess";
			case ERange(_, _): "ERange";
			case ECast(_, typeHint): "ECast(" + typeHint + ")";
			case EUntyped(_): "EUntyped";
			case EUnsupported(raw): "EUnsupported(" + raw + ")";
		}
	}

	static function renderAnon(fieldNames:Array<String>, fieldValues:Array<HxExpr>):String {
		final tmp = "__hxhx_o";
		final parts = ["(function() { var " + tmp + " = $new(null);"];
		final count = fieldNames.length < fieldValues.length ? fieldNames.length : fieldValues.length;
		for (i in 0...count)
			parts.push(tmp + "." + safeIdent(fieldNames[i]) + " = " + renderExpr(fieldValues[i]) + ";");
		parts.push("return " + tmp + "; })()");
		return parts.join(" ");
	}

	static function renderCall(callee:HxExpr, args:Array<HxExpr>):String {
		final renderedArgs = [for (arg in args) renderExpr(arg)];
		switch (callee) {
			case EIdent("trace"):
				return "$print(" + renderedArgs.concat([quote("\n")]).join(", ") + ")";
			case EField(EIdent("Sys"), "print"):
				return "$print(" + renderedArgs.join(", ") + ")";
			case EField(EIdent("Sys"), "println"):
				return "$print(" + renderedArgs.concat([quote("\n")]).join(", ") + ")";
			case EField(EIdent(className), method):
				return mangleFunction(className, method) + "(" + renderedArgs.join(", ") + ")";
			case _:
				return renderExpr(callee) + "(" + renderedArgs.join(", ") + ")";
		}
	}

	static function matchesMain(requested:String, fullClassName:String):Bool {
		return requested == null || requested.length == 0 || requested == fullClassName || requested == fullClassName.split(".").pop();
	}

	static function mangleFunction(fullClassName:String, method:String):String {
		return safeIdent(StringTools.replace(fullClassName, ".", "_") + "_" + method);
	}

	static function safeIdent(name:String):String {
		if (name == null || name.length == 0)
			return "_";
		final out = new StringBuf();
		for (i in 0...name.length) {
			final c = name.charCodeAt(i);
			final ok = (c >= "a".code && c <= "z".code)
				|| (c >= "A".code && c <= "Z".code)
				|| c == "_".code
				|| (i > 0 && c >= "0".code && c <= "9".code);
			out.addChar(ok ? c : "_".code);
		}
		return out.toString();
	}

	static function quote(value:String):String {
		return '"' + StringTools.replace(StringTools.replace(StringTools.replace(value, "\\", "\\\\"), "\n", "\\n"), '"', '\\"') + '"';
	}

	static function shellQuote(value:String):String {
		return "'" + StringTools.replace(value, "'", "'\\''") + "'";
	}

	static function ensureDirectory(path:String):Void {
		if (path == null || path.length == 0 || FileSystem.exists(path))
			return;
		final parent = Path.directory(path);
		if (parent != null && parent.length > 0 && parent != path)
			ensureDirectory(parent);
		FileSystem.createDirectory(path);
	}

	static function unsupported(kind:String, detail:String):String {
		throw "Neko native backend MVP does not yet support " + kind + ": " + detail;
	}

	static function unsupportedExpr(detail:String):String {
		return unsupported("expression", detail);
	}
}
