# 1 "Main.ml"
(* Generated by reflaxe.ocaml (WIP) *)
(* Haxe type: Main *)

let __reflaxe_ocaml__ = ()

type t = { __hx_type : Obj.t }

let create = fun () -> let self = ({ __hx_type = HxType.class_ "Main" } : t) in (
  ignore ();
  self
)

let __empty = fun () -> ({ __hx_type = HxType.class_ "Main" } : t)

let main = fun () -> (
  ignore (Native.Mod.f ~x:1 2 ?z:(let __optarg_1 = Obj.repr (Obj.repr 3) in if __optarg_1 == HxRuntime.hx_null then None else Some (Obj.obj __optarg_1)));
  ignore (Native.Mod.f ~x:1 2 ?z:None);
  Native.Mod.f ~x:1 2
)